package.json

:rocket:
gulp-shell just published version 0.5.0, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>

Updated gulp-shell to version 0.5.0

---

package.json

:rocket:
request-json-light just published version 0.5.21, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>

Updated request-json-light to version 0.5.21

---

backend/merge.coffee
tests/unit/merge.coffee

In some particular cases, it could crash the application.

Fix ensureParentExists to set a side

---

backend/merge.coffee
backend/remote/index.coffee
backend/remote/watcher.coffee
package.json
tests/unit/merge.coffee

A small optimization to avoid some useless operations and reduce noise.

Avoid useless puts

---

backend/merge.coffee

Another small fix for moving a not-empty folder.

Fix moving a folder with files inside

---

backend/merge.coffee
backend/pouch.coffee
backend/remote/index.coffee
tests/unit/remote/index.coffee

When a local file was overwritten, the upload of the binary failed. This PR fixes this bug.

Fix overwrite

---

backend/local/index.coffee
backend/local/watcher.coffee
backend/merge.coffee
backend/remote/index.coffee
backend/remote/watcher.coffee
doc/design.md
tests/unit/local/index.coffee
tests/unit/local/watcher.coffee

On UNIX, this field is used to chmod +x executable files.

Add executable field to files

---

backend/app.coffee
bin/cli.coffee
tests/helpers/integration.coffee

- Add a default for devicename when adding a remote
- Ask confirmation before reset-database
- Validate URL for add-remote-cozy

Improve cli

---

backend/local/watcher.coffee
backend/merge.coffee
backend/remote/couch.coffee
backend/remote/watcher.coffee
doc/design.md
tests/integration/image_from_mobile.coffee
tests/unit/local/watcher.coffee

Fix for images from mobile: they have no checksum and were wrongly detected as conflicts.
Note: this PR also includes commits from #171.

Fix mobile images

---

.travis.yml
package.json
src/app.coffee
src/remote/index.coffee
src/remote/watcher.coffee
test/integration/devices.coffee

see https://github.com/cozy-labs/cozy-desktop/pull/232

Add filter in couch to limit bandwidth

---

bin/fauxton.coffee
gui/app/main.js
gui/lib/Account.elm
src/app.coffee
src/bin/cli.coffee
src/config.coffee
src/local/index.coffee
src/local/watcher.coffee
src/remote/watcher.coffee
test/helpers/config.coffee
test/helpers/integration.coffee
test/integration/cancel.coffee
test/integration/conflict_folder_file.coffee
test/integration/conflict_move_file.coffee
test/integration/conflict_remote_docs.coffee
test/integration/conflict_two_files.coffee
test/integration/conflict_two_folders.coffee
test/integration/image_from_mobile.coffee
test/integration/move_file.coffee
test/integration/pull.coffee
test/integration/push.coffee
test/integration/swap_files.coffee
test/unit/config.coffee
test/unit/local/index.coffee
test/unit/local/watcher.coffee

- Add a spinner on the unlink button
- Remove the recent activities and logs on lunk, to avoid showing them if cozy-desktop is used again later
- Enhance the error management on unlink

Many things about unlink

---

README.md

Signed-off-by: Philippe Coval <rzr@gna.org>

debian: install npm before using it

---

gui/package.json

See https://github.com/electron-userland/electron-builder/issues/635

Downgrade electron-builder

---

src/merge.coffee

Fix an error on the resolution of an initial conflict

---

gui/app/main.js

Remove some hacks that were needed for previous versions of electron

---

.travis.yml
doc/test.md
test/helpers/integration.coffee
test/helpers/password.coffee

To match [cozy-proxy expectations](cozy/cozy-proxy@767dd1c)

Use a stronger test password

---

src/local/index.js
src/merge.js
src/metadata.js
src/pouch.js
src/remote/v2/index.js
src/sync.js
test/unit/metadata.js
test/unit/pouch.js
test/unit/remote/watcher.js

Copied from v2 code to the metadata module.

Metadata helpers

---

src/file_stream_provider.js
src/remote/index.js

Needed to reimplement `Remote#addFile()` with Flow typechecks.

Remote class properties

---

src/prep.js

Should be Merge#putFolder(), addFolder() doesn't exist

prep: Fix Merge#addFolder() call

---

.env.test
package.json
src/remote/cozy.js
src/remote/index.js
test/builders/remote/base.js
test/unit/remote/index.js
yarn.lock

Works with https://github.com/cozy/cozy-client-js/pull/78 and https://github.com/cozy/cozy-stack/pull/305

Remote overwrite file

---

package.json
src/conversion.js
src/remote/index.js
test/unit/conversion.js
test/unit/remote/index.js
yarn.lock

Needs https://github.com/cozy/cozy-client-js/pull/87 + `yarn upgrade cozy-client-js`

remote: Add executable support in addFile()

---

src/merge.js
src/pouch.js
src/prep.js
test/unit/helpers_merge.js
test/unit/prep.js

Promisify Prep and Merge

---

package.json
src/bin/repl.js
src/local/watcher.js
src/remote/watcher.js
src/sync.js

Debug improvements

---

src/metadata.js
src/prep.js
src/remote/watcher.js
test/unit/remote/watcher.js

Extract validation from prep

---

src/local/watcher.js
src/merge.js
src/prep.js
src/side.js

Sidename type

---

gui/app/main.js
gui/package.json
gui/yarn.lock
package.json
src/remote/v2/couch.js
test/builders/remote/base.js
yarn.lock

Update node dependencies

---

src/local/watcher.js

At least until we find a better solution.

local/watcher: Use polling on Windows

---

src/sync.js

It will need a new release of cozy-client-js, with https://github.com/cozy/cozy-client-js/commit/badc5c4ffe2f5920fd0d5ef9a3d3808bf9185f5d, to work

Improve revoked device detection

---

src/app.js
src/bin/cli.js
src/local/index.js
src/remote/index.js
src/sync.js
test/unit/remote/index.js

Fix recent activities in GUI

---

src/local/index.js
src/local/watcher.js
src/logger.js
src/merge.js
src/pouch.js
src/prep.js
src/remote/index.js
src/remote/watcher.js
src/sync.js

- Add path almost everywhere (even to errors)
- No big json data structure at info level
- Log more detailed messages at debug level
- Log very low-level stuff (full metadata, chokidar stuff...) at trace level

Improve logging

---

CHANGELOG.md
gui/app/package.json
package.json

Release 3.0.0 beta.3

---

CHANGELOG.md
cli/package.json
gui/package.json

Needs https://github.com/cozy-labs/cozy-desktop/pull/763

Release 3.0.0-beta.6

---

.travis.yml
cli/src/local/index.js
cli/src/local/watcher.js
cli/src/metadata.js
cli/src/prep.js
cli/src/remote/watcher.js
cli/src/utils/pending.js
cli/test/builders/metadata/dir.js
cli/test/builders/metadata/file.js
cli/test/unit/local/watcher.js
cli/test/unit/metadata.js
cli/test/unit/remote/watcher.js

Needs https://github.com/cozy-labs/cozy-desktop/pull/771

Fix initial scan

---

cli/src/utils/path.js
cli/test/helpers/conflict.js
cli/test/helpers/local.js
cli/test/helpers/remote.js
cli/test/helpers/sync_dir.js
cli/test/integration/v3/conflict_resolution.js
cli/test/unit/local/index.js
cli/test/unit/remote/cozy.js

Those are test improvements I introduced while working on the conflict resolution retry limit.
Submitting them in a separate PR since I don't know how the retry limit feature will turn out and those changes could be useful somewhere else.

Refactor tests

---

cli/package.json
cli/test/helpers/sinon_stub_promise.js
cli/test/mocha.opts
cli/test/unit/helpers_merge.js
cli/test/unit/prep.js
cli/test/unit/remote/watcher.js
cli/test/unit/sync.js
cli/yarn.lock

Sinon.js includes everywhing needed to stub promises since version 2.0.
And it even works better :)

Get rid of sinon-stub-promise

---

gui/src/elm/Help.elm

Translate default support request message

---

gui/styles/_two_panes.styl

Fix "Show more files" button styling

---

gui/main.js
gui/package.json
gui/ports.js
gui/src/elm/Dashboard.elm
gui/src/elm/Help.elm
gui/src/elm/Main.elm
gui/src/elm/Settings.elm
gui/src/elm/TwoPanes.elm
gui/src/main/appmenu.js
gui/src/main/autolaunch.js
gui/src/main/autoupdate.js
gui/src/main/fileutils.js
gui/src/main/help.window.js
gui/src/main/i18n.js
gui/src/main/incompatibilitiesmsg.js
gui/src/main/lastfiles.js
gui/src/main/onboarding.window.js
gui/src/main/shortcut.js
gui/src/main/tray.js
gui/src/main/tray.window.js
gui/src/main/window_behaviour.js
gui/styles/_two_panes.styl
gui/styles/app.styl
gui/yarn.lock

The code needs some cleanup but the function should be here.

Systray ui

---

cli/package.json

Also use it in test:unit:coverage CLI script.

Introduce mocha:coverage CLI script

---

cli/src/local/checksumer.js
cli/src/local/index.js
cli/src/local/watcher.js
cli/test/unit/local/checksumer.js
cli/test/unit/local/watcher.js

Needs https://github.com/cozy-labs/cozy-desktop/pull/820

Extract checksum computation from LocalWatcher#createDoc()

---

cli/src/local/checksumer.js
cli/src/local/event_buffer.js
cli/src/local/index.js
cli/src/local/watcher.js
cli/test/unit/local/checksumer.js
cli/test/unit/local/watcher.js

Needs https://github.com/cozy-labs/cozy-desktop/pull/821

Promisify more LocalWatcher methods

---

cli/src/local/checksumer.js
cli/src/local/event_buffer.js
cli/src/local/index.js
cli/src/local/watcher.js
cli/test/unit/local/checksumer.js
cli/test/unit/local/watcher.js

Needs https://github.com/cozy-labs/cozy-desktop/pull/822

Checksum on flush

---

gui/main.js
gui/src/main/tray.window.js

Thanks @jsilvestre for logs :heart:

Fix application GUI startup issues

---

cli/src/local/watcher.js
cli/src/pouch.js
cli/src/remote/watcher.js
cli/src/sync.js
cli/test/helpers/integration.js
cli/test/unit/local/watcher.js
cli/test/unit/pouch.js
cli/test/unit/remote/watcher.js

Needs https://github.com/cozy-labs/cozy-desktop/pull/857

Fix sync lock

---

cli/test/helpers/pouch.js
cli/test/unit/merge.js
cli/test/unit/pouch.js
cli/test/unit/remote/watcher.js
cli/test/unit/sync.js

This breaks a bunch of tests which this commit also fixes.

test/helpers/pouch: Make sure saved metadata have valid ids

---

gui/main.js

gui: Limit oauth window height for small screens

---

CHANGELOG.md
KNOWN_ISSUES.md
cli/package.json
gui/package.json

Includes a separate `KNOWN_ISSUES.md` file so we don't end up copy-pasting everything between `CHANGELOG.md` and every release notes.

Release 3.2.0 beta.2

---

cli/test/scenarios/add_delete_dir_and_file/scenario.js
cli/test/scenarios/add_file/scenario.js
cli/test/scenarios/add_trash_dir/scenario.js
cli/test/scenarios/add_trash_file/scenario.js
cli/test/scenarios/change_file/scenario.js
cli/test/scenarios/create_dir_into_moved_one/scenario.js
cli/test/scenarios/create_dirs/scenario.js
cli/test/scenarios/delete_dir_permanently/scenario.js.DISABLED
cli/test/scenarios/delete_file_permanently/scenario.js.DISABLED
cli/test/scenarios/index.js
cli/test/scenarios/move_and_trash_dir/scenario.js
cli/test/scenarios/move_and_trash_file/scenario.js
cli/test/scenarios/move_dir_from_the_outside/scenario.js
cli/test/scenarios/move_dir_into_created_one/scenario.js
cli/test/scenarios/move_dir_reversed_events/scenario.js
cli/test/scenarios/move_dir_successive_same_level/scenario.js
cli/test/scenarios/move_dir_successive_with_delay/scenario.js
cli/test/scenarios/move_dir_with_content/scenario.js
cli/test/scenarios/move_file/scenario.js
cli/test/scenarios/move_file_reversed_events/scenario.js
cli/test/scenarios/move_file_successive/scenario.js
cli/test/scenarios/move_file_successive_2/scenario.js
cli/test/scenarios/move_from_inside_move/scenario.js
cli/test/scenarios/move_two_dirs/scenario.js
cli/test/scenarios/move_two_dirs_same_prefix/scenario.js
cli/test/scenarios/move_two_files/scenario.js
cli/test/scenarios/replace_dir_with_file/scenario.js.DISABLED
cli/test/scenarios/replace_file_with_dir/scenario.js.DISABLED
cli/test/scenarios/restore/scenario.js.DISABLED
cli/test/scenarios/trash_dir_with_content/scenario.js

Disabled ones were temporarily reenabled to make sure they were valid.

test/scenarios: Type-check all scenarios with flow types

---

gui/js/lastfiles.js
gui/js/tray.window.js
gui/main.js

- more logs on logout / exit / restart
- cleanup lastFiles on logout

Add lost changes from hotfix branch

---

gui/js/lastfiles.js
gui/js/tray.window.js
gui/main.js

- lastFiles.clean() is not needed anymore
- Same for app.lastFiles

gui: Last files cache is already removed by core

---

CHANGELOG.md
gui/main.js
package.json

This includes https://github.com/cozy-labs/cozy-desktop/pull/939

Release v3.4.2 beta.6

---

core/merge.js
core/sync.js

Also add Merge#moveFolderAsync() timestamps notice

sync: Log change on error

---

elm-package.json
gui/elm/Address.elm
test/elm/AddressTest.elm
test/elm/elm-package.json

- Allow trailing slash
- Allow hash

gui: Effectively handle hosted Cozy app URL as onboarding address

---

doc/usage/linux.md

Src: https://forum.cozy.io/t/cozy-desktop-pour-linux/4843/14

[Doc][Linux] Works on Mageia 6

---

test/support/doubles/side.js
test/unit/sync.js

This will help us to add new unit tests and complete #975

core: Clean up Sync unit tests

---

core/merge.js
core/metadata.js
core/remote/watcher.js
core/sync.js
test/integration/platform_incompatibilities.js
test/support/helpers/integration.js
test/support/helpers/remote.js
test/unit/remote/watcher.js

Platform incompatibilities

---

.flowconfig

Will fix flow (broken on master, my bad).

flow: Ignore ach example json

---

doc/developer/setup.md

Added instructions to setup a development environment on Ubuntu

---

core/pouch.js
core/remote/watcher.js
core/sync.js
test/integration/platform_incompatibilities.js

 core/sync: Actually bring back child file on compat->incompat->compat move

---

.jq
package.json

jq: Introduce filters & scripts

---

KNOWN_ISSUES.md

Thanks to @aenario for finding it.

doc: Link to electron GPU-related issue [ci skip]

---

core/metadata.js
core/sync.js
test/integration/mtime-update.js

Waiting for Travis to see if this breaks anything else.

core/metadata: Add test & fix to not update file if only mtime has changed

---

core/config.js
doc/usage/linux.md
gui/js/tray.window.js
test/unit/config.js

gui: Make the app easier to use on i3wm

---

gui/js/proxy.js

It generates a lot of noise in logs.

gui: Don't log validated certificate

---

core/ignore.js
test/unit/ignore.js

Last 3 commits. I'll rebase on master once #1069 is merged.

Actually ignore Microsoft Office temporary files on Windows

---

.jq
doc/developer/log_analysis.md

- Add stack trace example
- Add debug level filters
- Add Metadata component filter
- Add test-related filters
- Add Pouch component filter

jq: More filters & documentation [ci skip]

---

core/local/index.js
core/local/watcher.js
core/merge.js
core/pouch.js
core/prep.js
core/remote/watcher.js
core/sync.js

Also add a few missing info and adjust some log levels.
Should not really impact logs size, be it better or worse.

core: Stop logging related things separately

---

core/local/watcher.js
core/metadata.js
core/remote/watcher.js
test/support/builders/metadata/base.js
test/support/builders/metadata/dir.js
test/support/builders/metadata/file.js
test/unit/local/watcher.js

So they don't end up in the Cozy trash.

Don't detect incompatible docs as unlinked on initial scan

---

dev/capture/local.js
dev/chokidar.js
package.json

dev: Add capture script for complex FileManager operations

---

test/unit/merge.js

test/unit/merge: Promisify #moveTo hint tests

---

core/local/analysis.js
core/remote/change.js
test/scenarios/move_files_a_to_c_and_b_to_a/local/darwin.json
test/scenarios/move_files_a_to_c_and_b_to_a/scenario.js

Waiting for CI to see if this breaks something else.

Test & fix : a -> c & b -> a bug

---

README.md
doc/developer/requirements.md
doc/developer/setup.md

Let's discuss here what could be enhanced.
The goal is the `README.md` file, the rest of the documentation under `doc/` will be treaten on a next step
This PR is related to #1141
---

Improve documentation

---

core/metadata.js
core/pouch.js
test/support/helpers/pouch.js
test/unit/merge.js
test/unit/metadata.js
test/unit/regressions/850.js
test/unit/sync.js

core/pouch: add checks for invariants

---

KNOWN_ISSUES.md
core/local/index.js
core/metadata.js
core/remote/index.js
test/integration/executable.js
test/support/builders/remote/base.js
test/support/builders/remote/file.js
test/support/helpers/context_dir.js
test/support/helpers/integration.js
test/support/helpers/platform.js
test/unit/local/index.js
test/unit/metadata.js
test/unit/remote/index.js

core: Fix executables handling

---

core/local/change.js
test/unit/local/analysis.js

core/local/change: No useless undefined wip property

---

CHANGELOG.md
package.json
test/unit/local/analysis.js

release: 3.10.0-beta.4

---

gui/styles/_wizard.styl

gui/onboarding: Respect FS case in folder selector

---

test/integration/move.js
test/scenarios/move_dir_and_update_subfile_remotely/scenario.js.DISABLED

So we can fix them at some point.

test: Reproduce 2 move merge issues

---

.jq

- Include Chokidar in Local filter
- Introduce nouptodate & noproxy filters
- Document path filter caveat
- Find logs before/after some given time

jq: Improve filters [ci skip]

---

core/metadata.js

- Initialize the id in buildFile (like for buildDir)
- Make assignId call id, and not opposite

Refactor metadata.js

---

core/local/analysis.js
core/local/change.js
test/unit/local/analysis.js

core/local: Fix add+unlink (temporary file)

---

.appveyor.yml

Try to make appveyor builds faster

---

core/merge.js
test/unit/helpers_merge.js

core/merge: avoid conflict-of-conflict files

---

core/globals.js
dev/remote/generate-test-env.js
package.json
yarn.lock

- upgrade cozy-client-js
- upgrade chokidar
- upgrade chokidar-cli

tech: Upgrade yarn dependencies

---

core/local/atom_watcher.js
core/local/chokidar_watcher.js
core/local/index.js
core/local/sync_dir.js
core/local/watcher.js

What could still be improved:
- SyncDir existence check should not be sync
- Missing unit tests
But those issues were already present in the original code.

core/local: SyncDir helpers

---

CHANGELOG.md
package.json

- Files moved right after they've been added to the Cozy folder and before we've
had the chance to upload them will be synchronized anyway, at the right path.

Release v3.10.3-beta.2

---

core/merge.js
core/metadata.js
core/prep.js
core/remote/change.js
core/remote/watcher.js
test/integration/move.js
test/unit/remote/watcher.js

This PR is a split from #1250 which was getting unreadable.
It needs to include @sebn review from there.

Manage descendant moves

---

core/merge.js
core/metadata.js
core/sync.js
test/scenarios/move_dir_and_update_subfile_remotely/scenario.js

This is PR is split from #1250 which was unreadable.

Fix scenario move_dir_and_update_subfile_remotely

---

core/merge.js
test/integration/update.js
test/support/builders/metadata/base.js
test/unit/merge.js

core/merge: Fix local offline update after unsynced update

---

CHANGELOG.md
package.json

- When the app was stopped in the middle of a synchronization, with folder moves
coming from the remote Cozy, we could end up detecting conflicts on those
folders undefinitely after restarting it. We now handle unapplied moves upon
startup and avoid creating unnecessary `-conflicts-` folders.
- If a file existing both locally and in the remote Cozy was updated more than
once without synchronization, the latest changes would create a conflict and
its resolution would override the file with an older version leading to data
loss. We now simply override the local version of the file with the latest
changes and synchronize them with the remote Cozy.

Release v3.10.4-beta.1

---

gui/main.js

Fix disk-quota for Cozy instances with no quota

---

CHANGELOG.md
package.json

- When the app was stopped in the middle of a synchronization, with folder moves
coming from the remote Cozy, we could end up detecting conflicts on those
folders undefinitely after restarting it. We now handle unapplied moves upon
startup and avoid creating unnecessary `-conflicts-` folders.
- If a file existing both locally and in the remote Cozy was updated more than
once without synchronization, the latest changes would create a conflict and
its resolution would override the file with an older version leading to data
loss. We now simply override the local version of the file with the latest
changes and synchronize them with the remote Cozy.

Release v3.10.4

---

core/config.js

- on our current node version (electron 1.8.3 - node 8.2.1), fs.constants.COPYFILE_FICLONE is not available
- fs-extra.copySync takes a third argument that can be an options object or a callback, but not flags
- on node 8.5.0 and later, we can use a copy-on-write reflink via fs.copyFileSync with flags.

Fix config copy

---

CHANGELOG.md
package.json

- We will now alert you when a new version of the app is available and give you
the option of restarting it to download and apply the new version or postpone
it.
- To avoid losing your data, we're very careful when it comes to conflicts and
we prefer to leave it to you to choose between the two versions we detected.
However, when it comes to changes that haven't been synchronized yet, we can
avoid creating a conflict and pick the latest version for you.
From now on, we won't create a `-conflict-` version of a folder that has been
changed locally and never synchronized remotely with your Cozy.
- If a file was changed remotely and its parent folder moved or renamed, we
could end up moving the file locally but not synchronize its new content.
We're now …

Release v3.11.0-beta.1

---

test/unit/merge.js

Pros:
- A test should not break because of another one
- No crazy filenames to prevent PouchDB conflicts

test/unit/merge: Independent tests

---

core/local/index.js
core/remote/index.js
core/sync.js
test/unit/local/index.js
test/unit/remote/index.js
test/unit/sync.js

core/sync: Prevent conflict when file moved+changed twice locally

---

CHANGELOG.md
package.json

- Editing the content of a file just moved with one of its ancestor could lead
to the incorrect detection of a conflict with its remote couterpart. We're now
updating its content as expected and thus avoiding creating any `-conflicts-`
file.

Release v3.11.1-beta.2

---

.appveyor.yml

We need to build the assets before building the electron app.

appveyor: Build CSS and Elm in both jobs

---

test/unit/local/index.js
test/unit/merge.js
test/unit/metadata.js
test/unit/prep.js
test/unit/remote/index.js

test/unit: Resurrect some disabled tests

---

core/local/atom_watcher.js
core/local/steps/await_write_finish.js
core/local/steps/win_detect_move.js

Detect files/dirs moved on windows

---

test/unit/local/steps/add_infos.js

KISS tests for `add_infos.js`.
File                      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------|----------|----------|----------|----------|----------------|
core/local/steps/add_infos.js            |    90.91 |       75 |      100 |    90.91 |          39,40 |
Here are lines 39,40:
log.info({err, event}, 'Cannot get infos')
console.log('stats', err) // TODO error handling

test: Cover add_info.js

---

core/prep.js
core/sync.js

core: Import complete metadata module in sync & prep

---

core/local/steps/add_checksum.js
core/local/steps/add_infos.js
core/local/steps/await_write_finish.js
core/local/steps/initial_diff.js
core/local/steps/scan_folder.js
core/local/steps/win_detect_move.js

Handle errors in addInfos

---

CHANGELOG.md
package.json

- We've improved the way we handle the revision of newly detected documents that
are created at paths that have already been synchronised in the past. This was
a potential source of conflicts were you to modify the content of such file.
- We're testing a new implementation of our local changes watcher on Windows and
Linux. This should bring performance gains, faster change detection and in
fine better stability.
Some bugs can be present and not all existing features are implemented yet
though.
It is acitvated by default in this early build for testing purposes only and
should not be used in other situations.

Release v3.12.0-alpha.1

---

core/local/steps/filter_ignored.js

Do not ignore the initial-scan-done in filterIgnored

---

CHANGELOG.md
package.json

- We fixed the issue preventing the new watcher from working past the initial
synchronisation folder scan.

Release v3.12.0-alpha.2

---

test/unit/local/steps/scan_folder.js

test: Cover scan_folder in some condition

---

doc/developer/test.md
gui/main.js
test/generate_property_json.js
test/mass_property_tests.sh
test/property/device.js
test/property/local_watcher/advanced_moves.json
test/property/local_watcher/basics.json
test/property/local_watcher/bedfordshire.json
test/property/local_watcher/checking_account.json
test/property/local_watcher/cotton.json
test/property/local_watcher/cycle_rename.json
test/property/local_watcher/cycle_rename_alt.json
test/property/local_watcher/deletions.json
test/property/local_watcher/fresh_thinking.json
test/property/local_watcher/index.js
test/property/local_watcher/keyboard_rubber.json
test/property/local_watcher/references.json
test/property/local_watcher/simple_moves.json
test/property/local_watcher/small_wooden_gloves.json
test/property/local_watcher/swedish_krona.json
test/property/local_watcher/tan_payment.json
test/property/local_watcher/underscore_prefix.json
test/property/local_watcher/unleashed_full_range.json
test/property/local_watcher/zimbabwe.json
test/property/runner.js
test/property/stack.js
test/property/two_clients/efficient_invoice.json
test/property/two_clients/index.js
test/property/two_clients/short_example.json

Add some property based tests with 2 cozy-desktop clients

---

core/local/analysis.js

One more step to make analysis easier to understand/refactor.
Please see individual commits.

core/local/analysis: LocalChangeMap & refactoring

---

CHANGELOG.md
package.json

- The count of objects to be synchronised was always 1 with the new local
watcher.
We've fixed this so the count is accurate and decreases with each element
successfully synchronised.
- In some situations, the detection of local changes could be stalling.
We've adapted the watcher so it detects when it can start processing
filesystem events.
Improvements for contributors:
- The developer documentation's [design section](https://github.com/cozy-labs/cozy-desktop/blob/master/doc/developer/design.md#local-watcher) has been updated with the reasons
that led to the decision to create a new local watcher and diagrams explaining
how it works on Windows and Linux.

Release v3.12.0-alpha.3

---

core/local/analysis.js
core/local/change.js
core/local/chokidar_watcher.js
test/scenarios/move_dir_and_update_subfile/local/linux.json
test/scenarios/move_dir_and_update_subfile/local/win32.json
test/scenarios/move_dir_and_update_subfile/scenario.js
test/unit/local/analysis.js

core/local: Fix dir move + subfile update

---

test/unit/local/steps/await_write_finish.js

After running all those tests, we cover
File                      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------|----------|----------|----------|----------|----------------|
NO TEST await_write_finish.js   |     9.26 |        0 |        0 |     9.43 |... 114,115,116 |
await_write_finish.js   |    98.15 |    96.43 |    85.71 |    98.11 |            115 |
Line 115:
```
.catch(err => log.error({err}))
```

test: Cover await_write_finish that debounces events

---

CHANGELOG.md
package.json

Needs https://github.com/cozy-labs/cozy-desktop/pull/1417

Release 3.12.0 beta.1

---

CHANGELOG.md
package.json

- We've improved the way we handle the revision of newly detected documents that
are created at paths that have already been synchronised in the past. This was
a potential source of conflicts were you to modify the content of such file.
- When moving a folder locally then quickly changing the content of a subfile
on the same device, the file content may not be updated in the Cozy in some
cases. Everything should now work as expected.
- We keep track of the changes made to documents to synchronise either with the
remote Cozy or the local filesystem using version numbers for each side of the
synchronisation. When moving a document, be it either a directory or a file,
on the local filesystem as part of its parent directory move, the new local
version number would …

Release v3.12.0

---

test/integration/conflict_resolution.js

Extracted from https://github.com/cozy-labs/cozy-desktop/pull/1334.
Needs https://github.com/cozy-labs/cozy-desktop/pull/1414.
Merging local dir move then remote dir addition to the same
destination doesn't trigger a conflict although it should.
This will be fixed later.

test/integration: Test more conflict resolution cases

---

core/merge.js
test/integration/conflict_resolution.js

Extracted from https://github.com/cozy-labs/cozy-desktop/pull/1334.
Needs https://github.com/cozy-labs/cozy-desktop/pull/1415

core/merge: Resolve conflict between local move & remote addition

---

test/scenarios/run.js

Extract functions to make runner easier to understand.

test/scenarios/run: Refactoring

---

core/local/steps/dispatch.js

core/local/steps/dispatch: Inject options

---

core/local/atom_watcher.js
core/local/steps/add_checksum.js
core/local/steps/add_infos.js
core/local/steps/await_write_finish.js
core/local/steps/buffer.js
core/local/steps/dispatch.js
core/local/steps/filter_ignored.js
core/local/steps/incomplete_fixer.js
core/local/steps/initial_diff.js
core/local/steps/producer.js
core/local/steps/scan_folder.js
core/local/steps/win_detect_move.js
core/local/watcher.js
test/unit/local/steps/add_checksum.js
test/unit/local/steps/add_infos.js
test/unit/local/steps/await_write_finish.js
test/unit/local/steps/dispatch.js
test/unit/local/steps/filter_ignored.js
test/unit/local/steps/initial_diff.js
test/unit/local/steps/scan_folder.js

Separate a few things & make it easier to customize behavior (e.g. dispatch in tests).
See individual commit messages.

core/local: Refactor AtomWatcher & steps

---

test/integration/conflict_resolution.js
test/integration/corruption_fixer.js
test/integration/full_loop.js
test/integration/move.js
test/integration/mtime-update.js
test/integration/platform_incompatibilities.js
test/integration/trash.js
test/integration/update.js
test/scenarios/run.js
test/support/helpers/index.js
test/support/helpers/local.js
test/support/helpers/remote.js

Needs https://github.com/cozy-labs/cozy-desktop/pull/1458

test/support/helpers: Refactor

---

core/local/atom_watcher.js
core/local/index.js
core/local/steps/dispatch.js
core/local/watcher.js

core/local: AtomEventsDispatcher injection

---

gui/main.js

In d751ab71, config was renamed to fileConfig.

gui: Fix GUI boot

---

gui/js/window_manager.js

See https://github.com/cozy-labs/cozy-desktop/issues/1055

gui: Try a work-around for the icon on Ubuntu

---

test/integration/conflict_resolution.js

test/integration/conflict_resolution: Make use of fullSyncStartingFrom()

---

core/local/steps/incomplete_fixer.js

To make upcoming fixes easier.

core/local/steps/incomplete_fixer: Refactor

---

test/integration/mtime-update.js

test/integration/mtime-update: AtomWatcher support

---

core/local/steps/incomplete_fixer.js
test/unit/local/steps/incomplete_fixer.js

core/local/steps/incomplete_fixer: Handle combined events

---

dev/remote/automated_registration.js
dev/remote/generate-test-env.js

Same as in CI with sane defaults when no env var is set.
Useful when docker is broken.
---

dev: Local `yarn bootstrap:remote` support

---

package.json
yarn.lock

So at least we get security updates.
---

chore(deps): Upgrade to electron 2.0

---

test/unit/local/steps/producer.js

So unit tests stop failing randomly.

test/unit/local/steps/producer: Handle some random cases

---

core/local/steps/initial_diff.js
core/local/steps/win_detect_move.js

core/local/steps: More logs

---

core/local/steps/dispatch.js
core/local/steps/win_detect_move.js

core/local/steps: Dispatch related improvements

---

CHANGELOG.md
package.json

- The new local watcher is now the default watcher. It should bring better
performance in local changes analysis.
- We found a bug in the synchronisation process of directories that could lead
to missed updates. We have not seen any reports of it but the mechanism has
been fixed anyway.
- We updated one of our main dependencies, Electron, to its 2.x version. We are
still not using the latest version but this one brings us back support from
the Electron team and security fixes. Other updates will come in the following
releases.
- Files and folders named like a volume (e.g. C:) and at the root of the folder
watched by Cozy Desktop could lead to an infinite loop if they or any of their
children were ever modified. …

Release v3.13.0-beta.1

---

core/sync.js
test/unit/sync.js

If changes are merged during Sync, we'll get an update conflict when
we try to mark the synced doc as up-to-date.
In this situation the extra changes were not synced because we would
not keep the sides difference.
We found this bug because the new watcher would not acquire a db
lock around Merge in dispatch step.
We added the lock in a previous commit but modifying the way we
acquire locks in Sync could lead to the updateRevs bug again if we
were not to fix it as well.

core/sync: Fix #updateRevs() conflict handling

---

.jq

jq: Add noscan filter [ci skip]

---

core/sync.js
test/unit/sync.js

Retrying won't fix anything in those cases.
It would only make sync slower.
---

 core/sync: Skip without retry on 412 error

---

CHANGELOG.md
package.json

- We now detect and correctly synchronise file moves where the destination
already existed and is being overwritten.
However since filesystems and file browsers are all different, you might
have a different experience on Linux. We made sure this works with the
GNOME file browser, Nautilus.
- We improved the way we aggregate quick modifications to files to avoid
having to synchronise a lot of changes when we only care about the result
of the last one.

Release v3.13.0-beta.5

---

CHANGELOG.md
package.json

- We fixed the last known issue regarding files and directories renamed while
the client is stopped using the new watcher. The next release should be a
stable one! 🚀
Happy syncing!

release: 3.13.0-beta.8

---

dev/remote/automated_registration.js
package.json
yarn.lock

- Use request-promise instead of request
- Use async/await syntax
- Extract various functions
- Improve error messages to make debugging easier
- Increase default timeout to prevent AppVeyor failures
---

dev/remote/automated_registration: Refactor & fix URLs

---

CHANGELOG.md
package.json

Improvements for contributors:
- We've decided to run prettier over our entire codebase with the cozy-app
eslint config and to keep using it from now on. This will remove the need to
check for syntax errors and improve homogeneity between Cozy Cloud javascript
projects.
- We've updated some of our dependencies. There shouldn't be any consequence but
it's just good hygiene and could potentially fix issues we don't even know.

Release v3.13.1-alpha.1

---

test/unit/local/steps/initial_diff.js

- Extract `.inputBatch()` method to make sure we clone every batch
added to the buffer without repeating ourselves
- Fix expectations for some tests failing after cloning the input
batch
- Make sure every event is named after its path and action

test/unit/local/steps/initial_diff: Refactoring

---

core/local/steps/initial_diff.js
test/unit/local/steps/initial_diff.js

When we don't receive any events for an existing document during the
initial scan, we assume it has been deleted and issue a `deleted`
event for it.
However, if its parent has been moved or renamed, its path won't be
correct anymore and we won't be able to merge it.
To issue a correct event, we fix its path attribute based on its
parents movements.
Based on #1562

core/local/steps/initial_diff: Fix path of issued deleted events

---

.vscode/settings.json

vscode: Format elm/js on save [ci skip]

---

gui/elm/Data/Window.elm
gui/elm/Icons.elm
gui/elm/Locale.elm
gui/elm/Main.elm
gui/elm/Ports.elm
gui/elm/Window/Help.elm
gui/elm/Window/Onboarding.elm
gui/elm/Window/Onboarding/Address.elm
gui/elm/Window/Onboarding/Folder.elm
gui/elm/Window/Onboarding/Welcome.elm
gui/elm/Window/Tray/Dashboard.elm
gui/elm/Window/Tray/Settings.elm
gui/elm/Window/Tray/StatusBar.elm
gui/elm/Window/Updater.elm

- Improves readability
- Makes diffs smaller
- Will be kept by elm-format when more than 1 item is exposed
---

gui/elm: Wrap big module statements

---

package.json
test/support/hooks/index.js
test/support/hooks/logging.js

See comments in code for the rationale.
---

test/support: Introduce ./hooks

---

.github/PULL_REQUEST_TEMPLATE.md

Either via a manual test or the addition of a scenario testing the new
behaviour or some behaviour that was not documented already.

github: Emphasize on testing new code

---

gui/js/proxy.js

gui/js/proxy: Reduce logging

---

test/integration/move.js

Instead of trying to recreate (uncorrectly) the steps of a move like
they were done before moves were supported in the Desktop app, we
should use the remote move method so this gets applied correctly.

test/integration/move: Use remote move method

---

core/sentry.js

- No more global logger customization on module import
- Honor `DEBUG`, `TESTDEBUG` & `COZY_NO_SENTRY` environment
variables in `.setup()`
- Make sure `.setup()` is not called twice
Teamwork with @taratatach :heart:
---

core/sentry: Improved (non-global) setup

---

gui/js/updater.window.js

- Extract #skipUpdate() from #checkForUpdate() so we can reuse it on
error, not only on timeout.
- Ignore error after skipped/timeout
- Retry on error after 1s
- Skip on ENOENT error (dev-app-update.yml)
- Remove stuff already logged by autoUpdater.logger
- Make skipping reason clearer
---

gui/js/updater: Improve error handling

---

CHANGELOG.md
package.json

- We improved error handling in our auto-update component. Hopefully this
should make it easier for people with flaky connections to get the latest
version of the app.
Happy syncing!

release: 3.13.2-beta.3

---

core/local/atom/add_checksum.js

It can be hard to know when reading logs if a checksum was actually
computed or not since we log before testing for the existence of a
checksum on the given event.
This would help figure out when we compute checksums when we don't
want to (i.e. we see computed checksums logs while no changes were
made on the file).
This should also reduce the size of the log files.

core/local/atom/add_checksum: Log only computed checksums

---

test/unit/local/atom/producer.js

test/unit/local/atom/producer: Refactor tests

---

test/unit/remote/cozy.js

test/unit/remote/cozy: Don't break on #cozyMetadata

---

CHANGELOG.md
package.json

- When a file or directory is moved or renamed from an ignored path to a
non-ignored one, it is now handled as a creation.
- When a file or directory is moved or renamed from a non-ignored path to an
ignored one, it is now handled as a deletion.
Happy syncing!

release: 3.13.3-beta.1

---

CHANGELOG.md
package.json

Improvements for Windows & macOS users:
- The application code signing certificate was updated.
Happy syncing!

release: 3.13.3-beta.2

---

CHANGELOG.md
package.json

Improvements for Windows & macOS users:
- The application code signing certificate was updated.
- When a file or directory is moved or renamed from an ignored path to a
non-ignored one, it is now handled as a creation.
- When a file or directory is moved or renamed from a non-ignored path to an
ignored one, it is now handled as a deletion.
Happy syncing!

release: 3.13.3

---

core/local/atom/filter_ignored.js

For each event coming through the channel, we compute a potential
event to keep the original event and the Ignore rules and push it
back to the channel or log the original, ignored, event.

core/local/atom/filter_ignored: Compute event to keep

---

CHANGELOG.md
package.json

- We fixed an issue where copies of conflicting files would not be created at
the right path.
- We improved our test harness regarding the initial scan of the local synced
directory. Those new tests already allowed us to identify and fix an issue
(see next point).
- When moving a directory then updating a descendant file while the app was
stopped, the file change would not be synced. This now works as expected.
This used to work but was broken at some point. The new tests should prevent
this to happen again.
- Although some files and directories were correctly ignored during initial
scan, this was not done immediately, resulting in more work for the app.
They are now ignored as soon as possible. This should also …

release: 3.13.4-beta.1

---

.travis.yml

So we also cover chokidar initial scan.
---

travis: macOS stopped client scenarios

---

KNOWN_ISSUES.md

- Removed dead links
- Removed solved issues
- Added synchronisation issues with documents starting with an
underscore or starting or ending with a space

Update Known Issues documentation

---

docker-compose.yml

docker: Upgrade cozy-app-dev from 1.2.2 to 1.2.8

---

core/config.js
core/index.js
core/local/atom/watcher.js
core/local/chokidar/analysis.js
core/local/chokidar/event.js
core/local/chokidar/local_event.js
core/local/chokidar/watcher.js
core/local/index.js
core/local/watcher.js
core/remote/index.js

To better introduce the 2 implementations & their workflow.

doc: Improve the local watcher(s) documentation

---

doc/developer/api_doc.md

doc: API doc build & publication [ci skip]

---

test/integration/mtime-update.js

In case the file's last modified date only is changed on the local
filesystem, we should not save the new value in Pouch to avoid
synchronising it with other filesystems which might not have the same
precision for the value.
However, if the change occurs on the Cozy, the remote document's
revision has been changed and we should expect to save that new
document's version in Pouch.

test/integration/mtime-update: Save update from Remote

---

.travis.yml

Use GOPROXY for faster travis build

---

dev/remote/automated_registration.js

Hash the password for cozy-stack

---

package.json
yarn.lock

Upgrade to latest version v7.1.1.

deps: Upgrade pouchdb

---

gui/js/tray.js

Starting with Electron 3 (still true with Electron 4 and potentially
with Electron 5 as well), whenever libappindicator-gtk3 is installed
on the client's computer, clicks on the systray icon won't trigger
click events.
We use those events to display the app's window and have currently no
other ways to display it on GNOME systems.
To make sure all users will have at least one way to display the app's
window, we add the complete context menu (i.e. not only the
« Quit Application » menu item on right click but also the
« Show Application » menu item, both on left click) on all Linux
systems.
If the libappindicator-gtk3 package is not installed (i.e. it is a
dependency of the Chrome Web browser), the left click will still
display the app's window.
On a side note, it was our intention to …

gui/tray: Add complete context menu on all Linux

---

package.json
yarn.lock

deps: Bump electron-updater

---

.travis.yml
electron-builder.yml
package.json
yarn.lock

Removes deprecated AppImage option.

deps: Bump electron-builder

---

package.json
yarn.lock

deps: Bump bunyan

---

.travis.yml

ci/travis: Log cozy-stack errors to console

---

package.json
yarn.lock

- dtrace-provider
- electron-mocha
- chokidar

deps: Bump small deps

---

.jq
core/pouch/index.js
core/remote/change.js
core/remote/watcher.js
test/support/builders/index.js
test/support/builders/metadata/base.js
test/support/builders/remote/base.js
test/unit/remote/change.js
test/unit/remote/watcher.js

Should make those scenarios pass all the time:
- `test/scenarios/move_file_inside_move/remote`
- `test/scenarios/move_from_inside_move/remote`

Remote changes misc

---

core/local/chokidar/analysis.js
core/local/chokidar/local_change.js
core/local/chokidar/watcher.js
gui/elm/Window/Tray/Dashboard.elm
gui/js/onboarding.window.js
gui/js/window_manager.js
gui/main.js
gui/styles/_two_panes.styl
package.json
test/scenarios/case_and_encoding/identical_additions/dir_file/win_mac/scenario.js
test/scenarios/run.js
test/unit/gui/proxy.js
test/unit/local/chokidar/analysis.js
yarn.lock

deps: Upgrade Electron to v5.0.0

---

CHANGELOG.md
package.json

- We fixed a technical error with one of our dependencies which prevented the
app from starting.

Release v3.16.0-beta.2

---

CHANGELOG.md
package.json

- After fixing the remote changes identification logic, we found out
that our sorting algorithm (necessary to avoid potential collisions
when applying them locally) was not stable and the resulting order
depended greatly on the original changes and their order.
We separated the criterias on which we sort the changes to come up
with 2 sorting algorithms called on after the other so the result of
each one is predictable and thus the end result too. This should
prevent some conflicts and mis-applied changes.

Release v3.16.0-beta.5

---

CHANGELOG.md
package.json

- We upgraded a lot of dependencies and especially Electron which was
upgraded to v5.0.0. This brings in Node v12.0.0. They should bring
performance and stability improvements.
- We improved the stability of the ordering and identification of
changes fetched from the remote Cozy. This should reduce the number
of unmergeable changes and conflicts arising from those situations.
This is especially true when complex moves were synchronised with
the remote Cozy (e.g. moving a folder from inside a moved folder).
- We fixed a few minor UI issues like long filenames which were not
correctly ellipsized in the synced files list.
- When upgrading Electron to v5.0.0, we broke the onboarding process
because of a new security restriction in Chromium (which is packaged
with …

Release v3.16.0

---

gui/main.js

With the Atom Watcher, changes are handled one at a time and this can
lead to status "blinking" in the systray and the app's status bar
between the synchronization state and other states like up-to-date or
change preparation (i.e. the change is being processed by the watcher
or being merged).
This can be off-putting for users who are not aware of this
behind-the-scene mechanism and might be feeling the application is
acting erraticaly.
By simply debouncing status updates display in either in the systray
or the status bar when this is not a long-term status (i.e. offline,
error, syncing, online after offline), we can give a sense of
continuity and that the process is going smoothly.

gui: Debounce sync status updates display

---

CHANGELOG.md
package.json

- With version 3.16.1 of the app, we decided to increase the visibility of the
synchronization activity especially during the upload of large files or the
preparation of local changes. This made the application's status and icon
"blink" for some users and would give a bad feeling about its behavior.
We made some more changes to the status display so you should now see no
blinking and better delimited activity phases that should better reflect the
ongoing synchronization.

Release v3.16.2-beta.2

---

gui/main.js

To avoid spamming the user with the same error notification each time
they open the main app window, we keep track of the last notified
message and only send a system notification if the error message is
new.

gui/main: Send only one notification per error

---

CHANGELOG.md
package.json

- We've completely changed our sorting algorithm for changes coming
from the Cozy. We may not receive changes in the order they were
made and this can make their application on the local file system
impossible. To mitigate this situation we sort the changes to make
their application possible. It is a difficult task and we've made a
lot of changes in the past to try and fix bugs in different
situations.
We've yet again seen new problematic situations recently and decided
to try a new approach with a completely new algorithm, focusing more
on essential changes that need to happen first rather than trying to
recreate the very specific order in which changes were made.
- We've noticed that when requesting a manual synchronization, the
button is not disabled right …

Release v3.18.0-beta.1

---

gui/main.js

New users or users who disconnect their client don't have an App
config. This prevents us from running the `App.setup()` method since it
will raise an error for invalid configs (like an empty one).
The config is built during the Onboarding process so we need to
postpone the setup of the App after the user has gone through that
process.
This means notes can't be opened if the client has not been connected
before.

gui/main: Setup App only when we have a config

---

CHANGELOG.md
package.json

- A regression was introduced in version 3.18.0 which leads to errors
when moving files after they've been updated. From what we've seen
the modifications are not lost and the file ends up at the expected
location but this could be the base for issues further down the
road.
We've made sure that the regression was fixed and added a data
migration to do some cleanup in your local databases.
- The first beta version of v3.19.0 changed the order in which we
initialize the different parts of the application to be able to
lookup notes and open them without starting the file synchronization
process. This change unexpectedly prevented users to go through the
on-boarding process and the end to start the application if the
client was not already connected to their Cozy. …

Release v3.19.0-beta.2

---

core/sync.js

Errors raised from the sync process, the local watcher or the remote
watcher reject the `started` and `running` Promises that we use to
detect them from the main process.
However, the `Sync.stop()` method awaits them to make sure we don't
stop the process before all its modules have been initialized (to
avoid running them more than once in case we're restarting the sync
process).
This means that if those Promises are rejected, the `stop` method
itself will raise an error and the sync process won't be stopped.
This is an issue when we try to run some actions after stopping the
sync process (e.g. disconnecting the client after the OAuth client has
been revoked) since errors during the `stop` call will prevent further
actions to be run via calls to `then.
Please make sure the following boxes …

core/sync: Catch sync errors when requesting stop

---

core/local/index.js
test/unit/local/index.js

When trying to put a remote document to the Cozy trash, if it's
missing, we skip the error since there's nothing we can do about it.
We should do the same when trying to trash a local file.
There's a slight difference when trashing a folder since we can get
the `ENOENT` system error (i.e. missing document) if the document at
the given path is a file instead of a folder.

core/local: No errors on missing trashed file/dir

---

test/unit/sync.js

The vocabulary used in the Sync module and the associated methods have
changed and we're now calling `Sync.applyDoc()` instead of
`Sync.fileChanged()` or `Sync.folderChanged()`.

test/unit/sync: Cleanup old tests

---

CHANGELOG.md
package.json

- This release fixes a small typo that prevented the overwriting moves
to function properly.

Release v3.20.0-beta.3

---

CHANGELOG.md
package.json

- Following some feedback on the app updater window which could give
the feeling that the update was not going to complete, we've made a
small redesign of this window, replacing the indeterminate progress
bar with a spinner and adding emphasizing the text asking you to be
patient until the download is complete.

Release v3.20.0-beta.4

---

CHANGELOG.md
package.json

Nothing to see here. This release let's us test the previous redesign of the updater window.

Release v3.20.0-beta.5

---

doc/usage/linux.md

doc/linux: Update supported distributions

---

core/remote/watcher/index.js
test/unit/remote/watcher.js

We decided to block the synchronization when the client could not merge
a change because its parent folder could not be found in PouchDB (i.e.
`MergeMissingParentMetadataError`).
However, some of those situations can resolve themselves by skipping
those changes and trying again later, after the other side changes
have been propagated (non exhaustive list):
- a folder was renamed locally while some content was added in it on
the remote Cozy (the content ends up in the renamed folder)
- a folder was deleted locally while some content was added in it on
the remote Cozy (the folder and all its content are trashed)
The decision to block the synchronization was made at a time when we
didn't have great confidence in the client and we preferred to have
users contact us whenever they encountered …

core/remote/watcher: Missing parents don't block

---

.jq

Cozy Notes content and schema are stored in the record's metadata and
are displayed when parsing the logs.
This data can be quite long and is irrelevant to what the Desktop
client does so we can remove them when using the `clean` filter to
make for a more compact output.

jq: Add filter to remove Notes metadata

---

.jq

jq: `clean` drops Note content from overwrite attr

---

core/remote/index.js

In case of an overwriting move (i.e. there is an existing document at
the move target location that we will overwrite), we want to preserve
the overwritten document's references.
This is useful to preserve a modified photo's album for example.
In this situation, the `Remote.moveAsync()` method will perform 4
actions:
1. fetch the overwritten document's references
2. add those references to the overwriting document
3. trash the overwritten document
4. move the overwriting document to the target location
If performed in this order, step 2. will generate a CouchDB change
with the overwriting document's previous location. This change will
then be picked up by the remote watcher. Since we have already saved
the document's new location in our local PouchDB record, the remote
watcher will …

core/remote: Move doc before migrating references

---

core/remote/watcher/index.js
test/unit/remote/watcher.js

We've stopped blocking the synchronization process when encountering
only `MergeMissingParentError`s in a single remote watcher changes
batch in f5c05d5c32a0b439d9456825ef64b8ddb41d9c91.
However, this commit did not change the way we manage the remote
sequence when encountering those errors. This means that even though
the synchronization does not stop, we do not mark the merged changes
as processed and we will fetch them and merge them again at the next
remote watcher poll.
In some cases, we can see missing parent errors that will never get
resolved and we'll keep fetching and merging the same changes again
and again. Besides the inefficiency of doing the same work every
minute, we could mess up the local PouchDB records by merging a change
more than once, especially if the document has …

core/remote/watcher: Skip sequences missing parent

---

gui/js/onboarding.window.js

While the OAuth flow works fine when trying to connect a Cozy Cloud
run instance, we were facing issues during the OAuth flow when
connecting to an instance via Toutatice, the SSO portal of Académie de
Rennes.
After investigation, it turns out they use jQuery on their portal to
set some form values that are required to complete the OAuth flow.
However, we use the Node integration in Electron to be able to require
Node modules and make calls to our core functions and this prevents
jQuery from loading when included in the loaded webpage via a script
tag.
Since we can't remove the Node integration for now, we decided to run
the OAuth flow in a dedicated `BrowserView` which won't have the Node
integration.
This gives us two advantages:
- webpages loaded as part of the OAuth flow can make use …

gui/onboarding: Run OAuth flow in BrowserView

---

CHANGELOG.md
package.json

- Until now the connection to your Cozy would always go through our
own infrastructure only. We're adding the possibility for partners
to offer their users to connect via their own SSO portal so we now
run the connection flow in a dedicated sandbox.
This has two advantages when an SSO portal is involved:
1. the portal code is run in a browser like environment with no
alterations so it should work out of the box
2. the portal code is isolated from the rest of our application
adding another layer of security preventing malicious code on the
portal itself to access your computer

Release v3.21.0-beta.7

---

core/remote/watcher/index.js

The remote watcher seems to be hanging without explanations at least
on macOS.
We don't know where to start the investigation but we can at least at
a few more log calls when starting/stopping the watcher and when we
successfully fetch the remote changesfeed but there are no changes to
process.

core/remote: Log when starting, stopping, watching

---

CHANGELOG.md
package.json

- We added a migration to force a refetch of all remote Cozy Notes in order to
avoid as many dispensable conflicts as we can during the first reboot after
this release installation.

Release v3.21.0-beta.8

---

CHANGELOG.md
package.json

- We made sure a Cozy Note is still identified as such after saving
changes like an update on the remote Cozy. This will ensure they
will stay protected from local updates afterwards.
- We made sure the application of the move and update of a file on the
local filesystem does not trigger invalid changes that would be
propagated to the remote Cozy.

Release v3.21.0-beta.9

---

core/merge.js
test/unit/merge.js

We'll stop merging local file updates if the local metadata stored in
PouchDB represent the same file as the metadata of the update.
When applying remote file changes to the local filesystem, the local
watcher picks up events that can lead to a local update request with
outdated metadata (i.e. the previous version of the metadata).
To avoid merging those fake updates and propagate inaccurate changes
to the remote Cozy, we'll use the newly introduced `local` metadata to
check whether the update is a true one or it corresponds to the
previous version of the file being synchronized.
This should prevent the creation of conflicts when propagating the
combined renaming and update of a Cozy Note to the local filesystem.

core/merge: Discard same-local-state files changes

---

CHANGELOG.md
package.json

- We introduced a new way to store and compare local file states. This
is the first step to solve different problems. We're solving a first
issue by preventing fake metadata (i.e. size and content checksum)
from being propagated to the remote Cozy when a Cozy Note is both
renamed and modified during a very short period.

Release v3.21.0-beta.10

---

core/local/atom/incomplete_fixer.js
test/unit/local/atom/incomplete_fixer.js

Some software take a lot of precautions when saving modifications made
on a file to avoid any data loss.
One such software moves the current file to a backup location and
writes the new version in its stead.
In this situation, on Windows, the Atom watcher receives and processes
the following events:
1. `renamed` (`file` → `file.backup`)
2. `created` (`file`)
3. `deleted` (`file.backup`)
If the backup file deletion was done before the watcher could compute
its checksum, the `renamed` event will be marked as incomplete. It
will then be completed in the `incompleteFixer` step by the `deleted`
event, transforming the `renamed` event into a `deleted` event of the
original file location (i.e. the same as the created file location
since we're replacing it).
This would be alright if the `created` …

local/atom/incomplete_fixer: File update via backup

---

gui/js/lastfiles.js
gui/main.js

The Recent files list in the main window displays files that were
synchronized recently (i.e. the last 250 files that were added or
moved and not subsequently removed).
We persist the objects used to display those element in a JSON file in
the config folder.
This list was not always correctly displayed during the client
start, especially on Windows where it never worked.
The list was correctly loaded from the JSON file but the messages with
the information needed to display the recent files were sent before
the main window was fully loaded and the Elm application ready to
receive them.
Also, if the JSON parsing was taking too long, we could try to send
the list to the window before it was loaded.
We introduced 2 changes to fix the situation:
- the `init` function responsible for loading …

gui: Fix recent files display during client start

---

CHANGELOG.md
package.json

- The list of recently synchronized files could be persisted multiple
times concurrently, leading to malformed JSON content which could
not be loaded back into the client's GUI during the next start.
We're now making sure each write is done sequentially so that the
list is always saved as valid JSON.

Release v3.22.0-beta.4

---

CHANGELOG.md
package.json

- As a multi-device platform, Cozy Cloud tries to keep the
modification dates of documents in sync across all your devices
(i.e. Drive Web, Drive Mobile, Cozy Desktop, other people's
Cozies…). When modifications happen on the Cozy itself, the
modification date is set by the server. On the other hand, when the
modification is made on on your computer, we get the date from your
filesystem. We were using the most recent date between the content
modification date and the metadata modification date but we think
the content modification date is the most important and that it
should not be affected by movements, renamings, permission
changes, etc.
For this reason, from now on we will only use the content
modification date on Cozy Desktop.
- Files with remote creation …

Release v3.22.0

---

package.json
yarn.lock

deps: Bump Electron to v8.5.0

---

.appveyor.yml
.travis.yml
dev/ci/dist.sh
gui/js/tray.window.js
package.json
yarn.lock

deps: Bump Electron to v9.2.0

---

yarn.lock

This version brings CVE fixes.

deps: Bump electron to v9.2.1

---

CHANGELOG.md
package.json

- We upgraded the framework upon which our application is built,
Electron, to v9.2.1 which is the 2nd latest major version (v10.0.0
was released 4 days ago). This should bring more stability to the
application overall and prevent some crashes. We can also expect
smaller bundles. This upgrade brings us official support back for a
while.
- Data migrations run after some client upgrades should not prevent
not fully synchronized changes from being detected and synchronized
after the migration.
- Documents added on your remote Cozy, detected by the client but not
fully synchronized before it is stopped should be synchronized
correctly after the next client launch. The client should not try to
delete them on your Cozy because it does not find them locally (the …

Release v3.23.0-beta.1

---

CHANGELOG.md
package.json

- Fixes a technical issue that prevented the built application from running.

Release v3.23.0-beta.2

---

CHANGELOG.md
package.json

- Fixes the displayed icon of recently synchronized files whose type
is identified as text.

Release v3.23.0-beta.3

---

CHANGELOG.md
package.json

- Fixes the infinite spinner of the Updater window, displayed when
download progress info is not available.

Release v3.23.0-beta.4

---

package.json
yarn.lock

This version brings the possibility to abort upload requests via an
AbortController `signal` passed via the client request options.

deps: Upgrade cozy-client-js

---

CHANGELOG.md
package.json

- We upgraded `cozy-client-js` for the request abortion, shipped in
the previous beta release, to work.

Release v3.23.0-beta.7

---

core/remote/cozy.js

We introduced unhandled promise rejections "handling" via the
`process` `unhandledRejection` event listener to make sure upload
requests will always terminate even when the underlying chromium
request fails with an unhandled promise rejection.
However, if the request succeeds, we don't remove the event listener
and thus we'll keep adding listeners with every upload.
We now remove the listener even if it was not triggered (i.e. the use
of `once` would remove it in this case).
This avoids `MaxListenersExceededWarning`s especially during tests.

core/remote: End rejections handling with request

---

.editorconfig
.travis.yml
dev/setup.sh
docker-compose.yml
gui/js/updater.window.js
test/setup.sh

dev: Small fixes to dev and test environments

---

doc/usage/windows.md

Documentation: Win 32 is not supported anymore

---

core/pouch/index.js
test/unit/pouch/index.js

We add the possibility to fetch documents from PouchDB via their
`path` attribute. This is done via a new `Pouch.bySyncedPath()`
method and a change in the `byPath` view.
The view will now emit the normalized parent path and name of each
document — both computed from the document's `path` — instead of the
parent path alone. This allows us to query documents via their full
path in addition to their parent path (thus preserving the
`Pouch.byPath()` and `Pouch.byRecursivePath()` querying methods).
We introduce a new querying method, `Pouch.bySyncedPath()` which will
return the first document matching the given path.
Being able to query documents by their `path` is a pre-requisite to
generating PouchDB record ids independant from the documents' paths.
Please make sure the following boxes are …

core/pouch: Allow fetching docs via their `path`

---

core/merge.js
test/integration/conflict_resolution.js
test/unit/merge.js

When the client was connected to a remote Cozy while there are
existing files in the local synced folder, any file with the same path
as a remote one would generate a conflict fixed by renaming the remote
file with a conflict suffix.
We can avoid many conflicts by linking together local and remote files
which have the same content.
Since the logic to merge file additions when a PouchDB record with the
same path already exists is now shared with the logic to merge file
modifications, we have to make slight modifications to the
`Merge.updateFileAsync()` method.
Indeed, in case the "added" local and remote files don't actually have
the same content, we'll want to create a conflict but we can't
dissociate the remote document of the just merged local file like we
would in the case of an …

core/merge: Initial sync links existing docs

---

test/support/builders/remote/file.js
test/unit/merge.js

tests: New tests and refactorings

---

CHANGELOG.md
package.json

- We'll now track more closely the local modifications resulting from
the application on the filesystem of changes fetched from the remote
Cozy. This is important especially for tracking movements and make
sure opposite movements won't be wrongly "detected" after a client
restart.
- We've made sure the logic dedicated to the initial scan, run after a
client start, won't be used after the initial scan is done. This was
the source of bugs when applying folder movements fetched from the
remote Cozy.

Release v3.24.0-beta.2

---

CHANGELOG.md
package.json

- We fixed the way we fetch the local documents tree to both prevent
failures when sending messages to support from the application and
send the appropriate paths.

Release v3.24.1-beta.1

---

CHANGELOG.md
package.json

- We fixed the way we fetch the local documents tree to both prevent
failures when sending messages to support from the application and
send the appropriate paths.

Release v3.24.1

---

gui/js/window_manager.js
gui/main.js
package.json
test/unit/remote/watcher.js
yarn.lock

deps: Bump Electron to v11.1.1

---

core/pouch/index.js

It turns out that the `leveldb` adapter of PouchDB is not crash safe.
This means that shutting it off at the wrong time can leave the
database in a corrupt state.
See https:/github.com/pouchdb/pouchdb/issues/3224
Once the database is corrupt, a call to the `allDocs()` PouchDB method
will lead to an uncaught exception because it does not check for
errors on read and tries to access the `_rev` attribute of a missing
record.
See https:/github.com/pouchdb/pouchdb/issues/5309
See https:/github.com/pouchdb/pouchdb/issues/4936
Attempts at providing a fallback method in this situation like
proposed in https:/github.com/pouchdb/pouchdb/issues/4936 did not work
in our case so we'll just catch the exception and return a fatal Sync
error for the moment.
This will block the synchronization and alert …

core/pouch: Catch corrupt PouchDB exceptions

---

CHANGELOG.md
package.json

- We upgraded the framework upon which our application is built,
Electron, to v11.1.1 which is the latest stable version. This should
bring more stability to the application overall and fix an issue on
macOS Big Sur which was preventing the application from restarting
after an upgrade.
- We've changed the way we handle the simultaneous deletions of the
same document on the remote Cozy and the local filesystem so that
any resulting synchronization conflict is only temporary (i.e. you
would see an error message but it should be resolved during the
following retry).
- Several improvements were made to synchronization error detection
and messages over the previous beta release. Messages should be
cleaner with an outstanding document name and filesystem locks …

Release v3.25.0-beta.2

---

CHANGELOG.md
package.json

- To make sure you're not tempted to give up on some changes because
of a temporary error and end up with an desynchronized state and
potentially lose data, we've removed the possibility to manually
give up for most errors that are displayed to you in the main
window. Instead, only conflicts with the remote Cozy will be
droppable as we sometimes find ourselves in a situation where the
conflict will never be resolved.
- We've removed a duplicate retry mechanism for failed movements of
locked documents (e.g. opened Office documents or being checked by
an Anti-Virus software). This should speed up retries when the
document is still locked.

Release v3.25.0-beta.3

---

CHANGELOG.md
package.json

- Clients can now be disconnected from the remote Cozy even if it is
no longer reachable (e.g. completely deleted or deleted after being
moved to another domain). The local configuration and database will
be wiped out.
- Changes that we failed to synchronize and should be retried will now
be retried without previously running a check that validates if the
synchronization should be successful. All changes made either on the
local filesystem or the remote Cozy will thus be taken into account
when retrying.
- We'll now verify if the Cozy has enough space before uploading files
to avoid wasting time and resources to get an error at the end of
the upload.
- Sometimes, the creation and modification dates of documents created
on the remote Cozy at the initiative of …

Release v3.25.0-beta.4

---

core/remote/index.js
test/unit/remote/index.js

When a remote document is renamed with a remote conflict by Sync
instead of Merge, we use a dedicated method, `Remote.resolveRemoteConflict()`.
We were assuming in this method that the current date would always be
the most recent one compared to the last modification date on the
remote Cozy for the document with the given name.
However, there are multiple situations in which this would not be the
case and `cozy-stack` would thus reject the renaming:
- the computer's time is off and late
- the modification date on the remote Cozy was set to a date in the
future
To make sure the Cozy will not reject the renaming of the remote
document, we fetch the remote modification date with the remote _id
and revision and use the most recent date between the current date and
the remote one.
Please make …

core/remote: Conflicts use most recent update date

---

build/entitlements.mac.inherit.plist
core/local/chokidar/initial_scan.js
core/local/errors.js
core/local/index.js
core/local/sync_dir.js
core/remote/cozy.js
gui/js/updater.window.js
gui/js/window_manager.js
gui/main.js
gui/ports.js
package.json
test/support/builders/stream.js
test/support/hooks/logging.js
test/unit/gui/updater.window.js
test/unit/local/index.js
test/unit/remote/cozy.js
yarn.lock

Bump Electron to v12.0.0

---

core/sync/index.js
test/integration/trash.js
test/unit/sync.js

The Sync retry mechanism includes incrementing the failed change
errors counter in its PouchDB record. This step is also useful in some
cases where we made some changes to the record when catching the
propagation error (e.g. when failing to update a remote file after
successfully moving it) and need to save them to PouchDB to make sure
they won't be picked up later (when retrying the propagation for
example).
However, saving the record will generate a new PouchDB sequence for
the change and will prevent the user from manually skipping it as this
relies on marking the change's sequence as processed. In this
situation, we'll still retry the failed change after the user has
requested to skip it.
To allow for both behaviors to coexist, we'll only save the modified
record with its incremented …

core/sync: Update errors only when about to retry

---

dev/remote/automated_registration.js
dev/remote/generate-test-env.js

The cozy-stack login and authorization pages have recently changed
and the authorization form does not have the `auth` class anymore so
our script would not find it in the HTML thus failing to update and
submit its content.

dev: Fix automated registration form parsing

---

doc/feedback.md

Switch from freenode to libera.chat

---

core/utils/fs.js

The error message thrown by Electron's `shell.trashItem()` method is
localized on macOS. Therefore, we can't detect missing document error
by matching the error message against a crafted RegExp as this would
mean building a RegExp that matches against every possible language.
e.g. when deleting missing `dir/file.txt`, the message would be:
- in English, `The file « file.txt » doesn't exist`
- in French, `Le fichier « file.txt » n'existe pas`
The only way to be sure `shell.trashItem()` failed because the
document does not exist anymore is to check whether the document
exists or not (minus some potential race condition issues).
This is slightly less efficient but works on all platforms for
every language.

core/utils/fs: Check for doc presence when handling trash errors

---

elm.json
gui/elm/Data/UserAction.elm
gui/elm/Locale.elm
gui/elm/Util/DecorationParser.elm
gui/elm/Window/Tray/Dashboard.elm

Move all the `UserAction` view logic to the `UserAction` module to
improve its readability and better separate concerns, fix the
`interpolate` and `capitalize` localization methods and fix the
document path decoration in error messages.

gui: Refactor UserAction view

---

CHANGELOG.md
package.json

- Error messages will now be properly localized and the document names
included in some of them should be properly displayed instead of
their type.

Release v3.29.0-beta.2

---

.jq
core/local/atom/add_checksum.js
core/remote/cozy.js
core/remote/watcher/index.js
core/sync/errors.js
core/sync/index.js

Small changes

---

core/local/atom/overwrite.js
test/unit/local/atom/overwrite.js

We make sure pending batches are not outputted until the end of the
timeout delay (i.e. they were outputted with each new batch).
The Atom `overwrite` step's role is too old on `deleted` events so
they can potentially be matched with later `renamed` or `created`
events thus detecting an overwriting move or creation.
To do this, we first try to match events within the same Atom
`producer` batch. If we can't find any match, this batch will be kept
around for a while so we can try to match its events with those of a
later batch.
However, we were outputting the batch kept as pending every time we
would receive a new batch, even if its output delay was over.
This means that potential matches would be missed if they were parts
of batches separated by another batch.
e.g. a `src/` folder move to …

core/local/atom/overwrite: Match with old batches

---

CHANGELOG.md
package.json

- All child moves (i.e. document moved because their parent directory
was moved) will now be notified to the GUI so the child documents
paths can be updated in the list of recently synchronized documents.
- We've introduced a mechanism to detect dependencies between multiple
changes on the same side (i.e. the local filesystem or the remote
Cozy) and synchronize them in the right order. We've added a few
dependencies that let us solve situations that were known to fail
(e.g. trashing directories as a whole instead of trashing every
element separately) and we will add more as needed in the future.
- As stated above, directories will now be trashed as a whole but we'll
now also keep empty directories in the trash instead of erasing them.
It should be easier for …

Release v3.30.0

---

CHANGELOG.md
package.json

- We've optimized the initial listing of documents present on the remote
Cozy to limit the number of necessary network requests and the CPU and
RAM usage. This should also result in a quicker listing.
Improvements for Windows and macOS users:
- The improvement introduced in the latest version around the trashing
of complete folders (i.e. keeping their hierarchy in the Trash) would
in turn generate visible errors in the main window and pause the
synchronization until the remote trashing of all the documents in the
folder would be fully synchronized.
We're now making sure the trashing of a folder is swift and does not
result in unnecessary errors.

Release v3.30.1

---

CHANGELOG.md
package.json

- Default values will now be provided by the client for remote metadata
when they're not provided by cozy-stack.

Release v3.30.1-beta.2

---

CHANGELOG.md
package.json

- We updated the localizations and fixed some GUI texts which were not
correctly localized.

Release v3.30.1-beta.3

---

.github/actions/setup-couchdb/action.yaml
.github/workflows/macos.yaml

ci: Ensure macOS env preparation success

---

CHANGELOG.md
package.json

- We will now automatically refresh the app's OAuth client when it
expires on any request. This should prevent synchronization errors and
avoid the need for restarting the app in such cases.
- We have improved the performance of the initial remote changes fetch
which could be slow enough on old Cozy to fail.
- We've tweaked the app's status update to make it less likely to show
an "up-to-date" status while we're actually fetching changes from the
Cozy.

Release v3.31.0-beta.2

---

CHANGELOG.md
package.json

- We upgraded our Electron dependency to v12.2.1 which includes lots of
CVE patches, a patch for a certificate issue following the end of the
Let's Encrypt first root certificate validity and patches around
certificates validation which we hope should resolve the missing
network problem some users are experiencing.
- We updated some of our status messages with the hope they will be
easier to understand.
- We will now automatically refresh the app's OAuth client when it
expires on any request. This should prevent synchronization errors and
avoid the need for restarting the app in such cases.
- We have improved the performance of the initial remote changes fetch
which could be slow enough on old Cozy to fail.
- We've tweaked the app's status update to make it …

Release v3.31.0

---

CHANGELOG.md
package.json

Includes the full partial sync feature behind the
`settings.partial-desktop-sync.show-synced-folders-selection` flag.

Release v3.32.0-beta.1

---

CHANGELOG.md
package.json

- The core of the synchronization process can handle selective
synchronization without flags (only the configuration of the selective
synchronization remains hidden behind a flag).
- Most remote folder deletion situations should be handled and the same
goes for remote folder exclusions as part of the selective
synchronization.

Releave v3.32.0-beta.3

---

CHANGELOG.md
package.json

- The URL validation step of the on-boarding wizard is now able to
detect your Cozy root URL in more complex URLs (e.g. a photo album URL
copied from your Cozy Photos app in your browser).
- When the server hosting your Cozy experiences issues, the Desktop
client will display a specific error message instead of telling you
that no internet connection is detected.
- Files being transferred to or from your Cozy will now be displayed in
the main window's Recent tab with progress information.
- We've made some optimizations to remote content fetching so the
initial synchronization and the retrieval of remote directories
content require less network requests and less memory.
- You will now be able to completely reinitialize your Desktop client's
synchronization from …

Releave v3.33.0-beta.1

---

core/app.js
core/sync/index.js
core/syncstate.js
core/utils/web.js
elm.json
gui/elm/Data/UserAlert.elm
gui/elm/Ports.elm
gui/elm/Util/Conditional.elm
gui/elm/Util/Mouse.elm
gui/elm/Window/Tray.elm
gui/elm/Window/Tray/Dashboard.elm
gui/js/cozy-web.window.js
gui/js/tray.window.js
gui/ports.js
gui/utils/web.js
test/unit/sync/index.js

We will now offer ways to open the remote Cozy Drive application by
pressing the `Ctrl` key while clicking on links and buttons that would
otherwise open local OS applications like the file explorer.

gui: Open Cozy web in Desktop with Ctrl+click

---

CHANGELOG.md
package.json

- Localizations strings have been updated and the new empty Recent tab
placeholder has been localized.
- Confirmation dialogs for reinitializing the synchronization and
unlinking the remote Cozy are more homogeneous and will prevent the
main window from closing until the requested action is confirmed or
canceled.
- Sub-directories excluded from a Desktop client's synchronization and
their content won't be fetched anymore when their parent directory is
re-included.

Release v3.33.0-beta.3

---

core/merge.js
test/unit/merge.js

When the client detects "modifications" (i.e. it could also be the
first time we see the file) both locally and remotely on the same
file, we rename the file on one side with a conflict suffix to avoid
losing content.
However, since modifications synchronized with the remote Cozy are
versioned (conditions can vary depending on the configuration of
`cozy-stack` but, by default, a new version is created if the file has
not been modified in the previous 15 minutes), we can use these old
versions to make better decisions and avoid some conflicts.
Therefore, if the local content (modified or not) can be found in the
old versions of the remote file, we'll overwrite it with the current
remote content instead because the user will be able to retrieve it if
necessary.
The same is true when moving …

core/merge: No conflicts on versioned local files

---

CHANGELOG.md
package.json

- We fixed a bug affecting sub-directories of sub-directories of
directories moved on the remote Cozy. These could not be updated from
the local filesystem anymore, triggering Invalid Metadata errors when
the client would try to synchronize the local modifications (e.g. a
move).
All directories that were affected will be fixed by a data migration
upon restart of the client.
- Fetching new remote changes will now be faster as we've removed some
network calls that are not necessary anymore.
- The client should create fewer conflicts on files as we've improved
the decision logic when dealing with conflicting local and remote
changes. If the local content can be found in one of its old versions
stored on the remote Cozy then the client will overwrite it with the …

Release v3.34.0-beta.1

---

CHANGELOG.md
package.json

- We fixed a bug affecting sub-directories of sub-directories of
directories moved on the remote Cozy. These could not be updated from
the local filesystem anymore, triggering Invalid Metadata errors when
the client would try to synchronize the local modifications (e.g. a
move).
All directories that were affected will be fixed by a data migration
upon restart of the client.
- Fetching new remote changes will now be faster as we've removed some
network calls that are not necessary anymore.
- The client should create fewer conflicts on files as we've improved
the decision logic when dealing with conflicting local and remote
changes. If the local content can be found in one of its old versions
stored on the remote Cozy then the client will overwrite it with the …

Release v3.34.0

---

CHANGELOG.md
package.json

- We fixed an issue with a data migration shipped with the previous
release. It affected clients connected to Cozies with a large number
of directories.

Release v3.34.1

---

CHANGELOG.md
package.json

- We fixed another issue with the latest data migration. It affected
users who had deleted directories which were still known to the local
PouchDB database.
Missing directories will now be handled appropriately.

Release v3.34.2

---

gui/js/updater.window.js

Instead of trying to update the app forever in case we're encountering
a persistent error, we will only try 5 times and skip the update if we
still can't download it at that point.

gui/updater: Stop retries after a few errors

---

gui/elm/Data/UserAlert.elm
gui/locales/de.json
gui/locales/en.json
gui/locales/eo.json
gui/locales/es.json
gui/locales/fr.json
gui/locales/it_IT.json
gui/locales/ja.json
gui/locales/nl.json
gui/locales/nl_NL.json
gui/locales/pl.json
gui/locales/sq.json
gui/locales/zh_CN.json

The previous message tried to give the user some hints on how to solve
the issue but did so poorly and the CTA (i.e. Give up) could be scary.

gui: Change large file error message and CTA

---

CHANGELOG.md
package.json

- We fixed a few issues that were preventing the correct processing of
movements and renamings of documents that have never been synchronized
and sometimes not even been saved in our local database.
These should now be handled as creations at their new path and
overwritten documents trashed on the other side.
- We've fixed yet another issue with data migrations making requests to
the remote Cozy when the Desktop's Oauth client has been revoked on
the Cozy.
You will now be be informed of the issue and given the opportunity to
reconnect your client.
- To prevent blocking the Desktop client to start and synchronize when
an app update is available but downloading it consistently fail, we've
decided to stop retrying the download after 5 failures. The client
will …

Release v3.35.0-beta.1

---

core/local/atom/add_infos.js
core/utils/timestamp.js
dev/capture.js
package.json
test/scenarios/run.js
test/support/builders/remote/file.js
test/support/helpers/local.js
test/support/helpers/scenarios.js
test/unit/merge.js

Various fixes and improvements of tests, especially scenarios, to help
stabilize builds.

test: Various fixes and improvements

---

.github/actions/build-and-publish/action.yaml
gui/js/details.window.js
gui/js/help.window.js
gui/js/markdown-viewer.window.js
gui/js/onboarding.window.js
gui/js/tray.window.js
gui/js/updater.window.js
gui/js/window_manager.js
gui/utils/notes.js
package.json
yarn.lock

deps: Upgrade Electron to v19.0.0

---

CHANGELOG.md
package.json

- The Electron framework was upgraded to v19.0.0. This major version
fixes a lot of security errors as well as other smaller errors like
crashes.
- We fixed the invalid path error details window which would not show up
anymore. We took the opportunity to improve its display and have the
whole content fit in the window without scrollbars.
- We replaced our filesystem changes surveillance library to
use @parcel/watcher as @atom/watcher is not maintained anymore and was
preventing us from upgrading Electron.
Although the behavior of Cozy Desktop should remain mostly untouched,
it should be easier to follow document movements on Windows and faster
to scan folders, especially during an app start.
Improvements for Linux …

Release v3.36.0-beta.1

---

CHANGELOG.md
package.json

- The Electron framework was upgraded to v19.0.0. This major version
fixes a lot of security errors as well as other smaller errors like
crashes.
- We fixed the invalid path error details window which would not show up
anymore. We took the opportunity to improve its display and have the
whole content fit in the window without scrollbars.
- We replaced our filesystem changes surveillance library to use
@parcel/watcher as @atom/watcher is not maintained anymore and was
preventing us from upgrading Electron.
Although the behavior of Cozy Desktop should remain mostly untouched,
it should be easier to follow document movements on Windows and faster
to scan folders, especially during an app start.
Improvements for Linux …

Release v3.36.0

---

.appveyor.yml
.github/actions/build-and-publish/action.yaml
.github/workflows/linux.yaml
.github/workflows/macos.yaml
build/afterSignHook.js
electron-builder.yml
package.json

- set targets via electron-builder config file
- fail macOS build job on notarization failure
- attach built artifacts to CI runs
- fix Electron installation on AppVeyor
---

ci: Improvements around package building

---

CHANGELOG.md
package.json

- Thanks to https://github.com/ArchangeGabriel, we should now unpack all
of our binary dependencies before the application is run, saving some
startup time and avoiding anti-viruses alerts.
- We fixed a bug in the process that fetches a directory's content when
it is re-included in the synchronization that was preventing it from
completing.

Release v3.36.1-beta.1

---

.github/dependabot.yml
.github/workflows/linux.yaml
.github/workflows/macos.yaml

Some of our actions use deprecated syntax that will soon be disabled.

ci: Update Github's actions to latest version

---

gui/js/tray.window.js
package.json
test/support/hooks/index.js
test/support/suppress-experimental-warnings.js
yarn.lock

deps: Upgrade Electron to v23.0.0

---

CHANGELOG.md
package.json

- The Electron framework was upgraded to v23.0.0. This major version fixes a lot of security errors as well as other smaller errors like crashes.
- Local renamings of files being uploaded will now be correctly synchronized on the remote Cozy without the need of a client restart.
- Desktop will now restart its local watcher when the local filesystem notifies that the local synchronization directory should be rescanned because some changes could not be transmitted to the application. This should prevent the few cases of trashing of all synchronized content.

Release v3.37.0-beta.1

---

CHANGELOG.md
package.json

- The Electron framework was upgraded to v23.0.0. This major version fixes a lot of security errors as well as other smaller errors like crashes.
- Local renamings of files being uploaded will now be correctly synchronized on the remote Cozy without the need of a client restart.
- Desktop will now restart its local watcher when the local filesystem notifies that the local synchronization directory should be rescanned because some changes could not be transmitted to the application. This should prevent the few cases of trashing of all synchronized content.

Release v3.37.0

---

package.json
test/support/helpers/scenarios.js
test/unit/local/channel_watcher/channel.js
test/unit/migrations/index.js
test/unit/remote/offline.js
test/unit/remote/watcher.js
yarn.lock

deps: Upgrade `flow-bin` to v0.108.0

---

CHANGELOG.md
package.json

- We will now fetch the latest changes from your Cozy as soon as they've
been made (with some delay in case many changes were made).

Release v3.39.0-beta.1

---

CHANGELOG.md
package.json

- We fixed our network configuration as it was preventing the realtime manager, responsible for fetching changes from your Cozy as soon as they've bee made, to create a connection with the Cozy.

Release v3.39.0-beta.2

---

CHANGELOG.md
package.json

- We fixed our network configuration as it was preventing the realtime
manager, responsible for fetching changes from your Cozy as soon as
they've bee made, to create a connection with the Cozy.

Release v3.39.0-beta.3

---

doc/usage/linux.md
doc/usage/macos.md
doc/usage/windows.md

- macOS and Windows were streamlined to only the latest 2 versions
- Linux distributions were streamlined to only the latest version of
each distribution already present in the table

docs: Update supported usage tables

---

core/remote/watcher/index.js

Since we're not completely sure the implementation of realtime
reaction to remote changes is functionnal, we'll put it behind a local
feature flag.

feat: Add realtime behing flag

---

core/sync/index.js

The PouchDB changes observers in Sync could cancel each other while
events would still be emitted but those emitted for
`waitForNewChanges` would not get returned to the caller because
`this.changes` would be null at that point.
We would then stop synchronizing changes!
Separating the changes observers using local variables should fix this.

fix: Prevent race conditions between in Sync

---

.github/actions/setup-dnsmasq/action.yaml
.github/workflows/macos.yaml
core/local/chokidar/analysis.js
core/local/chokidar/event_buffer.js
core/local/chokidar/initial_scan.js
core/local/chokidar/prepare_events.js
core/local/chokidar/watcher.js
test/scenarios/run.js
test/support/helpers/pouch.js
test/unit/local/chokidar/analysis.js
test/unit/local/chokidar/event_buffer.js
test/unit/local/chokidar/watcher.js

fix: Prevent Chokidar events processing issues

---

CHANGELOG.md
package.json

- Cozy Desktop will now stop its processes when power is suspended and
restart them when power is resumed. This should speed up suspension
and prevent unwanted wake ups in some situations but, mostly it will
ensure that processes are fully functional when power is resumed (we
could lose the remote watcher leading to missed remote changes).
- The realtime remote changes detection feature is now hidden behind a
flag so we can do more tests in live conditions before releasing it to
everybody.
- We fixed an issue in the detection of changes to synchronize (i.e.
after they've been detected either on the local filesystem or the
remote Cozy) which could lead to the synchronization process hanging
until the application is restarted.
- …

Release v3.39.0-beta.5

---

core/remote/constants.js
core/remote/watcher/index.js
test/unit/remote/watcher.js

fix: Make sure RemoteWatcher.requestRun resolves

---

CHANGELOG.md
package.json

- We fixed a regression introduced in the remote watcher that could lead
to a stuck synchronization process after an error such as failing to
create a conflict on the remote Cozy.

Release v3.39.0-beta.6

---

core/utils/sentry.js
package.json
yarn.lock

deps: Upgrade @sentry/electron to v5.7.0

---

.github/workflows/macos.yaml
electron-builder.yml

This build will run without the need for an emulator on Apple
processors which should give them a performance boost.

feat: Add Apple processors build

---

core/app.js
gui/locales/de.json
gui/locales/en.json
gui/locales/eo.json
gui/locales/es.json
gui/locales/fr.json
gui/locales/it_IT.json
gui/locales/ja.json
gui/locales/nl.json
gui/locales/nl_NL.json
gui/locales/pl.json
gui/locales/sq.json
gui/locales/zh_CN.json
gui/main.js
package.json

feat: Change support e-mail address for Twake's
