backend/config.coffee, backend/db.coffee, backend/remote_event_watcher.coffee, cli.coffee
So these two commits fixes #81, by adding an option --insecure (short flag is -k, which is the same in curl).  This option disables certificate validation.  Will be useful once https://github.com/pouchdb/pouchdb/issues/3504 gets fixed.
=> Enable insecure HTTPS at runtime

package.json
:rocket:
path-extra just published version 2.0.0, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
The new version differs by 6 commits (ahead by 6, behind by 0).
- [07260c7](https://github.com/jprichardson/node-path-extra/commit/07260c7caf5cc2908b7b41ce246d9b94c2ce3eb5): 2.0.0
- [051c724](https://github.com/jprichardson/node-path-extra/commit/051c724f7d92e2c4a7e5f9b7ae9b1f9dd5d752af): Merge pull request #13 from nono/env
- [c9061f3](https://github.com/jprichardson/node-path-extra/commit/c9061f339a5ad2c67a7759677a1110c86f127ff2): Respect XDG Base Directory Specification
- [acf71ed](https://github.com/jprichardson/node-path-extra/commit/acf71e …
=> Updated path-extra to version 2.0.0

backend/merge.coffee
Cozy-desktop failed after doing `mkdir a/b/c/d ; rm -rf a` in a watched folder. I think it's a race condition in PouchDB, but I didn't reproduce it on a simpler test case. For the moment, this commit is a work-around for this bug. But for the long-term, we should find the real bug.
=> Work-around for nested deletion

backend/remote/index.coffee, tests/unit/remote/index.coffee
When an image is uploaded on the cozy, its metadata are updated in the
CouchDB to include a thumbnail. So, for the write-only mode, it is
expected that the remote revision can sometimes be desynchronized with
the revision stored in the local PouchDB. This commit adds a way to
bypass this desynchronization and allow to update/remove the images.
=> Fix for images on write-only

README.md, backend/app.coffee, backend/config.coffee, bin/ci, bin/cli.coffee, bin/fauxton.coffee, gulpfile.js, tests/helpers/config.coffee, tests/helpers/couch.coffee, tests/unit/config.coffee
Using the same metadata database for one time pushing and other time pulling is dangerous. So, I've blocked that and explained how to use COZY_DESKTOP_DIR if you want to play with both modes.
=> No push pull

backend/remote/watcher.coffee
A small fix for a race condition when a file is deleted at the same time from the local and the remote, because it was on a folder that was removed.
=> Fix a race condition when deleting a folder

backend/merge.coffee
When an image was added to the synchronized folder, both sides tried to
update it in a loop:
- remote -> local, because cozy creates thumbnails for the image
- local -> remote, because cozy-desktop update the lastModification
with `fs.utimes` and it as the side effect to also update the
creationDate.
Cozy-desktop now preserve the creationDate, which breaks the loop.
=> Fix loop for images

backend/remote/index.coffee
If the user deletes a file on its local folder and its cozy when cozy-desktop is stopped, it should not block cozy-desktop. This commit fixes this.
=> Fix for files deleted on both local and remote sides

.travis.yml, package.json, src/local/index.coffee, src/local/watcher.coffee, src/remote/index.coffee, src/sync.coffee, test/helpers/files.coffee, test/helpers/integration.coffee, test/integration/move_file.coffee, test/integration/quickcheck.coffee
We launch 2 cozy-desktops in two directories, and make them synchronize via a central cozy instance. During ~10 seconds, we do some operations in both directory (like creating files, or moving folders). After that, we wait 20 seconds and we compare the 2 directories. They should be identical: same files and folders.
=> Add property based testing

README.md, doc/debug.md, doc/design.md, package.json, src/app.coffee, src/bin/cli.coffee, src/ignore.coffee, src/prep.coffee, src/sync.coffee, test/unit/ignore.coffee, test/unit/prep.coffee, test/unit/sync.coffee
Cozy-desktop can now ignore somes files and folders when doing the synchronization. The users can list what they want to ignore in the `.cozyignore` file. The syntax for this file is the same as `.gitignore`.
=> Allow users to ignore somes files listed in .cozyignore

.travis.yml, README.md
Node 0.10 and 0.12 will reach their end of life this year. So, it's time to make node 4 the default. We need to test cozy-desktop with node 5 as we will use it inside Electron for the GUI and Electron comes with node 5. Node 0.10 is still used a lot, in particular on Ubuntu and Debian, so we should keep the tests for it too. But I've disabled the build for node 0.12 to focus the support on the three other versions.
=> Explain that node 4 is recommended

src/local/index.coffee, src/merge.coffee, test/unit/helpers_merge.coffee
I've modified two things for when we check if a file or a folder has changed:
1. The comparison of the executable flag failed in some rare cases previously. It should be more robust now.
2. The creation date was compared. It is no longer the case. The local filesystem can't give us it in a reliable way (it only has access time, change time and update time on a lot of cases). So, it's better to ignore it.
=> Improve stability and avoid many useless exchanges

src/remote/index.coffee, test/unit/remote/index.coffee
When a file is uploaded and modified at the same time, the uploaded file can be corrupted. This fix compute the checksum of the uploaded file to be sure that it won't happen.
=> Fix corrupt upload

gui/package.json
From https://github.com/electron-userland/electron-builder/issues/375
=> Install libappindicator1 as a dependency of the linux package

.travis.yml, README.md, gui/README.md, gui/package.json
Electron 1.1.0 is now coming with node 6. We can remove the build with node 5 on travis, as node 5 will soon be no longer supported.
=> Use Electron 1.1.0

gui/app/locales/en.json, gui/app/locales/fr.json, gui/app/main.js, gui/app/ports.js, gui/lib/Folder.elm, gui/lib/Main.elm, src/app.coffee
It can happen, for example, when a file already exists at this path.
=> Show error when the sync path is invalid

src/bin/fauxton.js, test/helpers/v2/couch.js
It was broken while moving v2 test helpers to a subdir.
=> bin/fauxton: Fix v2's couch helpers import

src/remote/cozy.js, src/remote/index.js, test/unit/remote/index.js
I assumed remaining TODO notices were part of conflict management => to be fixed in another story.
To be merged after https://github.com/cozy-labs/cozy-desktop/pull/546
=> Remote update file metadata

src/local/index.js, src/remote/cozy.js, src/remote/index.js, src/side.js, src/sync.js, test/unit/local/index.js, test/unit/remote/index.js, test/unit/sync.js
- `Local#trash()` still destroys for now
- `Remote#trash()` may eventually put some folder's content inside the trash before the folder itself, but I'd prefer to fix it in next PR.
=> Side trash and destroy

src/local/watcher.js, src/logger.js, src/sync.js, src/utils/pending.js, test/unit/sync.js, test/unit/utils/pending.js
WIP
Right now, this works because chokidar triggers file events before dir ones (should we rely on this?)
=> Sync to trash

package.json, yarn.lock
We will also need https://github.com/cozy/cozy-client-js/issues/88 for the packaging of cozy-desktop-gui (or include pouchdb-find in our package.json).
=> Fix: babel-polyfill is a runtime dependency, not a development one

gui/app/main.js
It's safer to clear the cookies after the user has given the permission to the device to access to his files on the Cozy.
=> Clear cookies in Electron

src/remote/watcher.js, test/unit/remote/watcher.js
A move may actually generate conflicts.
Deleting the trashed content then adding back the new metadata is safer.
Deleting the existing metadata then adding back the restored content goes the same.
This relies on some upcoming feature in cozy-stack: since files will get their
hidden flag updated when trashed/restored, they will appear in the changesfeed,
and everything should just work.
=> remote/watcher: Make sure trashed/restored content is not handled as a move

src/local/index.js, src/remote/index.js, src/side.js, src/sync.js, test/unit/sync.js
Right now we only promisify `fileChanged()` and `folderChanged()` since this should allow us to progressively remove callback-based wrappers in `Sync`'s dependencies.
=> Sync promisification

.travis.yml
To make sure dtrace-provider is recompiled.
See: https://travis-ci.org/cozy-labs/cozy-desktop/jobs/223061506
=> build: Try not to cache node_modules on CI

src/remote/watcher.js, test/unit/remote/watcher.js
This code was inherited from cozy-v2, but it's no longer relevant.
In cozy-v2, we had 2 documents in CouchDB for 1 file: one for metadata and one for the content. And it can happen that local modify the content while the remote renamed it. It's no longer the case in V3, we have other constraints. In particular, not having a continuous change feeds increases the risk of coming back to old version of a file when there are several changes on the local side in the short period of times. This PR should fix this case.
=> Fix for writing the same file several times in a few seconds

gui/package.json
So we don't need to export the certificate and use some password env var.
We can still follow the standard way later, would it be more convenient.
=> Use Windows personal certificate store

src/merge.js
The `updated_at` field on a local filesystem can have a worse precision,
and be ceiled to the second. It was then rejected by the cozy-stack.
=> Fix for renaming in local a file from the remote

gui/app/main.js
Locale cannot be determined from env vars on Windows.
To be portable, we must use electron's standard app.getLocale() function.
But it cannot be used before the ready event is fired.
=> Fix locale

cli/src/local/index.js, cli/src/merge.js, cli/src/remote/cozy.js, cli/src/remote/index.js, cli/src/side.js, cli/src/sync.js, cli/test/builders/metadata/dir.js, cli/test/integration/v3/move.js, cli/test/integration/v3/trash.js, cli/test/unit/local/index.js, cli/test/unit/remote/index.js, cli/test/unit/sync.js
- Prevent PouchDB 409 conflict errors (while preserving behavior)
- Delete empty folders in local/remote trash after move/rename
- In remote client move test, a file may sometimes remain in the local trash (it was already an issue before this fix, to be fixed in another PR)
=> Trash fixes

appveyor.yml
We don't run remote unit/integration tests on AppVeyor anyway.
=> Disable remote instance bootstrap on AppVeyor

gui/package.json
So we don't get a warning anymore.
=> Use new electron-builder install-app-deps subcommand

cli/package.json, cli/src/utils/fs.js, cli/test/unit/utils/fs.js, cli/yarn.lock
Better hide directories with a simple Windows command.
1 dependency less.
No need to depend on a fork anymore.
And we won't need to recompile it for electron everytime we run yarn.
=> Get rid of fswin

cli/src/local/checksumer.js, cli/src/local/index.js, cli/src/local/watcher.js, cli/test/unit/local/checksumer.js, cli/test/unit/local/watcher.js
So we can await for multiple checksum promises at once.
Useful to process an event batch.
=> Promisify checksumer

cli/src/sync.js
So we can effectively test the new releases
=> sync: Temporarily disable the remote Cozy overloading guard

gui/src/main/tray.window.js, gui/src/main/window_manager.js
App is still not visible in dock or with cmd+tab when the tray popover
shows up. Only during auto-update, onboarding or when showing help form.
=> gui: Make tray-running app not visible in macOS dock & cmd+tab

gui/main.js, gui/package.json, gui/src/main/onboarding.window.js, gui/src/main/proxy.js, gui/yarn.lock
=> Use electron-proxy-agent

appveyor.yml
Using a remote cozy instance can be quite slow.
=> ci/appveyor: Increase default timeout to 1min

gui/js/tray.window.js
electron-positioner may throw `TypeError: Error processing
argument at index 0, conversion failure from NaN`. Not sure whether it's
a bug in cozy-desktop, electron-positioner or electron.
Catch error, log it & show the popover wherever possible thus user should
report the issue with useful logs but can still use the app.
=> gui/tray.window: Catch, log & recover from electron-positioner errors

doc/usage/linux.md
Après avoir lancé la commande `strings $(locate -b '\libstdc++.so.6') | grep 'GLIBCXX_[0-9]' | tail -n 1` (il a fallut que j'installe locate et que je crée la DB (`pacman -S mlocate && sudo updatedb`)), je n'ai pas une version suffisante de GLIBCXX.
Comment on peut updater GLIBCXX ?
=> Add Arch Linux GLIBCXX version

.travis.yml
Looks like caching `node_modules` breaks `elm-package install` on macOS builds.
=> ci/travis: Don't cache node_modules

core/remote/watcher.js, test/unit/remote/watcher.js
Be it corrupted on local or remote (md5sum matches but size doesn't)
=> core/remote/watcher: Prevent infinite sync of corrupt file

core/app.js, core/config.js, core/remote/registration.js, gui/elm/Help.elm, gui/js/help.window.js, gui/locales/en.json, gui/locales/fr.json, test/support/helpers/config.js, test/unit/app.js
So we can use our own email and stop polluting support in dev.
Defaults to the real one.
=> core: Support email improvements

gui/js/tray.js
Fixes issue #984 for GNU/Linux distros with KDE. Tested with Kubuntu 17.10
=> Fix tray icon click event for KDE

core/local/analysis.js, core/local/change.js, core/local/watcher.js, core/remote/change.js, core/remote/watcher.js, test/unit/local/analysis.js, test/unit/remote/watcher.js
- Give them a `sideName` property
- Standardize their names
- Shorten their `type` value (no need to prefix with the new `sideName`)
Also fixed incompatibilities that were not emitted anymore.
=> core: Standardize change types

test/unit/pouch.js
Fall on it while testing, it seems there is an issue with "." in strings. Not sure what this implies.
=> Add another Counterexample found by jsverify

core/app.js
So we don't:
- get an error with `unzip logs.zip` because file is not a zip
- get an error with `gunzip logs.zip` because it doesn't like the filename
- need to `mv logs.zip logs.gz && gunzip logz.gz`
=> core/app: Ensure logs archive extension matches the actual format

core/sync.js
It always happens, it's normal, and generates a lot of noise in logs.
We still need to figure out a way to prevent infinite loops though.
=> core/sync: Stop logging already synced seq

test/support/logging.js
Dump logs (JSON lines format) in console for failing test, so we can debug failures occurring only on CI.
Failing build examples:
- [Travis](https://travis-ci.org/cozy-labs/cozy-desktop/jobs/362697020#L3448)
- [AppVeyor](https://ci.appveyor.com/project/cozy/cozy-desktop/build/1.0.517#L860)
I assume it should not be an issue on the security level, since we don't log credentials anyway.
=> Dump failed test logs in console

test/support/helpers/context_dir.js, test/support/helpers/local.js, test/unit/local/index.js
Its API is in no way specific to the sync dir.
This will help testing other directory-relative behaviors.
Also moved `#tree()` there because we'll probably always want to get the tree of some context dir.
Which also means now we can handle the fake trash as any other `ContextDir` (e.g. for *treeing* or *clearing*).
=> test/support: Rename SyncDirTestHelpers to ContextDir including #tree()

test/support/helpers/platform.js
So developers don't end up wondering why some test doesn't run.
=> test/support: Don't swallow skipped test in platform helpers

test/unit/local/index.js
Except:
- createReadStream 1/2 (uses checksumer)
- inodeSetter
- metadataUpdater
=> test/unit/local: Reenable & promisify (almost) all tests

.travis.yml, test/world/case_and_encoding.js
Travis macOS workers switched to 10.13/HFS+:
https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce
We don't handle this combination in tests yet, although it does work in production.
Using an APFS disk image should fix the macOS builds.
=> ci/macos: Fix build

core/local/index.js, core/remote/index.js, core/side.js, test/unit/remote/index.js
So we may stop wondering:
- wether it is actually used or not
- which doc we should rely upon
All writer methods are actually mutating the input doc.
This is what Sync actually uses currently, while some tests were relying
on writer method results, which was wrong.
Now everybody uses the mutated doc (until we rewrite all this using some
functional pattern).
=> core: Stop abusing writers return types

test/integration/case_or_encoding_change.js, test/support/helpers/local.js
So we don't end up with hard-to-debug test failures.
=> Make local tree expectations clearer and more reliable

package.json
I would like to add a commit that changes the tests scripts organization.
`npm run test` runs every tests, at the time I create this Pull Request, it takes more than 15 minutes.
But this classical standard script `npm run test` or `yarn test` is often run as soon as we clone the repository.
So I would suggest to change:
- `"test": "yarn test:world && yarn test:unit && yarn test:elm && yarn test:integration && yarn test:scenarios"` → `"test:all": "yarn test:world && yarn test:unit && yarn test:elm && yarn test:integration && yarn test:scenarios"`
- `"test": "yarn test:world && yarn test:unit && yarn test:elm && yarn test:integration && yarn test:scenarios"` → `"test": "yarn test:unit"`
It would include that we change the `.travis.yml` scripts.
---
Please make sure the following boxes are …
=> chore: Fix test script

.travis.yml
- Update Homebrew then force it to 1.7.2 (both steps seem to be
necessary to make it work)
- Forget Homebrew cache between builds (to make sure we don't end up
with weird cached stuff while adding/removing this fix)
=> travis/macos: Fix Homebrew + CouchDB setup

test/support/logging.js
So we stop getting flooded locally :)
=> test/support: Only dump failure logs on CI

.jq, core/local/analysis.js, core/local/change.js, core/perftools.js, core/remote/user_action_required.js, core/utils/fs.js
- Unify logger names (upper camel case)
- Add missing filters (so we stop adding them one at a time)
- Still support old logger names
=> core,jq: Unify logging & filters

core/local/index.js, test/support/helpers/context_dir.js, test/unit/local/index.js
Stop doing magic like we did in v2, this could mess up with connectors &
sharings:
- Don't delete src when dst exists
- Let it crash on missing src
- Don't create missing dst parent
- Don't fallback to dst creation
Still allow identical rename.
=> core/local: Fix moves

.travis.yml
So we stop wondering about multiline env vars occasionnally breaking the build.
I can't think of any multiline one that would be useful anyway... (please correct me if I'm wrong).
Courtesy of @aenario :)
=> ci/travis/linux: Fix docker --env-file error

test/support/builders/metadata/base.js
Up-to-date metadata always had its sides incremented at least 2 times:
- Once on Merge (on the side from which the change is coming from), e.g.
1-N/A or 2-3
- Once on Sync (on both sides), e.g. 2-2 or 4-4
=> WIP: test/support/builders/metadata: Fix up-to-date sides

dev/cozy-stack/Dockerfile
Tag was force-pushed with development version of the stack, so it works now thanks to @aeris :heart:
=> dev: Use latest cozy-app-dev:2018M3S6 [ci skip]

core/local/analysis.js, core/metadata.js, core/pouch.js
Flagging exceptions didn't work because of bunyan serialization.
=> core: Fix & add Sentry notifications

core/config.js, test/unit/config.js
A corrupted config.json file is not parsable and requiring it throws
an uncaught error, preventing the app to start.
Since we couldn't figure out how this file gets corrupted and since it
can get corrupted by any other software, we catch this error and reset
the file so the app can start in any case.
=> core/config: Reset corrupted config file on start

doc/developer/requirements.md, doc/developer/setup.md, doc/developer/test.md
For Fedora 28:
- add transifex-client, docker and docker-compose dependencies
Add build and run steps, including the creation of a Transifex
account (i.e. to get an API token).
Add command to start the included development cozy-stack via docker in
the testing procedure.
=> Update onboarding procedure

core/merge.js, test/support/builders/metadata/base.js, test/support/builders/metadata/file.js, test/support/builders/metadata/index.js, test/unit/merge.js
Conflicting file/dir move destination id was not matching its path (it was missing the conflict suffix).
=> core/merge: Fix move conflicting destination id

dev/capture/remote.js, test/support/helpers/scenarios.js
So we get a readable output when all we want is to analyse the log file.
=> test/scenarios: log to console with TESTDEBUG, not DEBUG

core/config.js, test/unit/app.js
NodeJS' require maintains a cache of imported modules or, in our case,
configurations.
This is an issue in tests where loading an empty config results in a
complete config object.
In our situation, we can easily replace require with fs.readJSON
which does not maintain any cache.
=> core/config: Replace require with fs.readJSON

.flowconfig, core/config.js, test/unit/config.js
To avoid losing any details of the configuration if the app were to crash or be closed during the persistance process, we use a temporary file.
If the temporary file is not copied (and removed) before we close the app, the next time we fire it up, we'll load this temporary config first.
If the temporary config is not valid (e.g. we didn't have the time to finish writing its content), we remove it and load the existing config.
If we load the existing config and it's not valid, we reset it.
To make sure the tmp config path is writable and its content is only visible to the current user, we reuse the existing config path and add a `.tmp` suffix.
=> core/config: Persist config via temporary file

.travis.yml
Enabling builds of Pull Requests will help us in adding a comment to
them with links to the built artifacts.
However, this means we'll build twice the same commits: once for the
push to the remote branch and once for the creation of the pull
request.
We can avoid this by disabling builds on branches but we'll keep
builds for the master branch since there won't be any pull request for
this branch.
=> travis: Build master branch only

core/config/.cozyignore, core/ignore.js, test/unit/ignore.js
I extracted some code from the class as they can be standalone
functions: easier to test, better insulation.
I reorganized tests by creating categories: easier to maintain,
faster to read.
I extracted default patterns to a standalone configuration file:
easier to patch, better SRP.
Let me know if every thing looks great to maintainers.
=> feat: Enhance Ignore files and folders feature

.travis.yml, dev/ci/after_failure.sh, dev/ci/coverage.sh, dev/ci/dist.sh, dev/ci/scenarios.sh, dev/ci/start_xvfb.sh, dev/ci/tests.sh
Travis offers running different jobs in parallel to speed up builds.
If we can run more than 2 jobs in parallel (it depends on load) then
we can get the final results of our builds much more quickly.
This commit separates unit & integration tests, real life scenarios,
building the binaries and running codecov.
=> travis: Run tests and other jobs in parallel

core/local/watcher.js
- Standardize failure messages
- Make it clear the missing file message is checksum related
=> core/local/watcher: Improve failed checksum logs

core/app.js, core/globals.js, gui/main.js, test/support/stacktraces.js
- It was repeated in to places
- It is global to the app/runtime (not GUI specific)
- It has nothing to do with test stacktraces support
=> core: DRY electron hack

.travis.yml, dev/ci/dist.sh, dev/ci/notify.sh
Each time we build a Pull Request on travis, we build the binary
artifacts for linux and mac OSX.
We upload those binaries to bintray.com and add a comment on the PR so
we can easily find them and test the Pull Request before merging it.
=> travis: Make built artifacts available in each PR

package.json
So the runtime actually matches the production one.
=> repl: Use electron embedded node

.travis.yml
We can avoid the slow brew update by installing CouchDB via an URL
=> Make travis/macOS builds faster

core/app.js, core/ignore.js, test/unit/app.js, test/unit/ignore.js
- User-defined rules with CRLF inside were not loaded
- Default rules could not be loaded on Windows development workstation depending on git config
=> core: Fix ignore rules CRLF issue

core/merge.js, core/prep.js
The conflict resolution can't work here, as it will try to move a deleted file/folder.
=> Handle doctype mismatch on doTrash

core/remote/cozy.js, test/unit/remote/cozy.js
When changesFeed `_changes` are very big, the request fails with timeout.
The idea of this PR is to fetch changesFeed by chunks of 10k items.
Implementation is recursive.
What do you think?
=> fix: Fetch changesFeed with recursive paginated call

core/remote/change.js, core/remote/watcher.js, test/unit/remote/watcher.js
Since it was not used anymore.
Also replaced 'Remote' type prefix with sideName (same as RemoteChange).
=> core/remote: Merge RemoteNoise into RemoteChange

yarn.lock
The version 5.1.2 of har-validator was unpublished on npm.
See https://github.com/ahmadnassri/node-har-validator/issues/112
=> Fix install of har-validator

.travis.yml
When CouchDB is too slow to start, the generation of the COZY_STACK_TOKEN fails. With this commit, we will wait longer that CouchDB has started.
=> Fix missing COZY_STACK_TOKEN on travis

test/unit/merge.js
`doc` was created before `was` in this test, and when the two dates don't have the same ISO string serialization (which happens rarely as they are very close), the test fails. By creating the documents in the good order, we can prevent that.
=> Fix an intermittent test failure

core/merge.js, core/metadata.js, core/pouch.js, core/sync.js, test/integration/move.js, test/unit/merge.js, test/unit/metadata.js, test/unit/pouch.js
If a new file is moved after we've detected the addition but before we
could upload it, we should not try to apply the following move as the
source file does not exist on the filesystem anymore but instead treat
it as an addition of the destition file and remove the source file in
Pouch.
=> core/merge: Treat move before upload as addition 

core/conversion.js, core/remote/cozy.js, core/remote/document.js, core/remote/watcher.js, test/integration/corruption_fixer.js, test/integration/platform_incompatibilities.js, test/support/builders/remote/base.js, test/support/builders/remote/dir.js, test/support/builders/remote/file.js, test/support/helpers/cozy.js, test/support/helpers/remote.js, test/unit/conversion.js, test/unit/metadata.js, test/unit/remote/index.js, test/unit/remote/watcher.js
Same convention everywhere:
- doc(s) for Metadata(s)
- remoteDoc(s) for RemoteDoc(s)
Motivations:
- Prevents confusion between doc (Metadata), remote (Side) or
file/dir/folder (?)
- Makes it easier to grep
- Allows using metadata module prefix
=> core: Rename all RemoteDoc/Metadata vars

dev/remote/generate-test-env.js
Some tests can fail if they run concurrently on 2 builds and the same
Cozy instance.
We've created a second Cozy instance dedicated to the AppVeyor builds
and we split those builds between the 2 to avoid these conflicts.
=> appveyor: Split builds between 2 Cozy instances

core/prep.js
Motivations:
- Keeps valid metadata construction in the same place
- It was not used anywhere else
=> core/prep: Merge#doMoveFile() method into #moveFileAsync()

CHANGELOG.md, package.json
- When a folder was moved on the Cozy or another device, the metadata of some
of its content was not updated properly, although the content was effectively
moved to the right place. Subsequent updates to these subfolders & subfiles
could then trigger unexpected conflicts. This should now work as expected. (#1274)
- When a file was effectively edited on 2 devices and the local one was detected
first, both were mistakenly renamed with a conflict suffix. Now only one of
them will be renamed. (#1285)
- Technical improvements for contributors
=> Release v3.10.3-beta.3

CHANGELOG.md, package.json
- The app is now available in spanish. Huge thanks to our translation
contributors, especially Hernando :heart:
- Files and directories can now only have one `-conflict-...` suffix at a time.
Existing ones with multiple suffixes won't be renamed automatically, but in
case a new conflict occurs, their suffixes will be squashed into a single
one with the new timestamp. Although this doesn't fix the root causes, it
should make the symptom easier to deal with. We're sill investigating the
underlying issues. Expect more fixes soon.
- We fixed a couple of issues preventing user-defined ignore rules to be
loaded.
- Files moved right after they've been added to the Cozy folder and before we've
had the chance to upload them will be synchronized anyway, at the right …
=> Release v3.10.3

core/local/chokidar_event.js, core/local/chokidar_watcher.js, test/integration/interrupted_sync.js
This PR includes and fix the test from #1235
=> Handle unapplied remote move - initialScan - sync

test/support/helpers/integration.js, test/support/helpers/local.js, test/support/helpers/remote.js
For cases where we didn't expect some conflicts in tests.
So we can see the actual conflict suffixes.
We tried to make the change minimal for other tests expecting
the original #tree() helper to be ellipsized.
=> test/support/helpers: Add unellipsized trees support

test/unit/pouch.js
So Pouch tests don't need it anymore.
=> test/unit/pouch: Use async/await instead of async module

core/merge.js, core/metadata.js, test/integration/move.js, test/unit/merge.js
When we move a directory during a synchronization phase, right after
adding some new files to it, those files don't get uploaded while they
remain in the renamed directory on the filesystem.
We mark the source file as never synchronized and its destination as new
so we don't try to move the source file and upload the destination
file instead.
=> core/merge: Synchronize childs of moved directory

test/support/builders/metadata/base.js, test/unit/merge.js
So builders don't force changed tags on docs built from existing ones.
Will make future Merge tests easier.
=> test: Extract MetadataBuilders#whateverChange() from constructor

test/unit/metadata.js
Since doctype doesn't matter in those tests.
And builders.whatever() is used, not .file().
=> test/unit/metadata: Rename file var to doc

core/metadata.js, test/unit/metadata.js
Some documents could be considered as different by the sameFile and
sameFolder functions if one of their properties was either null or
undefined on one document and absent (or just a different null value)
on the other document.
This could lead to the potential creation of conflicts since we
mutate document properties and can create a property with a null value
without changing anything else.
=> core/metadata: Null properties are same as absent

gui/elm/Ports.elm, gui/elm/Window/Tray.elm, gui/elm/Window/Tray/Settings.elm, gui/elm/Window/Tray/StatusBar.elm, gui/js/tray.window.js, gui/locales/en.json, gui/locales/es.json, gui/locales/fr.json, gui/ports.js
By adding a button in Settings, an end-user is able
to start a sync manually.
In the code, it is called `start-manual-sync` because
so many things are called `sync` with among others: 
updating the status of the synchronization, 
starting the synchronization of a file, 
the handler of the button that starts the synchronization of a file, etc.
=> feat: Start a sync manually

CHANGELOG.md, package.json
- You now have the opportunity to force a manual synchronisation from the
settings panel. This will be useful mostly to fetch some remote changes
without waiting for the periodic pull.
- Being always careful when it comes to your data, trying our best not to
lose any of it, when we try to reconciliate changes, we try to figure out
if the two documents we're comparing are the same. We were a bit too
conservative on this side and a lot of changes could lead to false conflicts
because of this. We're now doing a smarter comparison which should lead to
a lot less `-conflict-` documents being generated.
=> Release v3.11.0-beta.2

CHANGELOG.md, package.json
- We will now alert you when a new version of the app is available and give you
the option of restarting it to download and apply the new version or postpone
it.
- You now have the opportunity to force a manual synchronisation from the
settings panel. This will be useful mostly to fetch some remote changes
without waiting for the periodic pull.
- Being always careful when it comes to your data, trying our best not to
lose any of it, when we try to reconciliate changes, we try to figure out
if the two documents we're comparing are the same. We were a bit too
conservative on this side and a lot of changes could lead to false conflicts
because of this. We're now doing a smarter comparison which should lead to
a lot less `-conflict-` documents being generated.
- …
=> Release v3.11.0

dev/cozy-stack/Dockerfile
So corrupt file reupload tests work with docker-compose.
=> dev/docker: Update cozy-app-dev to 2018M4S3

.jq
- Singular, same as most of our filters
- Keeping only path/time is easy to do by hand
- Doing it by default sometimes makes the filter useless
=> jq: Rename conflicts filter to conflict & keep props [ci skip]

core/local/change.js, test/scenarios/add_delete_dir_and_file/local/linux.json, test/scenarios/move_dir_a_to_b_to_c_to_b/local/linux.json, test/scenarios/move_dir_a_to_b_to_c_to_b/scenario.js, test/scenarios/move_file_a_to_b_to_c_to_b/local/linux.json, test/scenarios/move_file_a_to_b_to_c_to_b/scenario.js, test/unit/local/analysis.js
Mark move changes as wip when we're adding an add event to them and
the underlying document does not exist anymore (happens in successive
moves for example).
This helps in managing a list of moves like A → B → C → B. The A → C
change would fail because C does not exist anymore and thus we wouldn't
aggregate the C → B move and instead treat it as an addition of B.
=> core/change: Detect & mark wip compound moves

CHANGELOG.md, package.json
- Moving a file or a folder multiple times in a row, synchronising them all at
once, ending on a path that was also an intermediary step (e.g. move document
A to B to C to B) would result in the synchronisation of the movement of the
file or folder to the last known path before the movement to the intermediary
step path and the addition of a new copy of the file or folder at the path
of the intermediary step (i.e. movement from A to C and addition of B). We now
correctly interpret those successive movements (i.e. movement from A to B).
=> Release v3.11.1-beta.1

test/support/helpers/scenarios.js
Hardcoding 0 was plain broken, triggering swallowed corrupt file errors.
The issue possibly didn't happen when file content was explicitely defined.
Also errors should definitely be explicit, but this will require more work
and should be fixed later in a separate commit.
=> test: Fix Metadata size in all scenarios

.appveyor.yml, dev/remote/generate-test-env.js
Our builds take more time with each test we add (especially
scenarios).
Besides, AppVeyor has a hard limit of 60 minutes per build that we've
finally reached.
Split our builds in two will give us some time to figure out how to
have shorter builds.
=> appveyor: Split build steps between 2 workers

.vscode/settings.json, core/merge.js, core/metadata.js, test/unit/metadata.js
The function were extracted to metadata.js,
then covered by tests.
=> fix: Use a RegExp to rename conflicting files

test/unit/remote/offline.js
This test can take more than 20 seconds which is the default timeout
for asynchonous mocha tests and leads to erratic behavior on our CI.
=> test/unit/remote/offline: Increase test timeout

dev/log2gource.js
Gource is a tool made for visualizing a repository (git, hg, svn, cvs)
evolution in time. It also accepts log in a custom format. I wanted to
try to visualize the logs from cozy-desktop with it, as a friday hack.
There is a script to do that. It looks beautiful (thanks to gource), but
I don't think it will really help us for debugging cozy-desktop. It's
here, just for the fun :-)
Gource: https://gource.io/
=> Add a script to visualize logs with gource

CHANGELOG.md, package.json
- Moving a file or a folder multiple times in a row, synchronising them all at
once, ending on a path that was also an intermediary step (e.g. move document
A to B to C to B) would result in the synchronisation of the movement of the
file or folder to the last known path before the movement to the intermediary
step path and the addition of a new copy of the file or folder at the path
of the intermediary step (i.e. movement from A to C and addition of B). We now
correctly interpret those successive movements (i.e. movement from A to B).
- Editing the content of a file just moved with one of its ancestor could lead
to the incorrect detection of a conflict with its remote couterpart. We're now
updating its content as expected and thus avoiding creating any …
=> Release v3.11.1

dev/elm.html, doc/developer/setup.md, gui/main.js, package.json
Elm windows do not need the whole app to start when they need works.
Here a fake HTML file is used to load elm windows and css and
it is served by a simple http server, so developers can see
their changes in milliseconds.
Here I added
- one HTML file for dev purpose
- an update in chokidar watch eventlistener
- a npm/yarn script to start the whole thing
- some documentation to explain what to do
=> core: Setup a dev env for Elm windows

core/app.js, core/local/chokidar_watcher.js, core/local/index.js, core/logger.js, core/pouch.js, dev/capture/local.js, dev/capture/remote.js, dev/chokidar.js, test/integration/conflict_resolution.js, test/integration/mtime-update.js, test/performance/local/watcher.js, test/regression/TRELLO_484_local_sort_before_squash.js, test/regression/TRELLO_646_move_overridden_before_sync.js, test/scenarios/run.js, test/support/coverage.js, test/support/helpers/TmpDir.js, test/support/helpers/config.js, test/support/helpers/context_dir.js, test/support/helpers/local.js, test/support/helpers/scenarios.js, test/unit/app.js, test/unit/config.js, test/unit/local/chokidar_watcher.js, test/unit/local/index.js, test/unit/metadata.js, test/unit/regressions/850.js, test/unit/remote/index.js, test/unit/utils/fs.js, test/world/case_and_encoding.js
So one can easily know whether she's using the standard Node.js `fs` module or `fs-extra` just by looking at the function prefix, e.g. `fs.rename(...)` vs `fse.rename(...)`.
Also we were uselessly using Bluebird to promisify `fs-extra` in a few places although it's already promisified by itself.
=> core: Alias fs-extra as fse everywhere & stop promisifying it

test/unit/local/analysis.js
To make it easier to see (e.g. using editor folding):
- which output cases are not covered yet
- for the same output, which input cases are not covered yet
Tests with more than 1 change as the output can still end up in their own group.
=> test/unit/local/analysis: Group tests by outputs & inputs

test/unit/local/analysis.js
So they match the values in real life.
So we can fix unwatched dir move + subfile update without breaking them.
=> test/unit/local/analysis: Fix md5sum in a few tests

core/local/analysis.js, core/remote/change.js, core/remote/watcher.js, test/scenarios/case_and_encoding/identical_additions/dir_file/win_mac/scenario.js, test/support/builders/index.js, test/support/builders/metadata/base.js, test/support/builders/metadata/file.js, test/support/builders/remote/base.js, test/support/builders/remote/dir.js, test/support/builders/remote/file.js, test/unit/remote/watcher.js
If a directory was moved remotely and overwrites an existing dir,
we would try to trash the destination and then make the move without
trying to overwrite any existing document at this path.
We're now ignoring the trash part since we'll overwrite the
destination and the move overwrites any existing document at the
destination path.
To test this with a real case scenario, comment out the `side` line of
the `test/scenarios/move_overwriting_dir/scenario.js` file and run
this test.
It might not pass right away as remote scenario tests are a bit
unpredictable but should pass eventually.
=> core/remote/watcher: Remote overwriting dir moves

CHANGELOG.md, gui/locales/es.json, package.json
- We've improved the wording of the updater window so it says it's downloading
the new version and displays the Cozy Cloud logo so you know what's being
updated at first glance.
- If a directory is overwritten by a move on your Cozy, we would move it to the
trash and, in some situations, after synchronising your local client, the
directory would not be overwritten on your computer. We're now skipping the
move to the trash and overwriting the directory.
=> Release v3.11.2-beta.1

core/merge.js, core/metadata.js, core/sync.js, test/unit/pouch.js, test/unit/sync.js
Marking a file or directory as unsyncable (previously "never synced")
should not add a new side to the metadata, especially when not syncing
a local document as this can lead to errors with documents not having
a remote object but a remote side.
We now simply mark the document for deletion, increase its existing
side and save it to the Pouch.
The Sync component is now responsible for not synchronising deleted
documents with only one side.
=> core/metadata: Don't add side when not syncing doc

core/local/atom_watcher.js, core/local/steps/add_checksum.js, core/local/steps/add_infos.js, core/local/steps/dispatch.js, core/local/steps/event.js, core/local/steps/initial_diff.js, core/local/steps/linux_producer.js, core/local/steps/producer.js, core/local/steps/scan_folder.js, core/local/steps/win_producer.js, test/generate_property_json.js, test/property/local_watcher/index.js, test/property/local_watcher/keyboard_rubber.json
When a directory is moved from outside the synchronized directory to it, atom/watcher gives us only one event (the directory was added), and it's our job to scan it to add the files and sub-directories inside it.
=> Detect moves from outside the sync dir

core/merge.js, test/integration/conflict_resolution.js, test/unit/merge.js
When we have fetched a remote change and failed to apply it, we end up
with a remote side superior to our local side.
If in this situation we try to merge a local change, we'll try to
resolve the conflict remotely and end up renaming the existing file
with the conflict suffix and potentially lose the local data after
successfully applying the remote changes.
We can avoid this situation by doing a local conflict resolution,
ensuring we have both the existing file and its conflicting copy.
This has the additionnal advantage of keeping potential sharings of the
remote file clean.
=> core/merge: Local change & unapplied remote change

CHANGELOG.md, package.json
- We've improved the conflict resolution after changes made to local files when
the client was stopped. In this situation, we would resolve the conflict on
the remote Cozy and end up renaming the local copy with the `-conflict-`
suffix and could overwrite its content with the remote content thus losing
the latest local changes.
We're now resolving the conflict locally, keeping the remote version
untouched. This has the additionnal benefit of keeping shared files free from
the `-conflict-` suffix.
- A function we introduced in version 3.11.0 was responsible for an increase in
false negatives for an invariant check, leading to errors being thrown and
synchronisations blocked.
We've reworked said function in a way that won't trigger false negatives for
the …
=> Release v3.11.2-beta.2

CHANGELOG.md, package.json
See [3.11.2-beta.1](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.11.2-beta.1)
See [3.11.2-beta.2](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.11.2-beta.2)
- We've improved the wording of the updater window so it says it's downloading
the new version and displays the Cozy Cloud logo so you know what's being
updated at first glance.
- If a directory is overwritten by a move on your Cozy, we would move it to the
trash and, in some situations, after synchronising your local client, the
directory would not be overwritten on your computer. We're now skipping the
move to the trash and overwriting the directory.
- We've improved the conflict resolution after changes made to local files when
the client was stopped. In this situation, we would …
=> Release v3.11.2

dev/capture/remote.js, test/scenarios/add_delete_dir_and_file/scenario.js, test/scenarios/add_file/scenario.js, test/scenarios/add_trash_file/scenario.js, test/scenarios/case_and_encoding/identical_additions/complex_dirs/actions.js, test/scenarios/case_and_encoding/identical_additions/dir_file/linux/scenario.js, test/scenarios/case_and_encoding/identical_additions/dir_file/win_mac/scenario.js, test/scenarios/change_file/scenario.js, test/scenarios/index.js, test/scenarios/move_and_update_file/scenario.js, test/scenarios/move_dir_and_update_subfile_remotely/scenario.js, test/scenarios/replace_dir_with_file/scenario.js.DISABLED, test/support/helpers/scenarios.js
- `>` becomes `create_file` (same a property-based tests)
- `>>` becomes `update_file` (same a property-based tests)
- `update_file` explicit `content` is now mandatory (makes scenarios easier to understand and remote instrumentation doesn't need to download previous content anymore)
=> test/scenarios: create_file & update_file actions

core/local/steps/event.js, test/support/builders/atom_watcher_event.js, test/support/builders/index.js
This builder follows the same principles as the metadata and remote
builders to create AtomWatcherEvent objects.
Some types and constants used in AtomWatcherEvent were exported for
consistency.
=> test/support: Add AtomWatcherEvent builder

core/local/change.js, core/local/chokidar_event.js, core/local/event.js, core/path_restrictions.js, core/remote/change.js
To make future changes easier to review.
This commit includes only indentation changes, nothing else.
=> core: Indent flow type definitions

core/local/analysis.js, core/local/change.js
Flow typechecking is terribly inaccurate in `local/analysis` & `local/change`.
The `change.fromEvent()` function in particular is messing up flow in unexpected ways.
For example, it prevents using the `?: ...` syntax (vs `: ?...`) in a few type definitions.
Replacing it with dedicated builders is a first necessary step to regain sanity.
The builders currently include some duplication.
But this should be easy to DRY later, once the code is more reliable.
Also the `LocalFileAddition` type is currently lying: `md5sum` is missing when `wip` is `true`.
Fixing it will require quite more work, hence the temporary `delete md5sum` hack when a file
is added then unlinked.
=> core/local: Replace change.fromEvent() with dedicated builders

core/ignore.js, core/local/steps/filter_ignored.js, core/metadata.js, core/prep.js, core/sync.js, test/unit/ignore.js, test/unit/metadata.js
We're starting to use Ignore#isIgnored with different types of
"documents" (i.e. Metadata and AtomWatcherEvent) while they don't all
have the expected `_id` and `docType` properties.
Since those 2 properties are the only information we need to decide
whether a "document" should be ignored or not, we can request them as
parameters so their values can be computed correctly by the caller
depending on the type of "document" it's dealing with.
Also, since we'll move to the new Atom Watcher, we'll use its
EventKind type instead of the current DocType type to determine
whether the given "document" is a directory or not.
To help transition to the new format, we replace all calls to
isIgnored for Metadata objects with calls to a new method
isIgnoredDoc which uses isIgnored internally and maps the …
=> core/ignore: Change isIgnored signature

core/config.js, test/unit/config.js
The constructor ensures the config file exists, even if empty.
So ending up with a JSON.parse error because it is, then deleting it
doesn't really make sense...
Also logging a harmless error didn't help debugging.
=> core/config: Fix harmless error on load

core/local/analysis.js
This refactoring is a first necessary step to simplify the deeply nested conditionals in analysis (in upcoming #1396). The values newly accepted by `changeFound()` feel a bit weird, but this will be improved in a subsequent PR (they will either be replaced by something more meaningful, or dropped because not necessary anymore).
Please see commit messages for the motivation behind each change.
=> core/local/analysis: Intermediate refactoring

core/local/analysis.js, core/local/change.js
The local changes analysis includes a succession of detection steps for each event type.
This was previously implemented as if/else statements nested into a switch/case one + block statements.
The goal here is to turn this into plain function chaining using `or` (`||`) expressions.
Requires #1395.
More improvements can be done later but are **out of the scope** of this already big PR:
- Extracting the remaing *panic* blocks as `ensure*()` function calls.
- Extracting the `switch/case` block into a separate function returning the detection result instead of calling `changeFound()` directly
- Extracting some kind of `ChangeMap` class
- Improve naming
- Introduce chokidar watcher steps, same as in the atom watcher
=> core/local/analysis: Conditionals refactoring

test/unit/local/steps/linux_producer.js
This PR aims to cover `core/local/steps/linux_producer.js`.
It uses temporary folder to create folders and files in an asynchronous mode.
I tried to stay clear by reducing variable declaration, but let me know if reviewers think it will be clearer to name variable.
=> test: Cover linux_producer with tests

package.json
Since atom is not supported yet.
So `yarn test:scenarios` doesn't fail locally on GNU/Linux & Windows.
=> yarn: Ensure test:scenarios run with chokidar, not atom

core/local/steps/initial_diff.js, test/support/builders/atom_watcher_event.js, test/support/builders/index.js, test/support/builders/metadata/base.js, test/unit/local/steps/initial_diff.js
To avoid processing a `scan` event following the transformation of a
`created` event into `renamed` event, we wait before passing it along
to the next step and remove any `scan` event for the same path.
=> core/local/steps/initial_diff: Cover basic cases

test/support/helpers/context_dir.js
Which is a promisified version of the standard fs.rename().
While fs-extra's move() is definitely not the same:
- It is doing some magic to allow moving accross separate volumes.
- It may change the inode unnecessarily
- We use fse.rename() in Local writer, so better match our own actions
Extracted from https://github.com/cozy-labs/cozy-desktop/pull/1334.
Courtesy of @aenario.
=> test/support/helpers/context_dir: Use fse.rename()

core/local/watcher.js
For release purpose. To be reverted later.
=> core/local/watcher: Temporarily use chokidar on all platforms

test/support/builders/atom_watcher_event.js, test/support/builders/metadata/base.js
Instead of normalising the paths in every test using a builder we can
do it in the builder itself.
This is necessary for some tests to pass on all platforms.
=> test/support: Normalise paths in builders

core/merge.js, core/metadata.js, test/integration/update.js, test/support/builders/metadata/base.js, test/unit/merge.js
When moving a document as part of a parent move, we create a new
document in Pouch and have therefore a new `_rev` starting with 1.
Thus, we should have clean sides with only one side set to 1.
=> core/merge: Reset child move destination sides

CHANGELOG.md, package.json
- We keep track of the changes made to documents to synchronise either with the
remote Cozy or the local filesystem using version numbers for each side of the
synchronisation. When moving a document, be it either a directory or a file,
on the local filesystem as part of its parent directory move, the new local
version number would be false, resulting in a possible desynchronisation of
content updates.
We now make sure both the local and remote version numbers get resetted in
this situation so future updates will be synchronised in the right direction.
=> Release v3.12.0-beta.2

core/pouch.js, test/support/builders/metadata/base.js, test/unit/merge.js
Based on #1423 
When we were building documents using the metadata builders and
setting their sides, we would not necessarily have a coherent
revision (i.e. as high as the highest side).
We now save the document until the revision is at least as high as the
highest side we're setting.
=> test/support/builders/metadata: _rev matches sides

core/local/change.js, core/local/chokidar_watcher.js, core/merge.js, core/move.js, core/sync.js, test/scenarios/rename_subdir_after_parent/local/linux.json, test/scenarios/rename_subdir_after_parent/local/win32.json, test/scenarios/rename_subdir_after_parent/scenario.js, test/unit/merge.js
When renaming a sub-directory of a directory renamed in the same
synchronisation loop, we missed two updates to the source directory:
- one local update when we merge the renaming of the parent directory
which triggers changes on its children (i.e. the local side and
revision were updated and merging the sub-directory change would
trigger a Pouch conflict)
- one remote update when we synchronise the renaming of the parent
directory with the remote Cozy and it does the thing that we do with
the local Pouch document (we could then not update the remote
sub-directory as its revision had changed)
To avoid those issues, we refetch the local document right before
merging the sub-directory renaming and the remote revision right
before synchronising it.
Please make sure the following boxes are …
=> Update revisions of renamed subdir of renamed dir

core/merge.js, test/integration/update.js, test/unit/merge.js
When creating a document with an id that has already been used and
deleted, PouchDB will reuse its rev. This means our new documents
won't have the expected short rev number of 1 and their sides won't
match it.
Whenever we create new documents in Merge, we make sure their sides
are updated to match the actual revision if it has been reused.
Since we might call the fix on the source of movements or an existing
directory document, we only fix documents which didn't have a rev when
calling the Pouch method (i.e. we are creating them).
=> core/merge: Fix sides after pouch rev reuse

CHANGELOG.md, package.json
- We've modified the way we handle child documents updates so everything gets
synchronised, even if a child update occurs quickly after its parent directory
has been renamed.
- We found out that creating or moving a file or a directory to a path that has
already been used in the path then deleted could lead to unrelevant version
numbers for the new document and in the end to unnecessary conflicts.
We now correct our version numbers when this situation happens so future
updates to the document are handled correctly.
=> Release v3.12.0-beta.3

core/merge.js, core/metadata.js, test/support/builders/metadata/base.js, test/unit/local/index.js, test/unit/merge.js, test/unit/metadata.js
`buildFile` and `buildDir` were using Date objects for the
`updated_at` attribute of the Metadata object they're building.
This leads to a comparison nightmare in tests as we some times have a
Date object and some times have an ISO string representation of this
date.
Forcing it to an ISO string in the builder solves this issue.
=> core/metadata: Use ISO string dates in builders

core/local/steps/incomplete_fixer.js
Otherwise it definitely won't work on Windows.
This part still needs unit tests anyway (planned in the current iteration), but since we're currently doing manual testing, better catch more complex issues than this one.
=> core/local/steps/incomplete_fixer: Fix path separator

CHANGELOG.md, package.json
**Notice:** This release uses the new watcher by default on Windows and
GNU/Linux for testing purpose only and should not be used in other situations.
- Fixed a race condition case were a sharing could be disabled when a folder
was moved locally while another one was added remotely to the same
destination.
- The right path separator is now used while squashing successive events (e.g.
file added or updated, then moved immediately) in the new watcher.
Happy syncing!
=> release: 3.12.1-alpha.1

core/config.js, core/local/index.js, core/local/watcher.js, test/unit/config.js
To simplify testing the new local watcher using Atom Watcher behind
the scenes, we move the choice of watcher to the Config.
If a `watcherType` property is defined in `config.json`, we use it,
otherwise we set with the 2 mechanisms that already existed (i.e. user
defined watcher via env variable then platform default watcher).
=> core/local/watcher: Get watcher type from Config

CHANGELOG.md, package.json
- The watcher type used (i.e. atom or chokidar) can now be chosen via the config
file. This means the new watcher will be testable easily with any version of
the app starting from now.
=> Release 3.12.1-beta.1

core/local/analysis.js, core/local/change.js
Some functions that build `LocalChange`s may handle many edge cases and return different change types. This makes it harder to understand them & to add type annotations (flow errors end up being quite hard to understand/debug).
=> core/local: Single type change builders

test/support/builders/metadata/base.js, test/support/builders/metadata/file.js, test/unit/merge.js
In the metadata module, when building a file or a directory, we use an
optional `remote` parameter to fill in the `remote` attribute of the
`Metadata` object being built. The way it is done, if the parameter is
not passed, we end up with a `remote` attribute with an `undefined`
value instead of not having the parameter at all.
Also, when building a directory, we set the `sides` attribute to an
empty object instead of not having an attribute at all like we do when
building a file.
The metadata's `buildFile` method creates documents with a class and
mime attributes which are missing from the metadata test builders thus
preventing us from comparing them with documents from test builders.
=> test/support/builders/metadata: Match implementation

core/merge.js, core/move.js, test/unit/merge.js, test/unit/move.js
When moving a file or directory, we delete the source document and
create a new one in Pouch.
This new document should only have one side, the one from which the
document was created, and its version should be 1 since this is a new
document (n.b. it can end up being higher if the path is being reused
and we're fixing the sides later).
We were doing this reset in some situations only. Now, we do it as
part of the `move` call so it's done in every move.
=> core/merge: Reset sides on every move

core/merge.js, test/unit/merge.js
Since move source & destination sides are already handled in `core/move`.
Completing [#1440](https://github.com/cozy-labs/cozy-desktop/pull/1440).
Courtesy of @taratatach.
=> core/merge: Don't mark sides already handled by move()

test/support/builders/atom_watcher_event.js, test/unit/local/steps/initial_diff.js
Passing `fs.Stats` objects to build or modify a test object can be
cumbersome as it requires a lot of attributes to be set to match the
objects that will really be built by the production code.
Most of the time, when building test AtomWatcherEvents, we only want
to set the `ino` property so we remove the `stats` method and add a
new `ino` method on the test builder. The `stats` property of the
event is managed by the builder.
=> test/support/builders/atom_watcher_event: No stats

core/local/steps/buffer.js, core/local/steps/dispatch.js
By using an `asyncMap` instead of an `asyncForEach` and by returning
the resulting buffer, we can detect the end of a batch processing from
the caller of the step.
This is very useful to test the step in isolation.
The Buffer's `forEach` and `asyncForEach` methods are not used at all or not
any more so we can remove them.
=> core/local/steps/dispatch: Detect end of batch

core/merge.js, test/unit/merge.js
When trying to merge a remote file update which results in a conflict
resolution, we dissociate the untouched local document from the remote
version.
When doing so, we're actually saving a new version of the document in
Pouch which will result in a `_rev` increase and should therefore
result in a local side increase as well.
=> core/merge: Fix side after remote dissociation

core/app.js, core/config.js, core/local/index.js, core/local/watcher.js, core/pouch.js, core/prep.js, core/remote/cozy.js, core/remote/index.js, test/support/helpers/config.js, test/support/helpers/integration.js, test/unit/config.js
So we can reuse the extracted `.watcherType()` function to support
AtomWatcher in scenarios/captures.
Also make sure env-based unit test won't break as soon as we change
the default watcher.
=> core/config: Separate class/module, refactoring, new functions & flow types

core/merge.js, test/support/builders/metadata/base.js, test/support/builders/metadata/file.js, test/unit/merge.js
Needs #1444 
Every test now takes documents built using the test builders and
compare the side effects of the merge methods with expected side
effects.
Those changes make clear what changes we expect from each method down
to every document attributes.
=> test/unit/merge: Check side effects in every tests

test/support/builders/metadata/base.js, test/unit/local/steps/dispatch.js
Based on #1399 
We make sure that only the expected Prep methods are called for each
combination of event action and kind and that they receive the
expected parameters.
Some changes were made to `core/local/steps/dispatch` to help test it in isolation.
By using an `asyncMap` instead of an `asyncForEach` and by returning
the resulting buffer, we can detect the end of a batch processing from
the caller of the step.
=> test/unit/local/steps/dispatch: Cover all events

dev/repl.js, test/integration/add.js, test/integration/case_or_encoding_change.js, test/integration/conflict_resolution.js, test/integration/corruption_fixer.js, test/integration/executable.js, test/integration/full_loop.js, test/integration/id_conflict.js, test/integration/interrupted_sync.js, test/integration/move.js, test/integration/mtime-update.js, test/integration/permanent_deletion.js, test/integration/platform_incompatibilities.js, test/integration/sync_state.js, test/integration/trash.js, test/integration/update.js, test/regression/TRELLO_484_local_sort_before_squash.js, test/regression/TRELLO_646_move_overridden_before_sync.js, test/scenarios/run.js, test/support/helpers/index.js, test/unit/scheduling.js
- Replaces `new IntegrationTestHelpers()`
- May end up as a facade (similar to Builders)
- Stop pretending cozy client must be injected (may be improved later)
- Instanciation is an implementation detail
- So we can later introduce new factory functions depending on the context
---
=> test: Introduce TestHelpers.init

test/unit/scheduling.js
- `Promise.delay()` requires bluebird
- `Sync#start()` takes a mode (although `undefined` happens to work the same as `full`)
---
=> test/unit/scheduling: Enable flow & fix minor issues 

core/app.js, core/local/index.js, core/local/watcher.js, core/remote/index.js, test/property/runner.js, test/support/helpers/index.js, test/unit/local/index.js, test/unit/remote/index.js, test/unit/remote/offline.js
- No need to remember params order anymore
- Makes it easier to add new options
---
=> core: Introduce options for Local, LocalWatcher.build & Remote

core/config.js
We pass the process as the second parameter when calling
`config.watcherType` but this param is destructured to extract its env
and platform attributes.
We should be using those in the function body instead of the `process`
attributes directly (so we can pass different values in tests).
=> core/config: watcherType uses env and platform params

test/unit/local/steps/buffer.js
We were not yet ensuring that `#asyncMap()`) was properly awaiting the given transform.
=> test/unit/local/steps/buffer: Test ordering

.appveyor.yml, core/config.js, dev/ci/scenarios.sh, test/unit/config.js
Except on macOS where the default is still chokidar.
This is a temporary change that will be reverted, to make testing easier.
But it will soon make its way into production.
It is expected to break the CI, so we can progressively merge the required fixes.
=> core/config: Default to atom watcher

core/local/steps/await_write_finish.js, core/local/steps/buffer.js, core/local/steps/initial_diff.js, test/unit/local/steps/buffer.js
No need to pass them around and run useless code.
=> core/local/steps/buffer: Drop empty batches

core/ignore.js, test/unit/ignore.js
On Windows, the various `path.*()` functions don't play well with
relative paths where the top-level file or directory name includes a
forbidden `:` character and looks like a drive letter, even without a
separator. Better make sure we don't end up in an infinite loop.
---
=> core/ignore: Don't confuse relative path with Windows drive letter

test/support/helpers/index.js
Otherwise tests will fail with AtomWatcher since it doesn't have
an `ignored` option like chokidar.
This doesn't prevent us to keep using the chokidar option.
Courtesy of @taratatach.
**Needs #1476**
---
=> test/support/helpers: Load default ignore rules

test/scenarios/run.js, test/support/helpers/scenarios.js
Will fix 9 scenarios on Windows with new atom watcher.
=> test/support/helpers/scenarios: .init() fileid support

core/local/atom_watcher.js, core/local/steps/initial_diff.js, test/unit/local/steps/initial_diff.js
Before starting the producer and looping over events, we initialize
the state of the steps that need one so this can be done whenever we
restart the watcher.
This is useful for the initialDiff step for example since it needs to
build a map of the existing documents to detect deletions and moves
that can have occurred while the watcher was stopped.
=> core/local/atom_watcher: Initialise steps' states

core/local/atom_watcher.js, core/local/steps/initial_diff.js, core/local/watcher.js, dev/capture/local.js, test/unit/local/atom_watcher.js
Modulification was needed so we can export the function.
So we can test it.
So we can reproduce the issue.
So we can fix it.
=> core/local/atom_watcher: Modulify & fix .stepsInitialState()

core/merge.js, test/integration/conflict_resolution.js
Was #1416 / commit 3971c0ef35fc710a662666ef7964a2bd21715531.
For some edge cases, the result is worse than without the fix.
We don't have time to investigate yet, so better revert & bring it back later.
=> core/merge: Revert dir local move + remote add = conflict

.jq, core/local/atom_watcher.js, core/local/steps/add_checksum.js, core/local/steps/add_infos.js, core/local/steps/await_write_finish.js, core/local/steps/dispatch.js, core/local/steps/incomplete_fixer.js, core/local/steps/linux_producer.js, core/local/steps/scan_folder.js, core/local/steps/win_detect_move.js, core/local/steps/win_producer.js
- Prefix loggers with `atom/`
- Ensure no error is swallowed
- Handle .event|.path in jq's path() filter
- Fix *experimental* wording
- Log expected/ignorable errors at the debug level
- Log non-critical but unexpected ones at the warn level
- Make sure event and other useful data are logged when available
- At least log path whenever possible if no event is available
- Use logger instead of console.log()
- Remove useless $FlowFixMe notice
- Don't return log.error() result in callback
=> core/local: Improve logging in atom watcher & steps

core/local/steps/initial_diff.js, test/unit/local/steps/initial_diff.js
Generate a `deleted` event for a document whose associated file is
missing only if there is no other document at the same path.
Otherwise we won't create a document for the new file.
=> core/local/steps/initial_diff: Detect path reuse

test/integration/scheduling.js
It is not a unit test since it tests many components together.
Also fixed test name to match file & to prevent confusion with Sync unit tests.
=> test: Reclassify ./unit/scheduling as ./integration/scheduling

test/support/helpers/local.js
Fixes `TypeError: Cannot match against 'undefined' or 'null'` everywhere
when running scenarios with atom watcher/captures.
Thanks @taratatach for identifying the issue!
Requires checking the watcher type to make flow happy.
The `$FlowFixMe` notice is still needed because of the magic batch.
=> test/support/helpers/local: Fix atom steps init in #simulateAtomEvents()

core/config.js
Fixes flooding useless error messages in test logs.
=> core/config: Only log watcher type as invalid when it is actually set

test/support/helpers/scenarios.js
The new atom watcher doesn't generate/handle events the same way on
Windows and GNU/Linux, so better not mix captures & platforms.
=> test/support/helpers/scenarios: Enable atom captures for current platform only

core/local/steps/incomplete_fixer.js, test/support/builders/atom_watcher_event.js, test/unit/local/steps/incomplete_fixer.js
Minimal builders change + `.loop()` test (nominal case) so we can extract `.step()` and test it more thoroughly without having to deal with buffers.
The code was carefully refactored in order not to conflict with upcoming #1494.
Also, although it will conflict, rebasing #1487 should be relatively easy too.
=> core/local/steps/incomplete_fixer: Extract .step()

test/support/logging.js
We didn't use CI logs dump for a long time.
We can still bring it back later if needed.
But not seing underlying errors was an issue, though.
---
=> test/support: Always log errors & drop CI dumps

.appveyor.yml, core/config.js, dev/ci/scenarios.sh, test/unit/config.js
=> core/config: Default to atom watcher 

core/local/steps/add_checksum.js, core/local/steps/add_infos.js, core/local/steps/await_write_finish.js, core/local/steps/dispatch.js, core/local/steps/filter_ignored.js, core/local/steps/incomplete_fixer.js, core/local/steps/initial_diff.js, core/local/steps/linux_producer.js, core/local/steps/scan_folder.js, core/local/steps/win_detect_move.js, core/local/steps/win_producer.js, test/unit/local/steps/await_write_finish.js, test/unit/local/steps/incomplete_fixer.js, test/unit/local/steps/initial_diff.js
- Unify STEP_NAME's
- Aggregate event context instead of logging it along the way to make
it easier to read, to follow and to understand
- Log at the dispatch step only to limit the amount of log lines
=> core/local/steps: Improve Atom Watcher logs

CHANGELOG.md, package.json
- The new local watcher is now the default watcher. It should bring better
performance in local changes analysis.
- Files and folders named like a volume (e.g. C:) and at the root of the folder
watched by Cozy Desktop could lead to an infinite loop if they or any of their
children were ever modified. Those are now handled properly and won't be
ignored either.
There are some known issues that we'll tackle in the next releases:
- On Windows, moving the child of a moved directory won't be handled properly.
- On Windows, moving a tree of directories and files to a destination that
shares part of this tree (e.g. `src/dir/subdir/file` → `dst/dir/subdir/file`)
and overwriting the destinations will result in conflicts being …
=> Release v3.13.0-alpha.1

core/local/steps/incomplete_fixer.js, test/unit/local/steps/incomplete_fixer.js
When rebuilding an incomplete event, if the completing event and the
rebuilt one share the same path, we should completely replace the
completing event since it's now obsolete.
=> core/local/steps/incomplete_fixer: Overwrite event

core/local/steps/event.js, core/local/steps/linux_producer.js
Type was fs.Stats instead of `fs.Stats|WinStats`.
=> core/local/steps: Fix AtomWatcherEvent#stats type

core/local/steps/linux_producer.js, core/local/steps/win_producer.js
At least temporarily, until we're confident enough to remove it.
I feel like we could regret not having them while debugging.
=> core/local/steps: Log batches in producers

test/integration/corruption_fixer.js
This test is failing due to the new in-memory cache in cozy-stack:
https://github.com/cozy/cozy-stack/commit/581ba9ccbe33475f1dd68bbc2f0f85c8d4ea89e5
The corruption fixer is in production since 5 months, so it is probably
not fixing a lot of files anymore & may be dropped soon.
Courtesy of @taratatach
=> test/integration/corruption_fixer: Disable test

core/local/steps/incomplete_fixer.js, test/support/helpers/context_dir.js, test/unit/local/steps/incomplete_fixer.js
- When rebuilding a `renamed` event in incomplete_fixer, we can end up
with a `renamed` event with equal path and oldPath which is invalid
and will raise an error at the Merge level.
We can avoid processing it altogether by dropping it.
- When rebuilding an event, if the destination `path` does not exist
anymore, trying to get its stats will raise an ENOENT error.
This path is also the path of the completing event.
To avoid raising useless errors (i.e. if we don't have a file or
directory at the given path, we don't need a rebuilt event), we catch
that error when rebuilding the event and don't return any.
Also, to avoid keeping events about files or directories that don't
exist anymore, if we don't have a rebuilt event we drop the completing
event.
Please make sure the following boxes are …
=> core/local/steps/incomplete_fixer: Avoid rebuilt event errors

test/support/builders/atom_watcher_event.js, test/support/builders/metadata/base.js, test/support/builders/stats.js, test/unit/local/steps/initial_diff.js, test/unit/merge.js
**Needs #1504**
Introduces new `StatsBuilder`.
Which builds `WinStats` & generates fileids from test inode numbers.
So we can reuse it in `AtomwatcherEventBuilder` & `BaseMetadataBuilder`.
And make sure our test data actually match our production data.
Since fileids have more precision than inode numbers, it could make sense to
generate inode numbers from fileids instead of the opposite.
But the current way prevent breaking many tests.
And the other one would mostly be relevant to test precision issues.
Which we don't test yet anyway.
=> test/support/builders: Use realistic test stats

core/local/stater.js, core/local/steps/incomplete_fixer.js, test/unit/local/steps/incomplete_fixer.js
Based on #1501 
When we move a file twice in a row, we would not complete the event
correctly and end up with C→D instead of A→D. Therefore, we wouldn't
be able to merge the move.
To handle this case, we go over incomplete events to complete other
incomplete events (e.g. B→C will complete A→B) but in such cases, the
rebuilt event will be marked as incomplete as well and will be offered
for completion later on.
A side effect of this fix is to drop useless complete events (e.g.
deleted event for A when we completed A→B with deleted B).
=> core/local/steps/incomplete_fixer: Handle A→B→C→D

core/local/steps/win_detect_move.js, test/unit/local/steps/win_detect_move.js
**Needs #1505**
It would be interesting to isolate the various side-effects (existing
metadata lookup, timeouts...) and identify their possible combinations
with the correponding race conditions. But this may require quite a lot
of refactoring. So this PR only test event combos, not timing. Still
better than nothing.
Extracted a few functions from implementation.
Also fixed a circular reference in debug data attached to events.
=> core/local/steps/win_detect_move: Test & refactor

core/local/steps/add_checksum.js, core/local/steps/initial_diff.js, test/support/builders/atom_watcher_event.js, test/support/builders/stats.js, test/unit/local/steps/add_checksum.js, test/unit/local/steps/initial_diff.js
When an event matches an existing document's ino, path and last update
time, we can safely assume the checksum hasn't changed and set it on
the event.
When an event already has a checksum, it's not necessary to recompute
it in this step.
This will speed up the initial scan by avoiding lots of checksum
computations.
=> Avoid recomputing checksums

core/metadata.js, test/support/builders/metadata/base.js, test/unit/metadata.js
Otherwise .markSide() will mess up because sides != null.
=> core/metadata: Fix .buildDir() sides

dev/ci/tests.sh, test/integration/interrupted_sync.js
=> ci/travis: Run integration tests with atom watcher on Linux

test/support/builders/atom_watcher_event.js
So atom event ids are normalized the same way as paths in tests.
=> test/support/builders/atom_watcher_event: Fix #path()

core/local/steps/event.js, core/local/steps/producer.js, test/integration/mtime-update.js, test/scenarios/run.js, test/support/helpers/local.js
So initial diff doesn't end up with state before initial scan while
we're testing live captures in scenarios.
---
=> test: Fix scenarios initial diff state issue

CHANGELOG.md, package.json
- Successive moves (e.g. A → B → C → D) are now correctly applied (i.e. A → D)
with the new local watcher.
- The introduction of the new local watcher brought a performance regression
during the initial Cozy directory scan. We ported an optimisation we had in
the previous watcher to the new one which should make the initial scan phase
about 3x faster.
- We found a bug in the synchronisation process of directories that could lead
to missed updates. We have not seen any reports of it but the mechanism has
been fixed anyway.
- We updated one of our main dependencies, Electron, to its 2.x version. We are
still not using the latest version but this one brings us back support from
the Electron team and security fixes. Other updates will come in the …
=> Release v3.13.0-alpha.2

test/scenarios/create_dirs/atom/linux.json
The capture contained events for files while we are actually creating
directories.
This lead to errors raised in the addChecksum step.
=> test/scenarios/create_dirs: Fix linux Atom capture

CHANGELOG.md, package.json
- Changing only the case of a file/directory name now works as expected when
using the new watcher.
Happy syncing!
=> release: v3.13.0-alpha.3

core/local/steps/producer.js, test/unit/local/steps/producer.js
A race condition could occur between readdir and stat in
producer.scan().
If the listed item is deleted before we can get its stats, we now
issue an incomplete scan event instead of logging an error, thus
avoiding possible deletion of the document via the deleted event
issued by initialDiff and then recreation via the renamed event issued
later by the producer (possibly aggregated by winDetectMove).
Greatly helped by @sebn 	
=> core/local/steps/producer: Fix incomplete scan race condition

core/merge.js, core/metadata.js, core/sync.js, test/unit/merge.js, test/unit/metadata.js
=> core/merge: Save missing fileids on up-to-date scanned docs 

CHANGELOG.md, package.json
- With the new local watcher, we introduced a more precise way to identify files
and folders on the filesystem. To make sure previously detected documents
benefit from this new identification we need to migrate all of them when we
get the new identifier. This version takes care of the migration in a way that
avoids running a full synchronisation when we only change the identifier as it
has value on the local client only.
There are some known issues that we'll tackle in the next releases:
- On Windows, moving a tree of directories and files to a destination that
shares part of this tree (e.g. `src/dir/subdir/file` → `dst/dir/subdir/file`)
and overwriting the destinations will result in conflicts being created for
the overwritten files.
- On Windows, the …
=> Release v3.13.0-beta.2

core/local/steps/dispatch.js
To prevent Merge/Sync conflicts.
This will probably make performances worse.
Sync should probably lock around single changes, not batches.
---
=> core/local/steps/dispatch: Lock around event dispatch

CHANGELOG.md, package.json
- Rapid successive changes on the same file were possibly generating conflicts
because the new watcher was messing up with the changes propagation. There
were actually 2 underlying issues behind this: one that was specific to the
new watcher and another that was not. We actually fixed both, although the
second one was not supposed to happen anymore once the new watcher would
behave correctly, but could still have been uncovered during upcoming
optimizations.
Happy syncing!
=> release: 3.13.0-beta.3

core/metadata.js, test/unit/metadata.js
Do not mistake a previous conflict timezone for a file extension.
---
=> core/metadata: Fix previous dir conflict suffix

CHANGELOG.md, package.json
- We recently fixed an issue we had in the generation of a conflict file name
where the conflict suffixes could be added indefinitely in case the
conflicting file would get in conflict again. It happens that directories are
still subject to a similar issue.
We made sure directories will only ever have one conflict suffix added to
their name event in case they get in conflict again.
- During the synchronisation process, a document can change either locally
(e.g. its checksum has changed because of a modification) or on the Cozy
(e.g. the file was moved or modified by another client). In this situation the
Cozy won't accept the change and will answer with an error. When we receive
errors from the Cozy we retry up to 3 times to apply the change …
=> Release v3.13.0-beta.4

core/local/steps/await_write_finish.js, test/unit/local/steps/await_write_finish.js
The step would only work if the first event on which we'll aggregate
others was in a previous batch.
If a lot of writes happen quickly we'll see batches of modified
events for the same file / directory and we want to aggregate those
to limit the number of changes to merge and sync.
To do that, we go over the events of the current batch and aggregate
them before trying to aggregate them with waiting events.
=> core/local/steps/await_write_finish: Aggregate in batch

core/local/steps/initial_diff.js, test/integration/interrupted_sync.js, test/unit/local/steps/initial_diff.js
If a document was moved remotely and we merged the change but did not
get to apply it locally (e.g. the client was stopped during the
process), we will receive scan events for the source of the move when
we start the client again (i.e. the file has not been moved).
If we let those scan events go all the way to dispatch, we'll end up
creating a new document remotely with the source of the previous move
(i.e. the source document does not exist in pouch anymore so we can
know it's been moved during Merge).
To avoid this, we ignore those events if we can find a document with
the same kind and ino during the initial diff and that document has a
movement marker (i.e. moveFrom).
=> core/local/steps/initial_diff: Ignore events for unapplied moves

CHANGELOG.md, package.json
- We've updated our icons to reflect the new Cozy branding with a deep blue
instead of the faded one and more of that blue around our lovely little cloud.
- With our new watcher, some remote movements that were detected, taken into
account but not applied locally (i.e. the file or directory itself would not
have been moved on the filesystem) because the client was stopped in the
middle of the synchronisation process would not be correctly applied after the
client is relaunched. In this situation, we would end up duplicating the
document that was moved, at its previous path.
We made sure we detect unapplied remote movements so we can finish applying
them and not duplicate your documents.
- Since it could be …
=> Release v3.13.0-beta.6

electron-builder.yml
Vertically center App and Applications folder icons in the MacOSX dmg
installer.
=> gui: Fix MacOSX installer icons positions

core/remote/watcher.js, test/unit/remote/watcher.js
=> core/remote/watcher: Ignore lower rev number changes

CHANGELOG.md, package.json
- The remote watcher now ignores changes with a revision lower than the
one we've saved on the associated document in the local Pouch.
Failing to do so was leading to files disappearing locally (before
reappearing a short while later) during their upload to the Cozy.
This could also be the cause of unexpected and undocumented behavior.
- When updating the Cozy branding, we messed up the alignment of icons
in the MacOS installer. The Cozy app icon, the arrow and the
Applications folder are now properly aligned and vertically centered
in the installer window.
=> Release v3.13.0-beta.7

core/local/steps/initial_diff.js, test/unit/local/steps/initial_diff.js
When transforming `scan` events into `renamed` events during the
initial scan, we don't know if some of the moved documents are
children of moved directories.
This is a problem because when dispatching them, we won't find any
document corresponding to their oldPath in Pouch since they would have
been moved just before.
To make sure all stopped client moves are correctly detected and
merged, we keep track of `renamed` events that are issued by the
initialDiff step or the watcher during the initial scan and use them
to correct any of their children's movements.
=> core/local/steps/initial_diff: Fix renamed events #1555

CHANGELOG.md, package.json
- We completely revamped the local watcher (the component looking for changes
in your local *Cozy Drive* directory). It should now be faster and more
reliable when synchronizing live changes. Expect a few more optimizations
regarding the initial scan very soon.
- The watcher type used (i.e. atom or chokidar) can still be chosen via the
config file. The new watcher (atom) is the default on Windows and GNU/Linux.
- We've updated our icons to reflect the new Cozy branding with a deep blue
instead of the faded one and more of that blue around our lovely little cloud.
- The remote watcher now ignores changes with a revision lower than the one
we've saved on the associated document in the local Pouch. Failing to do so
was …
=> release: 3.13.0

core/local/steps/initial_diff.js
The loop responsible for fixing the event oldPath if its parents have
moved can live outside the .initialDiff() function.
Based on #1564 
=> core/local/steps/initial_diff: Extract .fixPathsAfterParentMove()

CHANGELOG.md, package.json
- When renaming folders and deleting part of their content while the client
was stopped, the deletion should now be properly handled on restart.
- We downgraded the dependencies upgraded in [v3.13.1-alpha.1](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.13.1-alpha.1)
because the upgrade broke networking. It should work again now.
Happy syncing!
=> release: 3.13.1-beta.1

core/remote/change.js, test/unit/remote/change.js, test/unit/remote/watcher.js
To re-order changes coming from the remote changesFeed, we use the
javascript `sort()` function which compares 2 elements at a time,
elements `a` and `b`.
In our custom sorter, to make sure changes which delete (i.e. in Pouch
terms) a specific id come before changes which create the same id, we
have 2 comparisons following each other :
- first we check if change `a` deletes the id created by change `b`
- second, if the first comparison was falsy, we check if change `b`
deletes the id created by change `a`
Due to the way to compute the id deleted or created by a change, if
`b` deletes the id and `a` creates it (i.e. we should be in the second
comparison case), the first comparison we return a truthy value and
the creation will come first, leading to conflicts in Merge later.
To make sure …
=> core/remote/change: Fix deleted-created sort

.gitattributes
Because core.autocrlf=true breaks prettier.
---
=> git: Prevent CRLF for *.js files on Windows

dev/remote/automated_registration.js
Otherwise, for some yet undiscovered reason, a third-party dependency
seems to be passing a broken URL object to electron-proxy-agent which
then messes up HTTPS with port 80.
Used to be a string before refactoring anyway.
Not even sure `request*` & `*fetch` can handle an URL object either.
---
=> dev/remote/automated_registration: Pass string URLs to request

CHANGELOG.md, package.json
- We added a new icon set for the Offline status. Prior to this version,
whenever we detected you might be disconnected from the Internet, we
would display a "pause" icon with the "Disconnected" status label.
We're now displaying a shadowed version of the main icon and a
"No Internet connection" status label. We hope this is clearer to you.
- We fixed a bug in the way we sort changes coming from your remote
Cozy. For some changes like the replacement of a file, the order in
which we receive changes from the remote Cozy is crucial to applying
it correctly on the local filesystem. In this particular case, we were
not always sorting correctly the deletion and recreation of the file
(or folder) which could lead to documents disappearing or conflicts to
appear.
=> Release v3.13.1-beta.2

gui/js/proxy.js, test/unit/gui/proxy.js
When refactoring `gui/js/proxy` to make it testable, we actually broke
command-line arguments parsing. Which means app didn't start anymore.
Once fixed, some tests started breaking because the proxy setup was not
completely reverted in `test/unit/gui/proxy`.
Now everything should be back to normal.
---
=> gui/js/proxy: Fix .config() & tests

core/sentry.js
To stop spamming infra. Until we find a solution.
---
=> core/app: Temporarily disable Sentry

CHANGELOG.md, package.json
- We recently introduced a new icon for the Disconnected app status when we
can't reach your remote Cozy. On MacOS, this icon was rendered incorrectly
within the app itself, in the status bar.
We changed the icon to be of the expected color in the systray and the app
status bar.
Changes that should have no effects:
- We did some minimal refactoring on our proxy setup to introduce some tests.
There should be no effects on the way the proxy works.
=> Release v3.13.1-beta.3

CHANGELOG.md, package.json
Improvements for GNU/Linux users:
- We've mitigated an issue LibreOffice users could encounter while saving.
LibreOffice uses an intermediary temporary file when saving and in some
situations we could end up deleting the file altogether or move the previous
version to the Cozy's trash and even not be able to synchronise the new
version.
We're now ignoring those temporary files (i.e. with extension `.osl-tmp`)
which results in a correct update of the office document.
- The solution above applies only to LibreOffice users on Linux while there are
other software saving through a temporary file.
We are now able to detect the use of a temporary file in some situations and
correctly handle it (i.e. not move it to the trash and synchronise the new
version).
There are …
=> Release v3.13.1-beta.4

core/local/atom_watcher.js, core/local/steps/add_checksum.js, core/local/steps/add_infos.js, core/local/steps/await_write_finish.js, core/local/steps/channel.js, core/local/steps/dispatch.js, core/local/steps/filter_ignored.js, core/local/steps/incomplete_fixer.js, core/local/steps/initial_diff.js, core/local/steps/overwrite.js, core/local/steps/producer.js, core/local/steps/scan_folder.js, core/local/steps/win_detect_move.js, core/local/steps/win_identical_renaming.js, dev/capture/local.js, test/support/helpers/local.js, test/unit/local/steps/add_checksum.js, test/unit/local/steps/add_infos.js, test/unit/local/steps/await_write_finish.js, test/unit/local/steps/channel.js, test/unit/local/steps/dispatch.js, test/unit/local/steps/filter_ignored.js, test/unit/local/steps/incomplete_fixer.js, test/unit/local/steps/initial_diff.js, test/unit/local/steps/overwrite.js, test/unit/local/steps/producer.js, test/unit/local/steps/scan_folder.js, test/unit/local/steps/win_detect_move.js, test/unit/local/steps/win_identical_renaming.js
- Prevents naming confusion with built-in global Buffer
- Prevents using the built-in in case of missing import
- Type is actually some kind of *buffered channel*, but sticking to the
simpler `Channel` name since we don't have many of them.
---
=> core/local: Rename Buffer to Channel

CHANGELOG.md, package.json
- We've updated again some of our dependencies that don't require changes in
our code. Those are the same that were upgraded in [v3.13.1-alpha.1](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.13.1-alpha.1)
then downgraded back in [v3.13.1-beta.1](https://github.com/cozy-labs/cozy-desktop/releases/tag/v3.13.1-beta.1).
We investigated, identified and excluded the problematic updates, so
networking should work as expected this time.
Happy syncing!
=> release: 3.13.1-beta.5

CHANGELOG.md, package.json
- We added a new icon set for the Offline status. Prior to this version,
whenever we detected you might be disconnected from the Internet, we
would display a "pause" icon with the "Disconnected" status label.
We're now displaying a shadowed version of the main icon and a
"No Internet connection" status label. We hope this is clearer to you.
- We fixed a bug in the way we sort changes coming from your remote
Cozy. For some changes like the replacement of a file, the order in
which we receive changes from the remote Cozy is crucial to applying
it correctly on the local filesystem. In this particular case, we were
not always sorting correctly the deletion and recreation of the file
(or folder) which could lead to documents disappearing or conflicts to
appear.
- We …
=> Release v3.13.1

gui/js/updater.window.js
So users with slow connection have more chances to start downloading the
update before it is skipped.
---
=> gui/updater: Increase UPDATE_CHECK_TIMEOUT

CHANGELOG.md, package.json
- To help you keep your app up-to-date, we have a mechanism that checks for new
versions every 24 hours. While we do that check, the app does not attempt to
synchronise anything to avoid stopping the process while the new version is
installed. We set a maximum wait time of 5 seconds for the check so that you
won't get stuck in that state for too long. Unfortunately, we've noticed that
some users hit that timeout because the check was taking too long and don't
get the new version notification, probably because of a slow Internet
connection.
We've decided to increase the maximum wait time to 10 seconds to make sure
those users are informed that a new version is available. This should have no
impact for users with a fast Internet connection.
- In some situations, …
=> Release v3.13.2-beta.1

core/remote/watcher.js, gui/main.js, test/integration/conflict_resolution.js, test/unit/remote/offline.js, test/unit/remote/watcher.js
So the sync status doesn't "blink" on invariant violations for example.
Also made sure technical error messages were not shown to the user anymore.
Teamwork with @taratatach :heart: 
---
=> core/remote/watcher: Assume offline on FetchError only

core/merge.js, core/metadata.js
Don't include ids or the whole docs in error messages.
To make errors easier to read/group when debugging.
---
=> core: Improve logging

CHANGELOG.md, package.json
- Whenever we can't reconciliate some changes coming from your remote Cozy with
your local documents, we try to inform you via special status label and icon.
Those issues can have different origins but most of them were notified to you
as your computer lacking an internet connection. We've made some changes to
display the No Internet connection status only when we experience network
issues and a generic synchronisation issues status when we can't be more
precise.
=> Release v3.13.2-beta.2

core/sentry.js
This reverts commit d4a29001ec09780f9dc6d8f2e2dbce33156e2702.
=> core/sentry: Bring back monitoring

core/config/.cozyignore
- We better not touch it on Windows
- We may not have the necessary permissions anyway
---
=> core: Ignore "System Volume Information/" by default

CHANGELOG.md, package.json
- We changed the status label when we catch an error that was not
specific enough for us to offer you a simple resolution. In this
situation we were stating that the synchronisation was impossible
when in most cases, some changes can have been reconciliated and
synchronised. We're now saying that the synchronisation was
incomplete. You should still contact us in this situation as we might
be able to offer you some help.
- We improved error handling in our auto-update component. Hopefully
this should make it easier for people with flaky connections to get
the latest version of the app.
- Whenever we can't reconciliate some changes coming from your remote
Cozy with your local documents, we try to inform you via special
status label and icon. Those issues can have …
=> Release v3.13.2

core/local/atom/filter_ignored.js, test/scenarios/manage_moves_with_ignored_src_or_dst/atom/linux.json, test/scenarios/manage_moves_with_ignored_src_or_dst/scenario.js, test/unit/local/atom/filter_ignored.js
Until now, the `filterIgnored` module was ignoring events based on
their `path` attribute only.
However, `renamed` events also have an `oldPath` attribute. Movements
can happen from or to an ignored location and this should be handled
as follows:
- ignored to not ignored: event should be considered as a `created`
event at the not ignored destination path, the `path` attribute
- not ignored to ignored: event should be considered as a `deleted`
event at the not ignored source path, the `oldPath` attribute
- not ignored to not ignored: event is untouched
- ignored to ignored: event is completely ignored
=> local/atom/filter_ignored: Handle renamed paths

core/constants.js, core/sync.js
- No need for a module for a single constant...
- It is only used in Sync anyway.
---
=> core: Merge ./constants into ./sync

core/metadata.js, test/unit/metadata.js
If a file, already in conflict, should be renamed because of a
conflicting document and has ancestors, then those ancestors should
not be duplicated in the generated path.
=> core/metadata: No ancestors duplication in conflict names

.travis.yml, test/scenarios/move_a_to_c_and_b_to_a_dir_dir_delay/scenario.js, test/scenarios/move_dir_and_update_subfile/scenario.js, test/scenarios/move_files_a_to_c_and_b_to_a/scenario.js, test/scenarios/move_overwriting_dir/scenario.js, test/scenarios/move_overwriting_file/scenario.js, test/scenarios/run.js, test/scenarios/trash_dir_with_content/scenario.js
Minimal test harness so we can quickly fix #1638 without breaking something else.
Other improvements can come up in a future PR regarding travis jobs & the scenario runner.
---
=> travis/linux: Add job for stopped client scenarios

core/local/atom/initial_diff.js, test/scenarios/move_dir_and_update_subfile/scenario.js, test/unit/local/atom/initial_diff.js
Do not ignore moved descendants to prevent file modification occuring
while client is stopped to be unsynced.
So the `renamed` child gets:
- its checksum computed in the add_checksum step
- converted to `created` in the dispatch step
---
=> core/local/atom/initial_diff: Fix dir move + subfile update

core/config/.cozyignore, core/ignore.js, core/local/atom/producer.js, test/unit/local/atom/producer.js
So we don't try to scan:
- `.system-tmp-cozy-drive/` contents
- Windows system files/dirs
---
=> core/local/atom/producer: Do not #scan() ignored files/dirs

core/local/atom/producer.js, test/unit/local/atom/producer.js
Same as in the filter_ignored step.
---
=> core/local/atom/producer: Log scan ignored events

CHANGELOG.md, package.json
- We've found out that if a file is replaced and it's parent directory
moved or renamed while the client was stopped, we were issuing a
deleted event for the file at its new location because its inode is
different and we didn't match it with its Pouch document.
However, we have logic that prevents issuing deleted events for paths
we have seen during the initial scan.
The problem here is that we were correcting the file's path (i.e. we
follow its parent move and use its new location in the file's path)
after checking if we had seen the path during the initial scan.
We're now correcting the path before doing the check so a scan event
of the new file's path will prevent the initialDiff from issuing a
deleted event for it.
See also [known …
=> release: 3.13.4-beta.2

CHANGELOG.md, package.json
- We fixed an issue where copies of conflicting files would not be created at
the right path.
- We improved our test harness regarding the initial scan of the local synced
directory. Those new tests already allowed us to identify and fix a couple
of issues (see next points).
- When moving a directory then updating a descendant file while the app was
stopped, the file change would not be synced. This now works as expected.
This used to work but was broken at some point. The new tests should prevent
this to happen again.
- We've found out that if a file is replaced and it's parent directory
moved or renamed while the client was stopped, we were issuing a
deleted event for the file at its new location because its inode …
=> release: v3.13.4

core/local/chokidar/initial_scan.js, core/local/chokidar/prepare_events.js, core/local/chokidar/send_to_prep.js, core/local/chokidar/watcher.js, test/unit/local/chokidar/initial_scan.js, test/unit/local/chokidar/prepare_events.js, test/unit/local/chokidar/watcher.js
- Makes `ChokidarWatcher` smaller
- Makes it easier to understand/document steps
- Better matches the `AtomWatcher` design
---
=> core/local/chokidar: Extract steps

gui/elm/Window/Tray/Settings.elm
- Sync status is already shown in the status bar
- Using it as the button label can be confusing (e.g. errors)
---
=> [WIP] gui/elm/Window/Tray/Settings: Don't change manual sync button label

core/path_restrictions.js, doc/usage/macos.md, test/integration/platform_incompatibilities.js, test/unit/remote/watcher.js
So it allows slash (`/`) from a macOS user standpoint.
=> core/path_restrictions: Allow colon (`:`) on macOS

core/remote/cozy.js, core/remote/watcher.js, core/sync.js, core/utils/logger.js, test/unit/remote/cozy.js, test/unit/remote/watcher.js
- Extracted from `RemoteWatcher` and `Sync`
- Mostly keeping the current behavior, except...
- Non-Fetch errors on disk-usage request in `Sync` don't trigger an offline/online round trip anymore.
---
=> core: Improve common Cozy errors handling

test/unit/local/chokidar/initial_scan.js, test/unit/metadata.js
Fixes issue in 2731cb3c not detected because electron-mocha was silently
ignoring some `.only()` invocation (forgotten in 2cf9290f, fixed in
32f4564a) despite the `--forbid-only` options, skipping the whole test
suite.
---
=> test/unit: Fix tests broken by unrestricted macOS colon

core/metadata.js, test/unit/metadata.js
The body of `createConflictingDoc()` was getting very complex and
error prone (e.g. keeping the previous conflit's milliseconds part
when a document has no extension).
We have 2 very different situations:
- either the document already has a conflict suffix
- or it does not
In the first case, we want to replace the previous suffix with a new
one while we want to add a conflict suffix in the second case, after
the file's basename but before its extension.
We can then create one function for each case, returning a new version
of the file's path and return a copy of the document with new `path`
and `_id` attributes.
=> core/metadata: Dissociate adding and replacing conflict suffixes

core/remote/cozy.js, test/unit/remote/cozy.js, test/unit/remote/watcher.js
Based on #1621 
The `cozy-client-js` lib defines its own `FetchError` objects when
throwing a network error.
This means it is not an instance of the `electron-fetch` defined
`FetchError` type and that calls to `instanceof` won't qualify errors
thrown by calls to `cozy-client-js` methods as `Fetch` errors.
However, we can detect all `Fetch` errors in
`.handleCommonCozyErrors()` by checking if their name is
"FetchError".
=> core/remote/cozy: Expect cozy-client-js FetchErrors

core/remote/cozy.js, gui/main.js, test/unit/remote/cozy.js, test/unit/remote/watcher.js
Based on #1650 
We're throwing an error with the message 'Client has been revoked' in
multiple places.
To make sure we're always throwing the same error (i.e. to avoid catch
mistakes) and to DRY up the code, we're extracting this error as its
own type in `RemoteCozy`.
=> core/remote/cozy: Introduce CozyClientRevokedError

test/unit/remote/watcher.js
Based on #1654 
If we try so save a document whose id starts with an underscore, Pouch
will raise an error with a `status` attribute of value `400`.
This leads us to believe this is an HTTP error coming from the stack
that we interpret as a revoked client error.
This unit test demonstrates the situation.
=> core/remote/watcher: Failing test on Pouch reserved ids error

CHANGELOG.md, package.json
- In case your client enters an error state, the manual synchronisation button
will now display is normal label instead of the error label which is already
display in the window's top bar.
- We fixed an issue with conflicting document names in the previous version but
introduced in the process a bug with files without extensions. If we detected
a conflict on a file without extensions that already had the conflict suffix,
we would use the milliseconds part of the previous conflict suffix as the new
file extension. We're now correctly handling conflict suffixes replacement
for all types of documents, with or without extensions.
- We recently tried to reduce the error kinds that would lead to a
"No Internet connection" status to network errors only and introduced …
=> Release v3.14.0

test/mocha.opts
It is not necessarily the default.
---
=> test/mocha.opts: Add --color

core/local/atom/initial_diff.js
It was introduced in 64f3cb080 but has no corresponding unit test or
scenario.
---
=> core/local/atom/initial_diff: Drop untested code

package.json, test/support/istanbul_reporter.js, yarn.lock
- Compatible with electron 2.x
- Supports all the mocha CLI options (including `--forbid-only`)
So we don't silently disable the whole test suite on CI.
(thanks @taratatach for pointing these recent changes)
---
=> yarn: Upgrade electron-mocha to 8.0.3

.travis.yml
Could divide the number of scenarios to run by 3 and make macOS CI
faster.
We didn't really change the chokidar watcher recently, so it should be
relatively safe without it. We can still revert this as needed anyway.
---
=> travis: Don't run all chokidar flushing scenarios

dev/repl.js
So at least the REPL starts.
Until we find a way to fix the import/token issue.
---
=> dev/repl: Temporarily disable helpers

core/IdConflict.js, core/local/index.js, core/merge.js, core/metadata.js, core/move.js, core/prep.js, core/reader.js, core/remote/index.js, core/side.js, core/sync.js, core/writer.js, test/scenarios/index.js, test/support/builders/metadata/base.js, test/support/doubles/side.js, test/unit/remote/index.js
Allows:
- Grouping side-related stuff together
- Breaking cyclic dependencies
- Enforcing interfaces
- Removing a few `$FlowFixMe` & `eslint-disable*` annotations
---
=> core: Refactor Side, Reader & Writer

core/local/chokidar/event_buffer.js, test/scenarios/move_a_to_c_and_b_to_a_dir_dir_delay/scenario.js, test/scenarios/move_files_a_to_c_and_b_to_a/scenario.js, test/scenarios/run.js, test/support/helpers/cozy.js, test/support/helpers/scenarios.js
To make sure we don't have bad interactions between the
synchronization of remote changes and the local watcher, we need to
run the local watcher during our remote scenarios.
This involves running the watcher, sending a magic event after we've
run all scenarios actions to signal the end of the test and using real
inodes to make sure the local watcher does not detect and merge inode
changes on init files during its initial scan.
=> Test sync feedback in remote scenarios

core/local/atom/dispatch.js, test/scenarios/move_a_to_b_and_create_a/remote/changes.json, test/scenarios/move_a_to_b_and_create_a/scenario.js, test/scenarios/move_a_to_c_and_b_to_a_dir_dir_delay/scenario.js, test/scenarios/move_files_a_to_c_and_b_to_a/scenario.js, test/scenarios/replace_file_with_file/scenario.js, test/unit/local/atom/dispatch.js
In the AtomWatcher, when an `renamed` event reaches the `dispatch`
step, the Pouch document matching the source path can have changed
already and not match the old situation anymore.
This is especially true when synchronizing a remote move and a remote
addition at the move source path.
Sending that event to `Merge` would lead to a conflict on the
destination path in our example (i.e. we're using the newly added
document as the move source while it differs from the destination
document).
To mitigate the situation, we can compare the inodes of the
file/directory that triggered the event and the existing document we
found in Pouch corresponding to the event `oldPath` attribute.
If those differ, we discard the event.
We assume here that the filesystem won't change the inode when moving
a …
=> core/local/atom/dispatch: Compare inodes for moves

test/scenarios/move_and_trash_file_from_inside_move/atom/linux.json, test/scenarios/move_and_trash_file_from_inside_move/local/darwin.json, test/scenarios/move_and_trash_file_from_inside_move/scenario.js
Moving a directory and then deleting (or moving outside the synced
directory) one of its children will result in the child not to be
trashed.
=> test/scenarios: Add failing scenario for move+delete child

core/metadata.js, test/unit/metadata.js
The regexp matching existing conflict suffixes in document paths was
too open and would match conflicts in the document's parents (e.g.
`parent-conflict-2019-07-29T14_00_01.223Z/document.pdf`).
This would result in replacing the parent's conflict suffix instead
of adding a suffix to the child document's path.
The regexp now ensures via a look-ahead that the conflict suffix being
matched is not followed by a `/`, marking a parent directory.
=> core/metadata: Child conflicts do not replace parent conflict suffix

core/merge.js, core/metadata.js, core/move.js, core/pouch/index.js, core/pouch/migrations.js, core/sync.js, test/integration/add.js, test/integration/full_loop.js, test/support/builders/metadata/base.js, test/support/helpers/scenarios.js, test/unit/local/index.js, test/unit/merge.js, test/unit/metadata.js, test/unit/pouch/migrations.js, test/unit/sync.js
We don't control the Pouch's `_rev` attribute set on each document.
When we move a document, the destination will be a new document  in
Pouch. This means its `_rev` will probably start with 1 (it can be
higher if the path has previously existed but it does not matter
here).
Since our mechanism to determine which changes need to be applied on
which side is based on the `_rev` value (i.e. its short rev or
beginning number to be precise) and the `sides` we maintain, we
cannot keep the existing `sides` value since they will probably not be
correlated with the new `_rev` anymore.
This means we're losing information when doing a move.
This loss prevents us from being able to merge some combinations of
changes.
e.g. With the client stopped:
1. add document to a folder locally
2. move that folder …
=> core: Use our own rev to determine changes to apply

.travis.yml, package.json, test/unit/local/chokidar/watcher.js, yarn.lock
We've recently seen an increase in MacOS build failures with errors
like SIGABRT or SIGBUS.
Those are likely to be RAM errors and seem to happen when closing the
Chokidar watcher.
The recent release 3.0.2 of Chokidar has brought significant
improvements in CPU and RAM consumption so we hope this will help our
builds to pass.
Besides, this should be a great improvement for our MacOS users.
=> dependencies: Bump chokidar version

core/merge.js, core/metadata.js, core/move.js, core/side.js, test/integration/move.js, test/unit/merge.js, test/unit/metadata.js, test/unit/move.js
If a file is added to a directory on one side while the directory is
moved on the other side, we should not try to apply the move on the
child file but transform it instead so it is interpreted as a file
addition at the new location (i.e. in the directory's new path).
This is allowing us to merge both changes during the initial scan
where the client applies changes coming from both sides before
synchronizing them.
=> core/merge: Transform child move if file was created on other side

gui/js/tray.window.js, gui/js/window_manager.js
When starting the app, an empty, transparent window is displayed and
can only be closed by clicking on the systray icon and unfocusing the
replacing window.
We actually want no windows to be displayed on start. For some reason,
waiting for the DOM content to be ready and displayed before hiding
the window causes its content to be hidden (hence the transparency)
but not the window itself.
Since we don't really need to display the window and its content
before hiding it, we can rely on the `show` window option to
determine when to display the window and when to return it right after
its creation.
=> gui: Start app minimized in systray

CHANGELOG.md, package.json
- Replacing a file on the remote Cozy with a new version without
overriding the previous one (i.e. moving/deleting the first version
before uploading the new one) while the client was off would lead to
a conflict on said file. The client now understands that the file has
been replaced and synchronises it.
- When handling a conflict on a document whose ancestor was already in
conflict would lead to the ancestor's conflict suffix to be replaced
instead of a conflict suffix to be added on the document itself. This
would make detecting and fixing conflicts difficult for you. We've
made our conflict resolution logic more robust to avoid those
situations in the future.
- Due to the way we used to decide on which side changes should be
applied (i.e. either on the …
=> Release v3.15.0-beta.1

CHANGELOG.md, package.json
- Replacing a file on the remote Cozy with a new version without
overriding the previous one (i.e. moving/deleting the first version
before uploading the new one) while the client was off would lead
to a conflict on said file. The client now understands that the
file has been replaced and synchronises it.
- When handling a conflict on a document whose ancestor was already
in conflict would lead to the ancestor's conflict suffix to be
replaced instead of a conflict suffix to be added on the document
itself. This would make detecting and fixing conflicts difficult
for you. We've made our conflict resolution logic more robust to
avoid those situations in the future.
- Due to the way we used to decide on which side changes should be
applied (i.e. either on the …
=> Release v3.15.0

CHANGELOG.md, package.json
- The UTF-8 encoding fix we shipped in the previous release was missing a
crucial step when re-encoding `NFD` paths with `NFC` which lead to the
creation of conflicts on accentuated paths for users synchronizing a directory
placed on a HFS+ volume.
In response, we've changed the way we attack this problem and decided to keep
paths in the encoding they were created with in Pouch and manage the mapping
with the filesystem only.
=> Release v3.15.1-beta.1

core/merge.js, test/integration/move.js, test/unit/merge.js
If a folder is created locally then moved between the merge and the
synchronization of its creation then we should not consider it as a
move but rather as an addition or we will fail at synchronizing it
since it doesn't exist on the remote Cozy yet.
The same is already done for file movements.
=> core/merge: Treat local-only folder move as addition

CHANGELOG.md, package.json
- In some situations, like when a large quantity of data is
synchronized with the remote Cozy, adding a directory and then
renaming it before we had a chance to synchronize it would result in
a error and that directory (and by extension, its content) would
never get synchronized.
We're now correctly handling this situation, like we were already
doing for files, by treating this directory renaming as a simple
addition of the directory at its most recent location.
=> Release v3.15.1-beta.2

CHANGELOG.md, package.json
- In some situations, like when a large quantity of data is
synchronized with the remote Cozy, adding a directory and then
renaming it before we had a chance to synchronize it would result in
a error and that directory (and by extension, its content) would
never get synchronized.
We're now correctly handling this situation, like we were already
doing for files, by treating this directory renaming as a simple
addition of the directory at its most recent location.
- The UTF-8 encoding fix we shipped in the previous release was
missing a crucial step when re-encoding `NFD` paths with `NFC` which
lead to the creation of conflicts on accentuated paths for users
synchronizing a directory placed on a HFS+ volume.
In response, we've …
=> Release v3.15.1

CHANGELOG.md, package.json
- When moving or renaming directories and subdirectories on your
remote Cozy pretty quickly or with your Desktop client turned off,
we would detect all moves but would end up dropping the moves of
children directories of moved directories. This would lead to
unsynchronized directories.
We're now treating them the same way we do for children file
movements and keep them synchronized.
=> Release v3.15.2

package.json, yarn.lock
Version 0.15.0 of `cozy-client-js` upgrades its PouchDB dependency to
the latest major version, v7, like our direct dependency.
This also means that we won't need to build yet another version of
`leveldown` (which is required by `pouchdb`), clearly outdated on top
of that, preventing us from upgrading Electron.
=> deps: Upgrade cozy-client-js

.travis.yml, package.json, yarn.lock
`node-abi` is used to find the node ABI (sequential build number?)
which is in turn used to find pre-built packages of native
dependencies like atom/watcher.
`atom/watcher` depends on `prebuild-install@5.2.4` which depends on
`node-abi@^2.7.0`.
`node-abi@2.7.0` adds the ABI for Electron v4.0.4 but not the latest v4
version.
So we'll need to upgrade Electron further and thus require a
greater version of `node-abi`.
But Yarn won't upgrade the package to its latest version even when
manually upgrading it. Which means we need to set it as a direct
dependency.
We'll also force all dependencies requiring `node-abi@^2.x.x` to use
`node-abi@2.11.0` via a resolution.
=> deps: Add direct dependency to node-abi

gui/js/proxy.js
We were setting the `host` and `User-Agent` request headers for HTTP
requests but not for HTTPS requests.
On the other side, we were handling string options for HTTPS requests
but not for HTTP requests.
We're now applying the same changes to the options for both HTTP and
HTTPS requests.
=> gui/proxy: Add request options for HTTP and HTTPS

core/remote/change.js, test/unit/remote/watcher.js
Ignored remote changes were not taken into account by the remote change
sorter so their order was unpredictable.
Since they won't trigger any actual modifications we can safely put
them at the end of the changes list and have predictable test results.
=> core/remote/change: Push ignored changes to the end

core/local/chokidar/analysis.js, core/local/chokidar/local_change.js, test/unit/local/chokidar/analysis.js
The relative sort order of moves and file additions depends solely
on their paths.
But, the sorter does not handle file updates as file additions like
the remote watcher does.
This means that the relative order of moves and file updates is not
stable and leads to randomly failing tests.
We can use the same algorithm for sorting local file updates and moves
as the remote watcher does and sort them by "add" path only.
=> core/local/chokidar/analysis: Stabilize updates sort order

test/integration/id_conflict.js
The expected behavior for NFC -> NFD renaming has changed in v3.15.1
but has not been reflected in the integration tests.
This should have failed but has not.
Those reflect the new expected behavior (i.e. local HFS+ renamings
are not propagated to the Cozy on macOS).
=> test/integration/id_conflict: Fix normalization tests

core/local/atom/add_infos.js, test/scenarios/case_and_encoding/identical_additions/complex_dirs/linux/atom/linux.json, test/scenarios/case_and_encoding/identical_additions/complex_dirs/win_mac/atom/win32.json, test/scenarios/case_and_encoding/identical_additions/dir_file/linux/atom/linux.json, test/scenarios/create_dirs/atom/win32.json, test/scenarios/move_dir_from_the_outside/atom/win32.json, test/unit/local/atom/add_infos.js
When captures contain stats, the Sync will detect changes on inodes
since files and folders are recreated for each test run but captures
are not and thus their stats will differ.
We need to modify the `addInfos` step so `scan` events too get stats
if they're missing.
=> test/scenarios: Don't use stats from captures

core/config.js
When persisting the config, we use a temporary file to avoid losing
data if writing the config file fails.
When we introduced this mechanism, we decided to use copy on write but
this seems to lead to errors on macOS and is not really necessery
after all.
=> core/config: Stop doing copy on write

.travis.yml
CouchDB can sometimes not be available when we try to create the test
instance.
Using travis_retry, we can retry to create the instance twice.
=> ci/travis: Retry creating a cozy-stack instance

package.json, yarn.lock
Use our own fork of node-windows-fsstat with Node 12 support so we can
upgrade Electron.
=> deps: Use node-windows-fsstat with Node 12 support

CHANGELOG.md, package.json
- We upgraded a lot of dependencies and especially Electron which was
upgraded to v5.0.0. This brings in Node v12.0.0. They should bring
performance and stability improvements.
- We improved the stability of the ordering and identification of
changes fetched from the remote Cozy. This should reduce the number
of unmergeable changes and conflicts arising from those situations.
This is especially true when complex moves were synchronised with
the remote Cozy (e.g. moving a folder from inside a moved folder).
- We fixed a few minor UI issues like long filenames which were not
correctly ellipsized in the synced files list.
- In an attempt to prevent losing a working config, we decided to use
a write technique called copy-on-write. This …
=> Release v3.16.0-beta.1

package.json
Our `cozy-client-js` dependency has a peer dependency to
`babel-polyfill` which was not satisfied and would result in errors in
production builds.
=> deps: Add direct dependency to babel-polyfill

CHANGELOG.md, package.json
- Apple now requires a notarization step for apps to be installed on
newer versions of macOS. With this process, Apple certifies that
Cozy Desktop does not contain any known malware and macOS will let
you install our app without having to tinkle with your security
parameters.
=> Release v3.16.0-beta.3

CHANGELOG.md, package.json
- When upgrading Electron to v5.0.0, we broke the onboarding process
because of a new security restriction in Chromium (which is packaged
with Electron) preventing us from redirecting to the folder
selection window after connecting to your Cozy and authorizing the
Cozy Desktop app.
The redirection is now handled differently to avoid the security
issue and load the folder selection window.
- Our remote changes watcher tries to recreate the changes that were
executed on the remote Cozy from the resulting documents and the old
versions we have locally. We found out that we were not correctly
detecting and thus handling complex hierarchy changes like:
* child only moves (i.e. we detect a move on a folder descendant
which is due to its ancestor move and should not …
=> Release v3.16.0-beta.4

core/remote/change.js, test/unit/remote/change.js
The javascript `Array.sort` function does not compare every element in
the array with each other (for performance) but instaed expects that
the given sort algorithm will be stable (i.e. the final order of
elements does not depend on the initial order of elements).
To sort our remote changes, we use different criterias, depending on
the elements we are comparing.
This results in an unstable algorithm and thus in un unpredictable
final order.
To avoid this, we break our algorithm into different sorting functions
with one criteria per function:
1. we sort our changes by path to have some basic order, useful mostly
for tests
2. we sort the resulting array by hierarchy so we create the parent
folders before creating their descendants, move a document and its
potential descendants before we …
=> core/remote/change: Separate sorting criterias

core/app.js
The new `https` module's `request` builder does not need the protocol
to be specified.
In fact, it doesn't expect any `protocol` and specifying one throws an
error and logs are not sent to us.
=> core/app: Don't specify protocol when sending logs

core/local/chokidar/event.js, core/local/chokidar/watcher.js, test/unit/local/chokidar/event.js
Sometimes `fsevents` can fire an `add` or `addDir` event when it
should fire its directory or file counterpart respectively.
Since we have access to the file/directory stats we can fix the event
type when building a `ChokidarEvent` to handle the change correctly.
=> core/local/chokidar: Fix wrong fsevents event type

CHANGELOG.md, package.json
- When you send a message to our support via the application, we also
securely send your last log file to one of our servers for analysis
so we can better identify the issues you might be facing. When we
upgraded Electron, the expected configuration of this request has
changed and the log file would not be sent anymore.
We've updated this configuration and log files are joined to your
message again.
- We found out that the libraries we use to watch the changes done to
your files on your filesystem could sometimes fire events with the
wrong type. Indeed, we've seen events for the addition of files with
a directory type and vice-versa.
We rely on this type to decide which actions to run so we're now
verifying that the type we …
=> Release v3.16.0-beta.6

doc/usage/linux.md
From now on, the Cozy Desktop AppImages won't include any code to
integrate the app with the user's desktop (see
https://www.electron.build/configuration/appimage).
For integrating the app with a linux desktop the user now needs to
install the previously optional `appimaged` daemon and move the
AppImage file in specific locations.
The documentation now reflects those changes and some changes to the
supported distributions: some old unsupported distributions were
removed from the list and the newest Fedora and Debian (thanks
@Picus13) were added.
=> doc/usage/linux: Update desktop integration how-to

gui/js/tray.js
The systray icon context menu used to be displayed on Windows and
Linux.
As part of a refactoring of the tray logic, the context menu was
removed from Windows by mistake.
=> gui/tray: Add context menu on Windows

core/local/atom/initial_diff.js, core/local/chokidar/initial_scan.js, core/pouch/index.js, core/pouch/migrations.js
When loading all documents in migrations or the initial scan of either
local watchers, we end up using a low-level db iterator which seems to
fail at parsing documents when they're too deeply nested (i.e. lots of
`moveFrom` inside `moveFrom`, probably resulting from conflict loops).
PouchDB uses a fallback mechanism when parsing JSON documents fails
and uses the vuvuzela library instead (see
https://github.com/nolanlawson/vuvuzela) which does not suffer from
deeply nested documents parsing errors.
By using the PouchDB's `allDocs()` method to get all the saved
documents, we hope not to use the low-level iterator that's failing
us.
=> Load docs in bulk in initial scans and migrations

core/local/atom/dispatch.js, core/local/atom/fire_local_start_event.js, core/local/atom/producer.js, core/local/atom/watcher.js, core/sync.js, core/syncstate.js, gui/js/tray.js, gui/main.js, test/unit/local/atom/dispatch.js, test/unit/local/atom/producer.js
I found out that when files are uploaded to the remote Cozy, the app's
icon is not showing the activity spinner.
I fear that combined with the fact that files show up in Drive Web as
soon as we start uploading it, users might think that the file is
fully synchronized before we've actually completely uploaded it.
From there I decided to refactor the state computation and the steps
we go through with the Atom Watcher since it does not buffer events
like we do in the Chokidar Watcher and thus the sync state computation
built for the Chokidar Watcher was not working very well with it.
=> gui: Improve state computation

core/local/atom/incomplete_fixer.js, test/support/helpers/context_dir.js, test/unit/local/atom/incomplete_fixer.js
When analysing the logs of users who experienced local conflict loops,
I saw that the loop started if the conflict happens on a document with
an inode that can be found on another document.
From what I've seen, the other document is the source of a move while
the document on which we detect a conflict is the destination.
This means that we did not detect and process this move as such but as
the creation of the destination only.
I've been able to reproduce at least one of the situations in which
this can happen by downloading a file directly within the local
Cozy Drive folder using Chromium. This browser uses a temporary file
with the `crdownload` extension that is renamed into the desired name
when the download is complete.
We're missing that specific renaming for large files because we …
=> core/local/atom/incomplete_fixer: Keep renamed for existing docs

CHANGELOG.md, package.json
- We use a monitoring system (hosted on our own infrastructure) to
receive reports of errors happening when you use Cozy Desktop. This
system requires a client to be setup in our app to send those
reports to the server. We used an older version of that client which
stopped working when we upgraded Electron in the previous version
and that lead to app crashes whenever we tried to send a report.
We've migrated to the latest version of that client so you shouldn't
experience those crashes anymore and we'll even get a bit more of
information in each report which might help us help you.
- We have detected that in some very specific situations, the app can
enter a local loop of conflict renaming on one or more documents.
Those loops would prevent your document to be …
=> Release v3.16.1-beta.1

electron-builder.yml
With the recent versions of `electron-builder`, the generated AppImage
file for x64 archictectures does not have `x86_64` in its name like it
used to.
We need this part in the file name for the nuts server to find it when
users want to download the app from our website.
=> dist: Add back arch in x64 linux AppImage name

CHANGELOG.md, package.json
- The library used to package our binaries changed the format of the created
Uninstall Windows registry subkey without cleaning up old keys when updating
the application. This means that Windows users updating from a version prior
to v3.16.0 to v3.16.0 will have 2 Cozy Drive applications listed in the
Windows programs manager and uninstalling the old version will actually
uninstall the most recent and leave them with a seemingly un-uninstallable
Cozy Drive version.
We added some cleanup logic to Cozy Drive to take care of removing the old
registry subkey automatically.
=> Release v3.16.1-beta.2

core/utils/win_registry.js, electron-builder.yml
Files within the app's asar archive are not accessible at runtime
while the `regedit` module uses `.vbs` files to execute the Windows
registry modifications so we need to copy those to the `resources`
folder and tell `regedit` where to find them for our registry
modifications to work.
=> dist: Copy regedit files into app resources folder

CHANGELOG.md, package.json
- Files within the app's asar archive are not accessible at run time
while the library we use to modify the Windows registry loads `.vbs`
files to execute the modifications.
We've bypassed this limitation by copying the `.vbs` files to the
app's `resources` folder and telling the library where to find them
for our registry modifications to work.
=> Release v3.16.1-beta.3

gui/js/autolaunch.js
On Linux, the auto-launch entry is a `.desktop` file containing the
app's name and path and some arguments like the `--hidden` flag.
It is generated within `$HOME/.config/autostart/` and is supposed to
be named after the given `name` option but a bug in `auto-launch`
changes that `.desktop` file name into the executable name.
Since our executable name contains the app's version, every time a
user updates the app, the auto-launch `.desktop` file name does not
match anymore and the autolaunch is disabled.
We can however force the `appName` option right after initializing a
new `auto-launch` object and have the library create a `.desktop` file
that will match any version of the application.
=> gui/autolaunch: Use app name for entry on Linux

CHANGELOG.md, package.json
Improvements for GNU/Linux users:
- On Linux, every time you updated the application, you had to
re-enable auto-launch if it was previously enabled because the
auto-launch entry contained the application's version and would not
match the new version.
We've changed the entry's name to just `Cozy-Desktop` so all
versions will match and the auto-launch will stay enabled after an
update.
=> Release v3.16.1-beta.4

CHANGELOG.md, package.json
- We use a monitoring system (hosted on our own infrastructure) to
receive reports of errors happening when you use Cozy Desktop. This
system requires a client to be setup in our app to send those
reports to the server. We used an older version of that client which
stopped working when we upgraded Electron in the previous version
and that lead to app crashes whenever we tried to send a report.
We've migrated to the latest version of that client so you shouldn't
experience those crashes anymore and we'll even get a bit more of
information in each report which might help us help you.
- We have detected that in some very specific situations, the app can
enter a local loop of conflict renaming on one or more documents.
Those loops would prevent your document to be …
=> Release v3.16.1

build/afterPackHook.js, build/launcher-script.sh, electron-builder.yml
Electron packages a Chromium executable within each app to render the
application's graphical content and starting with Electron v5, the
Chromium sandbox is activated by default.
On Linux, recent versions of Chromium use a kernel feature to run this
sandbox: unprivileged user namespaces with clone. This feature is
unfortunately disabled by default on Debian issued kernels as they
consider it is not ready for production and increases the attack
surface of the operating system (see
https://lwn.net/Articles/673597/).
Chromium has another option to run sandboxes: using a root owned
binary with the SUID bit to access the privileged user namespaces.
This is a separate binary which is shipped with Electron applications.
Our problem is that the SUID binary is packaged within our AppImage
and is …
=> dist: Disable sandbox on kernels not supporting it

core/local/atom/add_infos.js, test/unit/local/atom/add_infos.js
Sometimes, AtomWatcher won't know the kind of a deleted document and
will trigger a `deleted` event with an `unknown` type.
In those situations, we decided to always force the kind to `file`.
However, if the deleted document is actually a directory, the deletion
won't happen because we'll get an `Mismatch on doctype for doTrash`
error during merge.
It seems more reasonable today to try and fetch the document with the
event's `_id` from Pouch and use its doctype to set the event's kind.
If we don't have any document in Pouch with the event's `_id`, we can
resort back to forcing the kind to `file`.
=> core/local/atom/add_infos: Try to guess deleted event kind

core/remote/warning_poller.js
The warnings poller uses a system of timeouts with defined delays
called ticks to check if any action is required from the user.
The main function `poll()` is called via `setTimeout` but wasn't bound
to the instance so the instance's ticks where not defined anymore when
trying to figure out the next tick.
This prevents the poller from polling after the first attempt and is
easily fixed by wrapping the call to `poll()` with an arrow function.
=> core/remote/warning_poller: Fix binding in setTimeout

doc/usage/macos.md
It has been reported to us that the application does not work on
macOS 10.9 Mavericks anymore. Since we don't have any device to test
this, Apple does not officially support this version anymore and the
Chrome documentation states that only macOS 10.10+ is supported, we've
decided to show we don't support this version at all and that we don't
expect Cozy Desktop to work on it anymore.
We also take the opportunity to add the last 2 versions of macOS and
state that we only actively support those 2 while only the latest
version is actively tested since we have a device to test it.
=> doc: Update supported macOS versions

CHANGELOG.md, package.json
- In some situations like unsigned Terms of Service, requests to the
remote Cozy will result in errors and the synchronization will fail.
To anticipate those, we have a poller that requests from the Cozy
required user actions and that turns them into alerts that
Cozy Desktop will show you. A technical error in the poller resulted
in failure to schedule polls past the first one and you would miss
those very precious information unless you would restart the
application.
You should now be shown those alerts as early as possible without
restarting the application thus enabling you to anticipate
synchronization errors.
- The library we use to watch for changes on the local filesystem,
Atom Watcher, can sometimes generate …
=> Release v3.16.2-beta.1

build/launcher-script.sh
To determine whether unprivileged user namespaces are enabled in the
user's kernel or not, we check the content of a file that will
probably be missing in most kernels where unprivileged user namespaces
have not been disabled by default.
This will trigger an error that we send to `/dev/null` but the `-e`
option of the launcher script forces the script to stop anyway.
Now that the script has been implemented and tested, we can remove
this option as well as the `-x` option which prints out every single
command.
=> launcher: Don't bail out on bash errors

core/utils/sentry.js
Until now, only errors marked with the `sentry: true` property were
sent to Sentry so their number would be limited.
However, some issues our users face are hard to analyze and understand
even when we can get our hands on user logs since those are usually
too recent compared to the time the original issue happened.
By sending a report for every error, we can hope we'll be alerted
sooner of potential issues or at least go back to older reports when a
user comes to us with some issue.
This should also give us a more global overview of issues users run
into and how many are affected.
=> core/utils/sentry: Send report for every error

core/pouch/index.js, test/unit/pouch.js, test/unit/sync.js
We changed the arguments of `Pouch#getPreviousRev()` to get passed a
revision diff count so we could introduce the `sides.target` on
documents.
This count is meant to select the count'th previous revision of the
specified document. To do so, we fetch all revision ids of the
document (i.e. the hash part of each revision) and use the count to
pick the id at the right index. We thought those were ordered by
ascending short revision order while they're actually ordered by
descending short revision order (i.e. the latest revision id is the
first of array).
This means that we were not selecting the right revision in Sync when
trying to get the latest known remote revision to propagate a file
update to the Cozy. This would cause conflict errors and prevent the
propagation.
Please make sure the …
=> core/pouch: Pick correct previous revision

CHANGELOG.md, package.json
- We use a local Pouch database to keep track of all documents and their
metadata. Part of this metadata are the remote identifier of each document on
the Cozy and its last known revision. Whenever we make a change on a document,
we fetch its previous version from the local Pouch database so we can access
its old metadata. When the change happened locally, we pass along to the Cozy
this old metadata's remote revision so it can validate we're not overwriting a
document that was changed on the Cozy without our knowledge. It appears we
made a mistake in the order old revisions are returned to us by Pouch and that
we were not always fetching previous revision but usually the second known
revision. This would mean local changes on the document would not get …
=> Release v3.16.2-beta.3

gui/js/updater.window.js, test/unit/gui/updater.window.js
When we reach the update check timeout, we mark the update as skipped.
This is done so we won't offer to update while we've just started the
initial scan and risk stopping it.
However, this means that the next time we check for an update (i.e.
about 24 hours later), we will skip the update if it is available.
To avoid skipping later updates, we can make sure that
`checkForUpdates()` resets the `skipped` property so any available
update won't be skipped by default.
=> gui/js/updater.window: Reset skipped on update check

core/app.js, core/config.js, core/remote/cozy.js, core/remote/index.js, core/utils/sentry.js, test/unit/app.js
The OAuth client stored on the Cozy contains the app's version. This
is used in io.cozy.files cozyMetadata to tell which version of which
app uploaded or updated documents for example.
This could also be useful to know which versions of the app are
installed.
However, the Desktop client would not update its OAuth client after
installing a new version. This means that the version used in metadata
and available in the OAuth client is the version that was installed
when connecting the client to the Cozy.
Updating the app's version in the OAuth client is a first step towards
being able to block some versions of the Desktop client from
connecting to the Cozy by allowing us to delete OAuth clients for old
versions and force a re-connection (with an app update).
We also take this opportunity to …
=> core/app: Update client version when updating app

core/remote/cozy.js, core/remote/index.js, gui/main.js
The connected devices list in the Settings of the Cozy includes the
date of the last successful synchronization for each client.
The Desktop client was not updating it thus leaving it blank for all
devices.
We're now updating this date whenever the Cozy is up-to-date from the
Desktop's point of view.
This means that either there were no changes to synchronize or all
changes, either from the Cozy or the computer, were propagated to
the other side.
=> core: Update last sync date when Cozy is up-to-date

CHANGELOG.md, package.json
- We found out that if you encountered a network timeout during the
release availability check, we would stop alerting you whenever a
new release is available unless you'd restart the app.
We're now making sure that each successful availability check
(we're running a check every 24 hours) we'll offer you to install
any update.
- In case you encounter an error such as a synchronization error,
we're now making sure you'll get notified only once and not every
time you open the application window.
- If you look at the Settings application on your Cozy, you will list
is Connected Devices tab. This page lists all clients that were ever
connected to your Cozy and were not revoked. This page also tells
you when each client was synchronized for the last time. …
=> Release v3.16.2-beta.4

CHANGELOG.md, package.json
- In some situations like unsigned Terms of Service, requests to the
remote Cozy will result in errors and the synchronization will fail.
To anticipate those, we have a poller that requests from the Cozy
required user actions and that turns them into alerts that
Cozy Desktop will show you. A technical error in the poller resulted
in failure to schedule polls past the first one and you would miss
those very precious information unless you would restart the
application.
You should now be shown those alerts as early as possible without
restarting the application thus enabling you to anticipate
synchronization errors.
- With version 3.16.1 of the app, we decided to increase the
visibility of the synchronization activity especially during the
upload of large files …
=> Release v3.16.2

core/remote/cozy.js, core/remote/watcher/index.js, core/sync.js, test/unit/remote/cozy.js, test/unit/remote/watcher.js
We can fail to merge some changes for various reasons that are not
definitive.
For example, we could encounter very brief network issues or the
remote changes can be in an order that prevents some of them to be
merged (i.e. we have merged the creation of their parent folder yet).
The order issue should not happen in theory since we order the changes
prior to merging them but we know that in some cases, we fail to
correctly order all changes, especially when there's a lot of them
(like during the first synchronisation on a new device).
We decided to implement a similar retry process than the one done
during the propagation of merged changes by pushing to the end of the
list changes which we've failed to merge.
We hope that later changes will make it possible to merge the earlier
ones (e.g. …
=> core/remote/watcher: Retry failed changes merge

CHANGELOG.md, package.json
- Merging multiple changes at once often requires that they are in the
correct order (i.e. the order in which they were made) or we might
not be able to merge some of them. We don't always get those changes
in the correct order from the Cozy and this can block the
synchronization although we have all the required changes in the
list.
We introduced a retry mechanism in this part of the application that
will put any change that we failed to merge at the end of the list
so we can retry after we've merged the others and thus potentially
unlock the situation.
=> Release v3.17.0-beta.1

core/utils/logger.js, core/utils/sentry.js, test/unit/utils/sentry.js
A lot of errors that are sent to Sentry don't have the required
fingerprinting attributes for Sentry to group them together and their
messages differ slightly with file paths, request domains or other
dynamic elements in system calls or network requests.
This generates a lot of noise in our Sentry dashboard, especially for
network requests as those events happen quite often and are not
grouped together at the moment.
To have Sentry group those events, we make sure that every exception
reported will have the appropriate `type` and `message` so they get
grouped together while still retaining the important dynamic parts in
other fields which will get attached to each individual event.
This requires some changes in the bunyan error serializer since the
standard serializer removes a lot of …
=> core/utils/sentry: Format errors to help grouping

test/unit/local/atom/dispatch.js
When running this unit tests file enough (or maybe on resources
constrained device like Travis), we can end up with some tests failing
because the expected built document has a different update time than
the one created by `dispatch`.
This is actually unexpected that those tests would not fail more often
since we build the expected document's update time depends on its
build time while the tested document's update time comes from the
event pushed into the events channel.
By setting the event's update time with the same value than the one
used when building the expected document we can make sure those values
will be the same when comparing the 2 documents.
=> test/unit/local/atom/dispatch: Harden tests

.appveyor.yml, .travis.yml, package.json
We want to be able to use the `stream.pipeline` method which is
available only starting with Node v10.0.0.
If we don't force the Node engine's version to at least 10.0.0,
`eslint` will complain when using this method.
=> deps: Force Node version to 10.0.0+

core/local/index.js, test/support/builders/stream.js, test/unit/local/index.js
When downloading a file from the remote Cozy, we create a reading
stream from the distant file that we pipe into a writing stream to the
local destination.
We already handle writing errors on the writing stream but we don't
handle reading errors on the reading stream.
This means that the most common errors during downloads (i.e. network
errors) are not caught and will break the synchronization process
without ever noticing the user.
The synchronization would only get back to normal after restarting the
application.
By catching those errors, we let the synchronization process continue,
retrying up to 2 times when catching network errors and notifying the
user of an incomplete synchronization if we couldn't successfully
download the file.
With this change, we want to be able to simulate …
=> core/local/index: Catch streaming read errors

CHANGELOG.md, package.json
- We found out that errors while downloading a file from the remote Cozy (mostly
network errors which are quite common) were not handled at all. The result was
that the synchronization was stopped without notice (not even an error message
in the status bar) and would only work again after restarting the application.
We now catch them so the synchronization won't get completely blocked, we'll
wait for an internet connection to come back in the event of network errors
and we'll try downloading the file up to 3 times before giving up.
=> Release v3.17.0-beta.2

CHANGELOG.md, package.json
- Merging multiple changes at once often requires that they are in the
correct order (i.e. the order in which they were made) or we might
not be able to merge some of them. We don't always get those changes
in the correct order from the Cozy and this can block the
synchronization although we have all the required changes in the
list.
We introduced a retry mechanism in this part of the application that
will put any change that we failed to merge at the end of the list
so we can retry after we've merged the others and thus potentially
unlock the situation.
- We found out that errors while downloading a file from the remote
Cozy (mostly network errors which are quite common) were not handled
at all. The result was that the synchronization was stopped without …
=> Release v3.17.0

core/remote/change.js, test/unit/remote/change.js, test/unit/remote/watcher.js
We've recently added a retry mechanism to the remote watcher so that
we'll try again to merge changes that could not be merged the first
time (or any subsequent time until we stop retrying).
We did so mostly to mitigate some sorting issues where we end up with
changes for documents before the creation change of their parent
folder.
However, there are other cases where the order of changes matters and
the wrong order will create issues that cannot be mitigated by the
retry mechanism.
For example, if a file is replaced by another one, we'll have 2
changes that need to be applied in this very order to avoid conflicts:
- a `FileTrashing` change for the previous version
- a `FileAddition` change with the new version
Since we've tried countless times to improve the sorting algorithm bit
by bit …
=> core/remote/change: New changes sorting algorithm

core/config.js, core/pouch/error.js, core/pouch/migrations.js, core/remote/cozy.js, core/utils/win_registry.js
Some of our custom errors are created via simple functions which do
not properly inherit from the Error prototype.
This means that when those errors are caught and sent to Sentry,
Sentry finds them to be "Non-Error exception captured with keys:
message, name" instead of the custom error type we expect.
To help better triage those errors, we can use the `class` construct
to properly extend `Error` and have the expected error reports.
Besides, we use the V8 `Error.captureStackTrace` function to keep a
proper stack trace for our custom errors.
=> core: Create proper custom error objects

gui/elm/Window/Tray.elm, gui/elm/Window/Tray/Settings.elm
When clicking on the manual synchronization button in the Settings
pane, we send a message to the main thread to restart in the Sync
flow.
However, until we receive the first status update back from the
synchronization process, the button stays enabled and we can
mistakenly request more manual synchronizations (e.g. by
double/triple/... clicking the button).
This can potentially lead to mistakes during the triggered initial
scan and should be avoided.
We introduce a new field in the Settings model that keeps track of
manual synchronizations. It gets updated when we click the button and
when we receive an up-to-date status back from the synchronization
process.
=> gui/elm: Disable manual sync after first click

core/local/index.js, core/remote/constants.js, test/unit/local/index.js
Since the introduction of the Cozy Notes application, we've started
synchronizing their markdown version on users' desktops.
The problem is, those version are not meant to be modified as they're
just a markdown export of the actual Note and modifications made on
those files with any application other than Cozy Notes won't be
reflected on the Note stored in the Cozy.
To avoid situations where users modify those files and lose content or
just don't find it on their Cozy, we've decided to use file system
permissions to show those files should not be modified.
Users can still change the permissions but we find this is a good
warning while we add the capacity to open Notes from the file system
(i.e. we'll launch the Cozy Notes application for that).
Warning: This behavior is based on the …
=> core: Mark local versions of Notes as read-only

core/app.js, core/sync.js, gui/main.js, test/unit/sync.js
The PouchDB views and migrations are setup during the start of the
Sync module. This seemed appropriate as this would make sure the DB
was ready before launching the watchers.
However, we've since reused the `Sync#start()` method to run manual
synchronizations. This means that views are created and migrations run
every time users click the manual synchronization button.
Even if these should not have any effects after the first run, it
seems risky and unnecessary to run them at this point.
It seems reasonable to do these actions during the application setup
which will happen before the synchronization is started.
=> core/sync: Don't setup Pouch during manual sync

core/app.js, core/sync.js, gui/js/tray.window.js, gui/main.js, test/integration/update.js, test/support/helpers/index.js, test/unit/regressions/850.js, test/unit/sync.js
The way the synchronization is stopped at the moment does not properly
end infinite loops that take care of waiting for changes either local
or remote.
This is an issue especially when requesting a manual synchronization
as it works by stopping the current synchronization and starting a new
one. If the former is not completely stopped, we can end up with
multiple loops working on changes making for unpredictable behavior.
We also suspect that this may cause errors when trying to disconnect
the client from the Cozy with a process still using the PouchDB logs
file while trying to remove it.
We now use a promise that resolves when we call the `Sync#stop()`
method and we race it again synchronization promises so we can know
when to break out of the loops.
Please make sure the following boxes …
=> core/sync: Properly stop synchronizations

core/app.js, core/config.js, core/sync.js, gui/main.js, test/unit/config.js, test/unit/sync.js
We used to give users the ability to choose whether they wanted to:
- synchronize their Cozy with their computer (i.e. `full` mode)
- backup their computer to their Cozy (i.e. `push` mode)
- backup their Cozy to their computer (i.e. `pull` mode)
We have removed this ability a long time ago and it's time to remove
these modes from the code since we don't expect to use them again
soon.
=> core/sync: Remove unused synchronization modes

core/local/chokidar/local_change.js, core/local/chokidar/send_to_prep.js, core/local/index.js, core/merge.js, core/sync.js, test/integration/conflict_resolution.js, test/integration/interrupted_sync.js, test/unit/local/chokidar/analysis.js, test/unit/merge.js
When starting Cozy Desktop, we gather and merge local changes then
remote changes and last we try to synchronize them.
This can create issues when the same document was modified both
locally and remotely.
So, to avoid loosing data, we decided to rename the document with a
conflict suffix on the side that would overwrite the existing
document. In the case of a startup sync, this would be the remote
side.
However, if the application was stopped right after a remote update
was merged and before it was propagated to the local file system, when
starting it up again, we'll wrongly detect a local update (i.e. the
local version does not reflect the remote version and its Pouch
representation). In this case, the conflict resolution would happen on
the local file system, thus generating a local …
=> core/merge: Don't override unsynced file updates

CHANGELOG.md, package.json
- As a follow-up to the manual synchronization button changes, we've
worked on the underlying synchronization stop requests to make sure
every component involved in the synchronization process is stopped
prior to starting a new process.
This means that we should not see problems coming from manual
synchronizations anymore but also that some actions that involve
stopping or deleting the PouchDB database will wait for the
completion of the current synchronization and thus may take longer.
This does not affect stopping the client.
- We've found out that some remote file updates (i.e. pushed by
another client) may be lost during a client restart (actually they
can now be recovered via the versions management) if they were
detected by the client but not propagated …
=> Release v3.18.0-beta.2

CHANGELOG.md, package.json
- We've completely changed our sorting algorithm for changes coming
from the Cozy. We may not receive changes in the order they were
made and this can make their application on the local file system
impossible. To mitigate this situation we sort the changes to make
their application possible. It is a difficult task and we've made a
lot of changes in the past to try and fix bugs in different
situations.
We've yet again seen new problematic situations recently and decided
to try a new approach with a completely new algorithm, focusing more
on essential changes that need to happen first rather than trying to
recreate the very specific order in which changes were made.
- We've noticed that when requesting a manual synchronization, the
button is not disabled right …
=> Release v3.18.0

core/config.js, core/remote/cozy.js, core/remote/index.js, package.json, test/unit/config.js, test/unit/remote/cozy.js, yarn.lock
We'll need to know if a Cozy uses flat or nested subdomains to address
applications so we can open Cozy Notes on the user's Cozy.
This information is stored in the instance's capabilities part of the
settings and can be access via the `/settings/capabilities` route.
Since those settings should not change very often, we can avoid making
making a request each time we want to know if an instance uses flat or
nested subdomain by storing it in the Desktop client's config.
Now that we can store the flat/nested subdomains capabilities of the
remote Cozy, we need a way to get the information.
The `/settings/capabilities` route is accessible via the `cozy-client`
package but not via the `cozy-client-js` package that we already use.
Since `cozy-client-js` is deprecated, we won't add this route to …
=> core: Get instance subdomains capabilities

build/launcher-script.sh, build/vnd.cozy.note+markdown.xml, electron-builder.yml
Create a file association on the user's computer via the
`electron-builder` configuration.
This will create the `text/vnd.cozy.note+markdown` MIME type on macOS
and Windows and will set Cozy Desktop as the default application to
open files with the `cozy-note` extension.
On Linux, since we don't install the application but hand an
executable, we need to create the MIME type by hand by putting a
declaration file in the local MIME types database.
The association will only work if a `desktop` file with the right MIME
type association points to the Desktop app. This is done automatically
if using `appimaged`.
=> tools: Associate `.cozy-note` files with Desktop

core/local/chokidar/prepare_events.js, test/scenarios/create_accentuated_file_in_accentued_dir/with_different_encodings/remote/changes.json, test/scenarios/create_accentuated_file_in_accentued_dir/with_different_encodings/scenario.js, test/scenarios/create_accentuated_file_in_accentued_dir/with_same_encoding/remote/changes.json, test/scenarios/create_accentuated_file_in_accentued_dir/with_same_encoding/scenario.js
When synchronizing a remotely added document with a path containing
utf-8 characters on an HFS+ file system, we have to take care of the
re-normalization done by the file system itself (i.e. it renames the
document with `NFD` normalized path.
To avoid treating those renames as normal movements (invalid since
they give the same PouchDB document id via the `NFD` normalization
done to get the id of documents on macOS), we check if an existing
document with the same equivalent path exists in PouchDB and if so, we
normalize our document path with `NFC` to make sure it won't trigger a
rename action if it is strictly equal to the existing path.
However, this only works if the entire existing PouchDB document's
path is normalized with `NFC`.
We have encountered cases where the remote document …
=> core/local/chokidar: Reuse non-NFC path on HFS+

core/sync.js
When we encounter an error while applying a change, we check if it is
a known error in which case we log it and take the appropriate action.
However, in all other cases, we don't log the error at all which makes
it really hard to debug.
=> core/sync: Log all kinds of errors

gui/notes/index.js, test/unit/gui/notes/index.js
The Cozy Notes web application is only routing to the public view of a
note if the path ends with a `/`.
Otherwise the assets won't be loaded and the note won't be displayed.
=> gui/notes: Fix public notes route path

CHANGELOG.md, package.json
- A new Cozy Notes application was released recently, allowing you to
create `cozy-note` documents. Those are automatically exported to a
markdown format and stored in your Drive so that it can be
synchronized with all your devices.
Those files cannot be modified directly as it would break their
format. To allow you to easily open and modify them we've set
Cozy Desktop as the default application to open them. Opening a
`cozy-note` file locally with Cozy Desktop installed (or run at
least once on Linux) will open in the Cozy Notes web application in
your browser even if it's a note that was shared with you. If you're
not connected to the Internet or we cannot find the note on its
owner's Cozy, we'll show its content in a downgraded rendered
markdown form. …
=> Release v3.19.0-beta.1

core/merge.js, core/pouch/migrations.js, core/sync.js, test/integration/move.js
Cozy Desktop v3.18.0 introduced a mechanism to avoid losing remote updates on files when they were merged but not applied on the local file system.
This mechanism uses the `overwrite` attribute which was previously only used for movements which should overwrite the destination. A loophole in our new algorithm created issues when mixing file updates and movements.
Our solution to this problem is to remove the `overwrite` attribute after we've successfully synced the associated change or when we're creating child moves since the destination might not exist already (and this part will be handled via the `overwrite` attribute on the parent being moved).
=> Fix collision between file move and update

core/app.js, core/sync.js, test/unit/app.js
We don't always use async/await calls for `App.stopSync()` and thus
its return value is not automatically converted into a resolved
Promise.
This prevents the auto-update process from restarting the application
after the update was applied since we've moved the App setup after the
update process.
=> core/app: Always return a Promise from `stopSync`

gui/main.js
We were always closing the app after opening a note or closing one markdown viewer window even if we had other windows opened or the app was in Sync mode (i.e. it was started on itself and notes were opened later).
=> gui/main: Fix opening notes on macos

CHANGELOG.md, package.json
- We introduced a regression around auto-updates with the opening of
notes. The application would not be restarted after the update was
downloaded and installed.
This is now fixed and updates are now fully applied again.
- On macOS, opening a note while the application was already started
and syncing would close it and closing one of multiple markdown
viewer windows would close all of them. Also the synchronization
process would be started even when
launching the app just to open a note. The behavior is now the same
as on the other two OSes. Opening a note while the app is not
started will not start the synchronization, opening it while the app
is started will not close it and closing one markdown viewer window
will not close all of them if more than one are …
=> Release v3.19.0-beta.3

core/local/atom/producer.js, core/local/atom/watcher.js, test/unit/local/atom/producer.js, test/unit/local/atom/watcher.js
We would not catch errors coming from the producer during the `start` phase.
This is an issue since we use Promises and those errors will stop the initial scan while we're not aware of it.
Besides, an error coming from one path should not stop the producer and prevent it from analyzing the rest of the synchronized folder.
=> core/local/atom/watcher: Catch producer errors

CHANGELOG.md, package.json
- We found out that revoking your device from the Connected Devices
page in your Cozy Settings would trigger an error in the
Cozy Desktop application preventing it from finishing the
disconnection.
From now on, when you choose to disconnect the application following
the device revocation (i.e. choosing `Disconnect` in the modal
window that shows up when the application detects it's been revoked)
will bring you back to the on-boarding process so you can reconnect
it if you want.
NB: On Windows, another issue is still preventing you from
disconnecting the application completely.
Improvements for Linux and Windows users:
- We found out that system errors triggered while trying to read the
content of one of your directories during the application start
would not be …
=> Release v3.19.0-beta.4

gui/locales/de.json, gui/locales/en.json, gui/locales/eo.json, gui/locales/es.json, gui/locales/fr.json, gui/locales/it_IT.json, gui/locales/ja.json, gui/locales/nl.json, gui/locales/nl_NL.json, gui/locales/pl.json, gui/locales/sq.json, gui/locales/zh_CN.json, gui/main.js
When we detect the OAuth client has been revoked, we offer the user to
fully disconnect Cozy Desktop from her Cozy and we restart the
application.
Doing so, the user is presented with the on-boarding process again.
To better reflect this behavior, we changed the button label to
"Reconnect". We believe users that disconnect their Cozy mostly do so
to reinitialize their app or by mistake.
=> gui/main: Change reconnection button label

CHANGELOG.md, package.json
- We found out that revoking your device from the Connected Devices
page in your Cozy Settings would trigger an error in the
Cozy Desktop application preventing it from finishing the
disconnection.
From now on, when you choose to disconnect the application following
the device revocation (i.e. choosing `Disconnect` in the modal
window that shows up when the application detects it's been revoked)
will bring you back to the on-boarding process so you can reconnect
it if you want.
NB: On Windows, another issue is still preventing you from
disconnecting the application completely.
- A new Cozy Notes application was released recently, allowing you to
create `cozy-note` documents. Those are automatically exported to a
markdown format and stored in your Drive so that …
=> Release v3.19.0

core/local/atom/add_infos.js, core/local/atom/fire_local_start_event.js, core/local/atom/initial_diff.js, core/metadata.js
In some situations, the stats returned by the file system for a given
path don't contain a type (i.e. file, directory, symbolic link…).
This means that we won't know what kind of action to apply on
documents generated by events for this path.
We decided a while ago to default the event kind for such paths to
`file` in the hope we could reduce the amount of situations where the
kind is unknown or wrong.
However, some users already have Pouch documents without doctypes so
we have to use a default value when inferring the event kind from it
(i.e. during the initial diff when we created `deleted` events for
documents we couldn't match with a file or directory on the file
system).
We'll use the same default type of `file`.
=> core/local/atom: Default event kind to file

gui/notes/index.js, package.json, test/unit/gui/notes/index.js, yarn.lock
The `computeUrl` method has been copied into `cozy-client` and can
thus be replaced by a call to the new `fetchURL` method.
=> gui/notes: Use `fetchURL` from the cozy-client note model

.travis.yml
Homebrew has updated its CouchDB cask version so it now downloads
version 3.0.0.
However, this version does not seem to work in our Travis macOS builds
so this forces a manual download of version 2.3.1 so we can get our
builds to pass again.
=> travis: Manually download CouchDB 2.3.1 on macOS

core/local/atom/initial_diff.js, test/unit/local/atom/initial_diff.js
When propagating the deletion of a folder to the remote Cozy, we
trash it and then, if it's empty, completely remove it from the trash.
The idea behind this is to keep the hierarchy leading to deleted files
in the trash (this is not true all the time so we should probably
revise this at some point).
This means that if a folder is not empty because we're trying to
propagate its deletion before propagating the deletion of its
empty children folders, we'll end up with a bunch empty folders in the
trash.
This behavior can be seen easily when deleting a folder while the
client is stopped because we'll fire `deleted` events in the path
order so the parent folder will be deleted before its children (their
paths are longer and start with their parent's path).
To get a reproducible behavior in …
=> atom/initial_diff: Delete missing children before parents

core/local/atom/win_detect_move.js, core/utils/sorted_set.js, test/unit/local/atom/win_detect_move.js
In some situations like the overwriting move of a directory, the
`deleted` event for the movement source will be fired after the
`created` event for the destination so we need to be able to match a
`deleted` event with a previously received `created` event.
We also need to keep track of pending events across batches in case
both events aren't fired in the same batch.
With this change, all `created` events on Windows will be withheld for
1 second so we can potentially match it with a `deleted` event that
would come later.
Maybe we could improve this by withholding only `created` events with
a known inode or fileid (i.e. we'd look for a document in PouchDB with
the event's inode or fileid).
=> atom/win_detect_move: Fix moves detection

core/local/atom/win_detect_move.js
Stop exporting private `previousPaths` method so that arguments types
are not required by the linter.
=> atom/win_detect_move: Fix lint issue

CHANGELOG.md, package.json
- In an attempt to avoid losing your data, we were very cautious when
we detected movements that would overwrite documents we were aware
of and would create a conflict document instead. There are a number
of situations where this is not ideal because you actually wanted to
overwrite this destination document (e.g. saving a file from an
office software which uses a temporary file, overwriting a directory
on purpose).
With all the safeties we have in place today (i.e. trash bins on
both your computer and your Cozy plus file versioning on your Cozy)
we decided to accept more overwriting movements when we did not
detect un-synchronized changes that would be overwritten by this.
This should mean a lot less conflicts when using Microsoft Office
softwares and the …
=> Release v3.20.0-beta.1

core/sync.js, test/integration/platform_incompatibilities.js
If a document with incompatibilities is moved locally (i.e. via one of
its ancestors) we should propagate the movement to the remote Cozy and
not transform it into an addition because the document exists on the
Cozy and not on the local file system (we'd end up with an error
because the file could not be read and the Cozy would reject the
addition anyway).
We'll still transform the remote movements of documents with platform
incompatibilities into additions since the document does not exist on
the local filesystem and therefore could not be moved.
=> sync: Propagate move with incompatibilites to Cozy

core/local/index.js, core/remote/index.js, core/sync.js, test/unit/local/index.js
The local side emits `delete-file` events for each file or folder that
was trashed so that we can update the Recent files list in the main
app window but the remote side would not.
Besides, the responsibility for emitting those events rested with the
local and remote sides while other sync events are rightfully emitted
by the Sync itself so this event is now emitted by the Sync as well
whenever necessary.
=> core/sync: Emit `delete-file` event after trash

test/scenarios/move_and_update_file/local/darwin.json
On macOS, since file system events are buffered and can be flushed
pretty much at any time we run our scenarios for different flushing
points (or breakpoints) in the captures.
However, some breakpoints would clearly not not give us the expected
behavior and should be completely different tests altogether so we can
select the ones that should give us the tested behavior.
We just selected some breakpoints for the
`test/scenarios/move_and_update_file` scenario.
=> scenarios: Test meaningful breakpoints on macOS

core/merge.js, test/unit/merge.js
Each action is quite complex with a lot of different behaviors
depending on several conditions.
Those conditional blocks were intertwined and it was hard to determine
what behavior was to be expected in different situations.
This is an attempt at simplifying those blocks with early returns and
a bit of duplication to keep related statements close to each other.
=> core/merge: Simplify conditional blocks

core/pouch/index.js
To help debug those errors and find them using our `jq`'s path filter,
we need to log the `path` attribute of the document we couldn't save.
=> core/pouch: Log doc's path with bulkDocs errors

electron-builder.yml
As stipulated in the Electron documentation about application
packaging, files are packaged by default into an `asar` archive to
speed up some require calls and prevent path name length issues on
Windows.
However, some Node API calls do not work with packed files and need to
unpack them first. This is the case for native extensions (i.e.
`.node` files) and this operation can trigger antiviruses, thus
throwing exceptions (see https://www.electronjs.org/docs/tutorial/application-packaging#adding-unpacked-files-to-asar-archives).
We believe some of our users can be experiencing those issues and as a
workaround, we propose to not pack (or unpack in Electron terms) the
native extensions when building the application.
=> build: Unpack native extensions

gui/main.js
The `main` module is responsible for instantiating the synchronization
process and thus all its sub-modules (i.e. watchers and sync mainly)
once the proxy and config and set.
With the different states in which the app can be started (i.e. not
connected to a Cozy, waiting for an update, already connected, opening
a note…), we have different paths leading to an instantiation.
However, we should not ever instantiate the app more than once or we
could see multiple instances of the local watcher running and maybe
different processes accessing the PouchDB database file.
Unfortunately, we were instantiating the sync twice in case the client
was already connected to a Cozy and running in normal, synchronization
mode.
=> gui/main: Instanciate sync only once

core/config/.cozyignore, test/unit/ignore.js
We want to make sure all temporary files created by a Microsoft Office
software are ignored to avoid synchronizing them and later detect a
movement instead of a file update when the edited file is saved.
We were ignoring temporary files for `.doc*`, `.xls*` and `.ppt*`
documents only (i.e. and not the open document types).
=> .cozyignore: Ignore all Microsoft Office tmp files

.travis.yml
- Upgrades CouchDB to 2.3.1 on linux
- Upgrades Golang to 1.14
=> ci/travis: Upgrade CouchDB and Golang

core/remote/cozy.js
We have 2 different methods in `cozy-client` to build a new
`CozyClient` object from an old one created by `cozy-client-js`.
We call one or the other if the old client was either an OAuth client
or a Token based client.
To make the difference between both, we can check if the `_oauth`
attribute is set to `true`.
Unfortunately, we were checking the value of `oauth` so we were always
calling the function for Token based clients.
=> core/remote: Fix typo in newClient condition

gui/locales/fr.json, gui/styles/_updater.styl
The updater window is a lot smaller than anticipated when doing the
redesign and not everything would fit into the window, especially in
French.
So the spinner has been shrinked down to give more room for the text 
and the French text for "please wait" is smaller so it can fit in 
one line.
=> gui: Shrink new updater design

CHANGELOG.md, package.json
- The updater window was smaller than anticipated when bringing the
window redesign to life so all the content would not fit inside,
especially with French text. The spinner has been shrinked down to
leave more room for the text and the French translation modified so
that the first sentence would fit in one line.
=> Release v3.20.0-beta.6

core/merge.js, test/integration/move.js, test/unit/merge.js
When a document is moved to an ignored path on the local filesystem,
we want to trash it on the remote Cozy and stop synchronizing changes
made on either side.
However, when the document is moved to a non ignored location before
being moved to the ignored path without a synchronization between the
2, the Sync picks up the move hint of the first move and propagates it
to the remote Cozy instead of the deletion.
We can make sure this does not happen by removing any move hint (i.e.
the `moveFrom` attribute) on its PouchDB record when we decide to
delete a document.
=> core/merge: Deleting ignored doc removes move hint

core/local/chokidar/initial_scan.js, core/merge.js, core/prep.js, core/sync.js, test/integration/trash.js, test/unit/local/chokidar/initial_scan.js, test/unit/merge.js, test/unit/prep.js
We believe users expect the path of their documents to be their
identifier and thus that deleting a file on one side while it was
moved on the other should not result in the file being deleted since
its path has changed.
To meet those expectations, we undo the trashing/deletion of files
when we detect they have been moved on the other side.
We note that when we merge the local deletion of a file before we
merge its remote movement, we cannot undo the merged trashing since
the PouchDB record has been erased.
However, the local deletion is not propagated to the remote Cozy
thanks to the movement updating the remote revision of the document
and thus implying a rejected trashing.
This situation can be stabilized once we'll have deletion markers
since we'll be able to fetch the deleted record …
=> core/merge: Don't trash file moved on other side

core/local/atom/add_infos.js, core/local/atom/dispatch.js, core/local/atom/incomplete_fixer.js, core/local/atom/initial_diff.js, core/local/atom/win_detect_move.js, core/local/atom/win_identical_renaming.js, core/local/chokidar/initial_scan.js, core/local/chokidar/prepare_events.js, core/merge.js, core/metadata.js, core/remote/index.js, core/sync.js, gui/notes/index.js, test/integration/move.js, test/integration/permanent_deletion.js, test/integration/trash.js, test/scenarios/move_overwriting_dir/not_trashed/atom/linux.json, test/scenarios/move_overwriting_dir/not_trashed/local/darwin.json, test/scenarios/move_overwriting_dir/not_trashed/scenario.js, test/unit/merge.js, test/unit/remote/index.js, test/unit/sync.js
Until now, when we detected the deletion of a document either on the
local file system or the remote Cozy, we would merge it by deleting
it from the PouchDB database.
Then, The Sync module would detect that change via the PouchDB changes
feed and propagate it.
However, deleted documents in PouchDB cannot be queried by `get()`.
Also, when multiple modifications are made to the same document (i.e.
saved with the same `_id` attribute), the changes feed will return
only the latest version of the document.
Those 2 "restrictions" make merging some changes harder. For example:
- the remote addition of files or folders into a locally deleted
folder (i.e. the parent folder can't be queried so it's "missing")
- the deletion and creation of a file at the same path/_id (i.e. we
lose the _rev of the …
=> core/merge: Mark documents for deletion

core/app.js, core/local/atom/add_infos.js, core/local/atom/dispatch.js, core/local/atom/incomplete_fixer.js, core/local/atom/initial_diff.js, core/local/atom/win_detect_move.js, core/local/atom/win_identical_renaming.js, core/local/chokidar/initial_scan.js, core/local/chokidar/prepare_events.js, core/local/chokidar/send_to_prep.js, core/local/index.js, core/merge.js, core/pouch/migrations.js, core/prep.js, core/remote/change.js, core/remote/watcher/index.js, core/sync.js, test/integration/trash.js, test/scenarios/index.js, test/scenarios/restore/scenario.js, test/support/helpers/scenarios.js
We were processing the restoration of files and folders from the
remote trash separately from the addition of files and folders while
we can actually treat them the same way since, from the Desktop
client's point of view, they're the same.
This removes some unnecessary code and should help us simplify how we
handle trashing elements by using one `trashed` attributes regardless
of whether the deletion happened on the local filesystem or the remote
Cozy.
=> core/remote: Treat restore changes as additions

core/local/atom/watcher.js, core/remote/index.js, core/remote/watcher/index.js, core/sync.js, core/utils/lifecycle.js, gui/main.js, test/support/helpers/index.js, test/unit/remote/offline.js, test/unit/remote/watcher.js, test/unit/sync.js
We found out that we were not catching all errors coming from the remote watcher thus not alerting the user and not completely stopping the synchronization process.
We want to make sure this does not happen anymore and that other similar situations cannot happen.
To do so, we need to move away from the complex lifecycle management we have today in the watchers and sync modules.
=> core: Refactor sync modules lifecycle management

CHANGELOG.md, package.json
- Moving a document to an ignored location (see
https://github.com/cozy-labs/cozy-desktop/blob/master/core/config/.cozyignore
and your local `.cozyignore` rules file) after another move would
result in the first move being propagated to the remote Cozy and the
document being desynchronized after that.
From now on, the second move to the ignored location will cancel the
first move and the client will correctly propagate a deletion to the
remote Cozy.
- Deleting a file on your Cozy while moving it on your local
filesystem with your client stopped would lead to the
desynchronisation of the file. It would be deleted on your Cozy but
would still exist on your local filesystem and all later
modifications would not be propagated.
We're now refusing the deletion …
=> Release v3.21.0-beta.1

core/remote/watcher/index.js, test/support/builders/metadata/base.js, test/unit/remote/watcher.js
Since we introduced the deletion marker, documents that were trashed
on the remote Cozy and restored before the deletion could be applied
on the local filesystem (i.e. the new version of the PouchDB record
has been merged with the marker but the document still exists) would
be considered as moved instead of being considered as added.
We missed a condition in the remote watcher where we needed to check
for the presence of the marker because we were checking for the
presence of a `trashed` attribute.
However, this attribute does not have the same meaning and would
actually not be present on any record in the PouchDB database since
it's a remote CouchDB attribute set on trashed documents.
=> core/remote/watcher: Restored docs are always added

CHANGELOG.md, package.json
- We missed a spot when introducing the deletion marker in the
previous beta release which could lead to remote restorations being
handled as movements if the previous deletion was merged into the
local PouchDB database but not propagated to the local filesystem.
We haven't identified visible issues coming from this yet though.
=> Release v3.21.0-beta.2

core/local/index.js, test/integration/update.js, test/support/builders/remote/file.js, test/support/helpers/cozy.js
To prevent users from breaking their Cozy Notes by updating them
locally, we decided to make their backup files read-only on the local
filesystem so that users would have to knowingly save any updates.
However, on Windows, this mechanism prevents us from overwriting a
backup file with a new remote version because our process doesn't have
write permissions either.
To circumvent this limitation, we temporarily add back write
permissions on Cozy Notes backup files when we are about to overwrite
them with a new version.
=> core/local: Accept remote Notes updates on Windows

dev/remote/generate-test-env.js
When using the `bootstrap:remote` command outside any CI environment,
the Cozy URL defaults to `https://cozy.tools.8080` but there are
situations where we might want to choose another URL instead (e.g.
when running tests on Windows where we can't use the dockerized
stack).
=> dev/remote: Accept COZY_URL variable for bootstrap

core/pouch/index.js, test/support/helpers/pouch.js, test/unit/pouch.js, test/unit/pouch/migrations.js, test/unit/remote/watcher.js
We found out that when merging a folder move, we could create new
PouchDB records based on records for documents that were not children
of the moved folder.
The source cause of this issue was that the `Pouch.byRecursivePath()`
method would list records whose `_id` started with the moved folder's
`_id` but not necessarily because their associated documents were in
the folder but because they were in a folder who had the same parent
as the moved folder and whose name would start with the moved folder's
name.
E.g. with the given hierarchy:
- `dir/file`
- `dir 2/subdir/subfile`
`Pouch.byRecursivePath('dir')` would list `dir` and `dir/file` as
expected but also `dir 2/subdir` and `dir 2/subdir/subfile`.
To know which documents to return, the method uses an inclusive
documents keys range as a …
=> core/pouch: byRecursivePath scopes results to given folder

docker-compose.yml
This is needed to get the latest cozy-stack version including the the
new document revision in `referenced_by` additions response.
Without this update, our `RemoteCozy.addReferencedBy()` method does
not work and fails tests.
=> dev: Use latest cozy-app-dev docker image version

core/metadata.js, core/utils/mime.js, test/support/builders/metadata/file.js, test/unit/metadata.js, test/unit/utils/mime.js
The Cozy Notes file extension `.cozy-note` is not a standard,
well-known, extension with its associated mime type detected by OSes
and mime lookup modules like the one we use.
This means we need to wrap our own custom lookup module around the
`mime` module so that we can return the `text/vnd.cozy.note+markdown`
mime type when the given path has a `.cozy-note` extension.
=> core/metadata: Use correct mime for Cozy Notes

test/scenarios/move_and_trash_file_from_inside_move/scenario.js
This scenario was not disabled on Windows while it won't work on this
platform as on any other platform since the Merge logic to handle it
is not in place.
=> test/scenarios: Disable scenario on all platforms

core/remote/index.js, test/unit/remote/index.js
For a long time, we've been creating the remote parent it it was
missing when creating a new folder on the remote Cozy.
This was done to simplify the creation of complex hierarchies but
erroring out here would force a retry after other changes have been
propagating and the parent would probably be created at that point.
On the other hand, trying to pro-actively create the parent can lead
to errors when the parent of a change is issued from a move since we
won't be able to synchronize the parent moved (i.e. a document would
already exist at the target location and the stack would refuse the
move).
We can see this issue in the following scenarios:
- test/scenarios/create_dir_into_moved_one/local/darwin.json flushAfter=0
- test/scenarios/move_dir_and_update_subfile/local/darwin.json …
=> core/remote: Stop creating missing remote parent

core/remote/index.js, test/unit/remote/index.js
Cozy Notes are a special kind of documents. Their content is saved in
the associated CoucDB record's metadata. The associated file document
is a markdown export of the original content.
This is what the Desktop client synchronizes on the user's filesystem,
a markdown export.
The client does not have the ability to update Notes documents at the
moment (and probably never will by itself). If a user updates on their
local filesystem the content of `.cozy-note` file, we won't be able to
update the associated Note's content.
Until now, we were allowing the propagation of such updates to the
remote Cozy, breaking in the process the actual Note because we don't
have the required metadata. From there, the only option for the user
to get a working Note back is to create a new one and paste the …
=> core/remote: Prevent updates of Notes on Cozy

core/local/index.js, core/merge.js, core/metadata.js, core/move.js, core/remote/index.js, core/writer.js, test/integration/notes.js, test/integration/update.js, test/support/helpers/context_dir.js, test/unit/helpers_merge.js, test/unit/local/index.js, test/unit/merge.js, test/unit/remote/index.js
Cozy Notes are a special kind of document. Their content lives within
their CouchDB record metadata and the associated file is only a
markdown export.
Besides, the stack is not able to re-import markdown into a Cozy Note
document for the moment.
This means that if a synchronized Cozy Note file is edited on the
user's local filesystem, we won't be able to import the new content
into the remote Cozy Note. On a side note, the client does not handle
remote records metadata so the edited CouchDB record will lose the
original Cozy Note content.
We've added some protections by forbidding the propagation of local
Note edits but this means the Note will be de-synchronized with
different contents locally and on the remote Cozy.
In case the Note is edited again, via the Cozy Note app this time, the …
=> core/merge: Create conflict on local Note edit

CHANGELOG.md, package.json
- The client would not detect the correct mime type for `.cozy-note`
files when detected on the local filesystem. This would change the
saved mime type of notes moved on the local filesystem and not show
the correct icon in the Recent changes list in our main window.
We've switched to a custom mime detector for those files to detect
our custom mime type.
- Since propagating a local file update to a remote Cozy Note would
break this note (i.e. it would not be detected as such and we would
lose its actual content while still keeping its markdown export
within the associated Cozy file), we've decided to prevent all local
note updates to be propagated to the remote Cozy.
- In order to still synchronize your local updates to notes with your
remote Cozy, we're now …
=> Release v3.21.0-beta.3

CHANGELOG.md, package.json
- Remote changes resulting in an `MergeMissingParentError` do not
block the synchronization process since v3.21.0-beta.1 but the
changes from the affected batch and the ones coming after will be
fetched over and over again until the errors are resolved, which
might never come.
We've identified a few sources of those errors that should be fixed
really soon and believe we should not encounter solvable missing
parent issues anymore so we've decided to mark them as processed
anyway and rely on the next changes to resolve those missing parents
issues.
=> Release v3.21.0-beta.4

core/local/index.js, test/integration/notes.js, test/unit/local/index.js
Synchronized Cozy Notes are a special kind of files because they're
only a markdown export of the actual Note's content.
When modifying this export, the actual Note is not updated and the
client can even break it since it won't send the entire metadata which
contains the actual content to the stack.
To help users in understanding those files should not be modified, we
thought that making them read-only would offer a good experience.
However, we've seen that some modifications can still be detected by
the Desktop client even without the user actually modifying the files
and also that the read-only limitation can be overridden by the user
anyway.
So we implemented some measures to avoid propagating those
modifications to the Cozy and create a conflicting document instead to
back up the new …
=> core/local/index: Remove Notes read-only limit

CHANGELOG.md, package.json
- The recent change we introduced to fix the propagation of remote
Cozy Notes changes to the local filesystem brought some new timing
issues. These can result in invalid metadata being sent to the
remote Cozy after propagating an update. In case the note was in a
shared directory, the metadata change is in turn propagated via the
sharing to other Cozies and we can end up with a desynchronized
note.
This new issue comes from the fact we have to add write permissions
on the local note file to let the client write the new markdown
export. The read-only protection was added to prevent local changes
that would break the actual note on the remote Cozy. Since we're now
managing those changes within the synchronization process (i.e. with
the creation of a conflict) we …
=> Release v3.21.0-beta.5

core/remote/index.js, test/support/builders/remote/base.js, test/support/builders/remote/file.js, test/support/helpers/cozy.js, test/unit/remote/cozy.js, test/unit/remote/index.js, test/unit/remote/offline.js, test/unit/remote/watcher.js
When we propagate a local overwriting move, we want to keep the
references from the overwritten document and add them to the moved
one.
We therefore apply multiple operations on the remote version of the
moved document. This means we need to update the remote revision of
our local version of the document after each operation to be able to
run the next one.
However, after adding the new references, now the last operation of
our move, we would not update the revision.
This would prevent running other operations on the remote document
until the next remote watcher cycle (which would then update the
remote revision).
We would face this issue if the moved document was also locally edited
for example.
We simply update the remote revision on our document after
transferring the references and we …
=> core/remote/index: Set rev after moving references

core/merge.js, core/metadata.js, core/move.js, core/remote/document.js, core/remote/index.js, core/utils/notes.js, test/integration/notes.js, test/support/builders/index.js, test/support/builders/remote/note.js, test/unit/move.js, test/unit/remote/index.js
We introduced 2 mechanisms to prevent users from breaking their remote
Cozy Notes:
- a local update to a Cozy Note file will not be propagated to the
remote Cozy
- a local update to a Cozy Note file will generate a conflict where
the renamed document is the remote Cozy Note and the local file is
uploaded as is (i.e. a markdown file with a `.cozy-note` extension
and a Cozy Note mime type)
Those 2 mechanisms work as expected when an actual Cozy Note export is
modified locally but they don't anymore if the resulting markdown file
is modified again.
In this situation, we'll keep creating new conflicts and if the
markdown file had not been uploaded already we'll get an error because
we'll try to rename its remote counterpart which does not exist yet.
We have this issue because we identify Cozy …
=> core: Use more attributes to identify Cozy Notes

core/local/atom/await_write_finish.js, core/local/atom/dispatch.js, core/sync.js, test/scenarios/move_and_update_file/scenario.js, test/unit/local/atom/await_write_finish.js, test/unit/local/atom/dispatch.js
When we propagate remote changes to the local filesystem, the local watcher will receive events from the filesystem and try to merge those "changes".
In some situations like when a Cozy Note was moved and updated, we end up reverting the changes we are applying.
We try to be smarter about the local changes in 2 ways:
- be more aggressive in the way we aggregate events in the Atom watcher to limit irrelevant changes
- try and detect already applied moves to that we don't merge creations when dispatching local `renamed` events with no source PouchDB records
=> core/local: Discard changes from remote propagation

CHANGELOG.md, package.json
- The local Cozy Notes edit protection (i.e. notes were marked as
read-only) was generating a new conflict every time the note was
modified on the remote Cozy.
Those conflicts originating from the change of permissions to write
the new version, we decided to stop marking notes as read-only. The
conflict mechanism should be enough to protect remote Cozy Notes
from being broken by a local edit.
- If a Cozy Note was moved and updated while a client was offline, the
propagation to the local filesystem of these changes would lead to
the creation of a conflicting markdown file and the renaming of the
remote note with a conflict suffix.
We made sure that applying more than one change on the same document
on the filesystem will …
=> Release v3.21.0-beta.6

core/merge.js, core/metadata.js, test/unit/merge.js
When we detect a local Cozy Note export modification and create a
conflict, we want to mark the new markdown file as such and not a real
Cozy Note.
We won't change the file's extension in case the file is still open in
the user's editor and so we won't change the document's mime type
either. However, we'll remove the Cozy Note's content and schema
stored in the record's `metadata` attribute since the actual file's
content has changed and won't be re-imported as a Note.
Removing these attributes should give Drive Web hints that the file
should be displayed as a markdown file.
=> core/merge: Remove Note metadata on conflicts

core/merge.js, core/pouch/migrations.js
The new Desktop release fixes a bug which lead to local Cozy Note exports not being updated on Windows when propagating a remote note update and the creation of a conflict when detecting a local modification on local exports to avoid breaking the remote note.
The association of the 2 would lead to the generation of conflicts for all exports that became unsynchronized because of the bug on Windows.
We want to avoid those dispensable conflicts and propose to rely on the unapplied remote update detection to forcefully download and replace the local export with the remote version.
We add a migration that fakes a remote update on all Cozy Note PouchDB records so that `Merge` will detect them and choose to discard the local modification it will receive from the initial scan after the release …
=> core: Refetch remote Cozy Notes after upgrade

core/merge.js, core/prep.js, test/integration/notes.js, test/support/builders/remote/note.js, test/support/helpers/remote.js
Some PouchDB records may have a `metadata` attribute, generated by the
stack with domain specific information.
For example, this is used to store the actual content of a Cozy Note,
its title, its schema…
We use this information in the Desktop client to check if a document
with a Cozy Note mime type is an actual Cozy Note (i.e. it's not a
markdown file generated during a conflict).
When we update an existing PouchDB record (during a move, an update or
a metadata — any record attribute — update), we copy some attributes
over to the new record before the two are compared and the new one is
saved to PouchDB.
We were not copying the `metadata` attribute.
If the updated document was a Cozy Note, its record in PouchDB would
have lost crucial information and our checks would tell us it is not
an …
=> core/merge: Keep existing metadata attribute

core/local/atom/fire_local_start_event.js, core/local/atom/win_identical_renaming.js, test/unit/local/atom/win_identical_renaming.js
On Windows, when propagating compound remote move and update changes
to the local filesystem, we can see old file metadata being propagated
back to the Cozy.
This is an association of timing and state issues.
When we apply a file move on the local filesystem, we expect 2 events
to be fired:
- a `renamed` event (obviously fired because the file has a new path)
- a `modified` event fired for the permissions and/or dates changes
The Atom watcher manages to group those 2 events via its
`awaitWriteFinish` step because they're processed with little delay
between them (less than the step's 200ms timeout which triggers the
flush of waiting events).
However, on Windows, we can see a second `modified` event fired not so
long after the first one (something like 10-15ms later) but reaching
the …
=> core/local/atom: Group close Renamed and Modified

core/local/stater.js, core/merge.js, core/metadata.js, core/pouch/migrations.js, test/integration/conflict_resolution.js, test/integration/executable.js, test/integration/interrupted_sync.js, test/integration/move.js, test/integration/mtime-update.js, test/integration/notes.js, test/integration/update.js, test/support/builders/metadata/base.js, test/support/builders/metadata/file.js, test/support/helpers/context_dir.js, test/support/helpers/scenarios.js, test/unit/merge.js, test/unit/remote/watcher.js
We want to keep track of the current local state of files, whether
they're in sync or not.
At the moment, we store altogether in our PouchDB records the 3
different states of documents — local, remote and last synced — and a
few technical attributes that help us make sense of it all (e.g. which
side has received changes that need to be synchronized, what actions
need to be applied…).
This mechanism is limited because we don't store separately the values
of attributes on each side. For example, if a file's `size` has
changed on the remote Cozy and we've saved it in PouchDB, we've lost
the local file's `size`.
When loosing this information, it's harder for us to make sense of our
data and to make the right decision and even impossible to make some.
A good example of such an impossible …
=> core/merge: Save local file metadata separately

CHANGELOG.md, package.json
- Moving a document to an ignored location (see https://github.com/cozy-labs/cozy-desktop/blob/master/core/config/.cozyignore
and your local `.cozyignore` rules file) after another move would
result in the first move being propagated to the remote Cozy and the
document being desynchronized after that.
From now on, the second move to the ignored location will cancel the
first move and the client will correctly propagate a deletion to the
remote Cozy.
- Deleting a file on your Cozy while moving it on your local
filesystem with your client stopped would lead to the
desynchronisation of the file. It would be deleted on your Cozy but
would still exist on your local filesystem and all later
modifications would not be propagated. We're now refusing the
deletion …
=> Release v3.21.0

core/local/chokidar/analysis.js, core/local/chokidar/local_change.js, test/unit/local/chokidar/analysis.js
We want to normalize paths with NFC when comparing them in `analysis`
so that equivalent paths which differ only by the norm they're encoded
with are found equal and we don't detect moves when there aren't.
On macOS, the local filesystem can automatically normalize UTF-8
characters in files and folders paths with the NFD norm.
Folders and files created on the remote Cozy will be normalized with
the NFC norm.
The same names encoded in different norms won't be equal from a
JavaScript string comparison standpoint.
On macOS, when a folder is moved or renamed, we receive two events from
the filesystem for the folder itself (i.e. `unlinkDir` with the old
path and `addDir` with the new path) that we will transform into a
`DirMove` change. We also receive two events for each child of the
moved …
=> local/chokidar/analysis: Compare normalized paths

core/local/chokidar/normalize_paths.js, core/local/chokidar/prepare_events.js, core/local/chokidar/watcher.js, test/unit/local/chokidar/normalize_paths.js
We'll correct paths normalization on local changes instead of local
events (i.e. after the analysis step) as well as improve the
correction by correcting paths of new documents when they're added
into an existing folder.
On macOS, saved paths in PouchDB records and actual paths on the
filesystem can differ by their UTF-8 normalization. Indeed, documents
created on the remote Cozy will always be normalized with NFC while
documents created locally **can** be normalized with NFD. This is the
case on HFS+ volumes for example.
The local normalization is done automatically and generates changes
that we don't want to propagate to the remote Cozy. This is why the
normalization can be different between PouchDB and the filesystem.
We'll consider that the local filesystem is applying an NFD …
=> local/chokidar/watcher: Normalize changes paths

core/local/chokidar/normalize_paths.js, core/metadata.js, core/remote/change.js, core/remote/watcher/index.js, core/remote/watcher/normalizePaths.js, core/remote/watcher/squashMoves.js, test/unit/regressions/850.js, test/unit/remote/watcher.js
To avoid detecting invalid movements when a file or folder whose path is encoded with different normalizations between the local PouchDB record and the remote Cozy is edited on the Cozy we do 2 things:
- compare changes' paths using the same normalization (NFC by default) every where within the remote watcher
- keep the existing (as in saved in PouchDB) path normalization for existing documents and parent folders
The later change is more of a safety net.
=> core/remote/watcher: Keep pouch path normalization

core/merge.js, test/unit/merge.js
We have recently introduced a local state for files via a `local`
attribute in their PouchDB records.
When the file is created on the local filesystem,  the local state
will be filled when the record is created.
On the other hand, when the file is created on the remote Cozy, the
state won't exist until the local watcher detects the file's creation
on the local filesystem and the generated `created` event is merged.
On Windows, this `created` event can be ignored if we're replacing an
existing document. We'd have a prior `deleted` event at the same
path and the two events would be grouped together by the
`winDetectMove` step into an `ignored` event. We don't have a
`renamed` event because the source and destination paths would be the
same and the result move would be invalid.
In this case, …
=> core/merge: Compare only existing local states

core/pouch/migrations.js
To give the `Sync` module the necessary hints that a given document
should be moved, we add a `moveFrom` attribute on the PouchDB record
describing its destination metadata.
Once the movement is synchronized, we delete this attribute for 2
reasons:
- to limit the records size and specifically their depth
- to make sure the `Sync` module won't read this hint again and try to
perform the synchronize the movement once more
However, this final cleanup wasn't always performed. This means that
some users still have PouchDB records with a `moveFrom` attribute.
If those documents are not modified, this is not an issue. On the
other hand, a data migration could lead the `Sync` module to see a
change in the record and, seeing the attribute, try to perform the
move which will probably fail.
We've …
=> pouch/migrations: Remove synchronized `moveFrom`s

test/integration/case_or_encoding_change.js
This test fails now when it should have failed before, when we changed
the behavior of the remote watcher when a doc with a local NFD path is
modified on the remote Cozy where its path is normalized with NFC.
We used to accept normalization changes from the remote Cozy but we've
decided to keep the normalization first saved in Pouch.
In this test, the normalization first saved is NFD so we should not
see a path change.
=> test: fix macOS normalization test

core/local/atom/initial_diff.js, core/local/chokidar/prepare_events.js, core/metadata.js, test/integration/full_loop.js, test/unit/local/atom/dispatch.js, test/unit/local/atom/initial_diff.js, test/unit/local/chokidar/prepare_events.js
In order to limit the number of checksum computations during the
initial scan, we try to reuse the existing PouchDB record's local
`md5sum` if the event's update time matches the record's local
`updated_at`.
We compare the event's `mtime` field because we care only about the
file content updates to trigger checksum computations.
Also, we now compare it with the recently added local `updated_at`
which will now contain the latest local `mtime` value instead of
either the remote `updated_at` value or the max between the local
`mtime` and `ctime` that can be stored in the record's main
`updated_at` attribute.
Finally, we re-use the local `md5sum` because the main `md5sum`
attribute can have changed after a remote update was merged but not
applied on the local filesystem.
Since we're changing …
=> core/local: Re-use untouched files' checksum

core/merge.js, core/metadata.js, test/unit/merge.js, test/unit/metadata.js
When moving a folder whose path is normalized with a certain norm
(i.e. NFC or NFD) but its children's paths are normalized with another
one (at least the parent part), we want to make sure the new
children's paths are correctly computed (i.e. the parent part is
replaced with its new path) and that their id is in sync with their
new path.
When a folder is moved, we fetch all its descendants from PouchDB via
their ids, based on the folder's id (i.e. we look for every document
whose id starts with the folder id). In this case, the path
normalization doesn't matter because ids are re-normalized.
Once we have all the descendants records, we replace the folder part
in its descendants' paths with its new path. However, if the
normalization is different, the replacement won't work (the String …
=> core/merge: Move children with different normalization

core/local/chokidar/analysis.js, core/remote/change.js, core/remote/watcher/squashMoves.js, test/unit/local/chokidar/analysis.js
When events are buffered (either on macOS or the remote Cozy), and a child document is moved as well as its parent folder, we need to correct the old child path to make sure its movement can be merged and applied (its old path references its old parent path which is invalid after the parent has been moved).
If we have a normalization difference between the parent path and the parent path within the child path, then the correction won't work with a simple string replacement.
We propose a new method to correct the child's old path that is not affected by normalization differences in the parent paths.
We use it both for local, macOS, moves and remote moves although we couldn't build a meaningful test to show that we had issues with remote moves in moves.
The remote move in move application …
=> Correct move inside move old path with normalization differences

core/local/index.js, test/integration/move.js
We should not trash a file when propagating a combined case change and
content update on macOS and Windows.
When we merge an overwriting move, we use the `overwrite` PouchDB
attribute to keep track of the overwritten document (especially its
`path` and/or `_id`). The presence of this attribute is a hint for the
Sync module and will be used to trash the overwritten document before
moving the overwriting one to its new location.
However, we also use this attribute when we simply update a file. We
did this so that we could remove the attribute to give a hint to the
Sync module that the updated file should be backed up before in
certain situations.
So, to avoid trashing the file when we try to apply a move and a file
update, we compare the most recent version of the record and the
content of …
=> local/writer: Case change + udpate does not trash file

CHANGELOG.md, package.json
- As a multi-device platform, Cozy Cloud tries to keep the
modification dates of documents in sync across all your devices
(i.e. Drive Web, Drive Mobile, Cozy Desktop, other people's
Cozies…). When modifications happen on the Cozy itself, the
modification date is set by the server. On the other hand, when the
modification is made on on your computer, we get the date from your
filesystem. We were using the most recent date between the content
modification date and the metadata modification date but we think
the content modification date is the most important and that it
should not be affected by movements, renamings, permission changes,
etc.
For this reason, from now on we will only use the content
modification date on Cozy Desktop.
- When you start your Cozy …
=> Release v3.22.0-beta.1

electron-builder.yml
The default comodoca.com time stamping server used by
`electron-builder` to sign our Windows binaries is failing us.
This prevents us from building new Windows releases.
We've switched to another server, provided by Digicert.
If we start seeing failures again, we can find other servers at
gist.github.com/Manouchehri/fd754e402d98430243455713efada710.
The current list contains:
- http://timestamp.globalsign.com/scripts/timstamp.dll
- timestamp.geotrust.com/tsa
- http://timestamp.comodoca.com/rfc3161
- http://timestamp.wosign.com
- http://tsa.startssl.com/rfc3161
- http://time.certum.pl
- http://timestamp.digicert.com
- freetsa.org
- http://dse200.ncipher.com/TSS/HttpTspServer
- http://tsa.safecreative.org
- http://zeitstempel.dfn.de
- ca.signfiles.com/tsa/get.aspx
- …
=> build: Change time stamping server

core/utils/timestamp.js, test/unit/utils/timestamp.js
We should correctly round dates sent by the remote Cozy whether they're
in UTC format or not.
We recently started to round the `created_at` and `updated_at` dates
coming from the remote Cozy to make sure we have the expected ISO
format in our PouchDB records.
However, we were expecting to receive dates in UTC only while we can
receive dates in other timezones.
When the timezone is not UTC, our rounding function raises an error
after trying to read the `length` of `undefined`.
This error is raised because our method to get the milliseconds part
of the date as a string relied on the presence of the letter `Z` at
the end of the date string.
When the timezone is not UTC, the string ends with the time offset and
the milliseconds part could be `undefined` if milliseconds were not
present in the …
=> core/utils/timestamp: Round non-UTC remote dates

CHANGELOG.md, package.json
- Files with remote creation or modification dates in a timezone other than UTC
would raise an error in the remote watcher when converting them into PouchDB
records.
We're now rounding those dates with a timezone agnostic method and those
errors should not happen anymore.
=> Release v3.22.0-beta.2

gui/main.js
Similarly to the Recent files list display, the account information
displayed in the Settings tab are sent to the main window via
messages.
In the same fashion, those messages need to be sent after the window
has fully loaded otherwise they won't be received and the account
information will never be displayed.
=> gui: Fix account info display in Settings tab

CHANGELOG.md, package.json
- The list of recently synchronized files and the linked Cozy
information would sometimes not be displayed after a client restart,
especially on Windows.
The data was correctly persisted though and we've made sure it is
correctly loaded and displayed now.
=> Release v3.22.0-beta.3

gui/js/lastfiles.js
Node's documentation states that it is unsafe to make multiple calls
to `fs.writeFile()` on the same file in parallel
(see https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback).
However, this is precisely what we were doing when persisting our
last files JSON object to disk. We only make one call to
`fs.writeFile()` per `lastFiles.persist()` call but calls to
`persist` are made asynchronously and not awaited by the caller (for
GUI performance).
This is probably the reason why we're seing malformed JSON files
persisted to disk.
We'll now use an `async` queue in which we'll push calls to
`fs.writeFile()` so they'll be run sequentially. We still won't
await calls to `lastFiles.persist()` in the GUI.
=> gui/lastFiles: Securely persist last files list to disk

core/sync.js
We use events to communicate between the Sync module and our GUI and
update the list of recently synchronized files.
We should not be adding folders in this list at the moment.
However, it appears we were sending Move events for all child moves,
be it files or folders.
For other types of events, we're checking whether the synchronized
element is a file before sending a message to the GUI.
We're now doing the same for child moves.
=> core/sync: No move events for folders

CHANGELOG.md, package.json
- The list of recently synchronized files could contain folder items
when their parent was moved or renamed.
We're now making sure only file items will be displayed in this list
until we officially support folder items.
- We increased the number of file types that will be displayed with a
specific icon to help you check more easily which elements were
synchronized. This includes 2 new icons for links (i.e. `.url`
files) and contacts (i.e. `.vcf` files).
=> Release v3.22.0-beta.5

gui/main.js
The auto launch status is computed asynchronously and sent to the Tray
window via an event.
However, if the window is not fully loaded and the Elm application not
ready to receive this message when it is sent then we'll miss it and
will display the default value which is `enabled`.
We're now sending the current status only after the window is shown so
we're sure it's ready to be received and processed.
=> gui: Show correct auto launch status

CHANGELOG.md, package.json
- The autolaunch setting could be displayed as enabled when it was
disabled from the OS settings panel instead of the Cozy Desktop
client settings.
We've made sure the interface shows the actual value of this setting
and the switch is off when the autolaunch is disabled.
=> Release v3.22.0-beta.6

gui/js/components/UserActionRequiredDialog.js, gui/js/onboarding.window.js, gui/js/tray.window.js, gui/js/updater.window.js, gui/main.js, gui/styles/_two_panes.styl, package.json, yarn.lock
Upgrades Electron to v6.1.12 and applies the required changes to other dependencies and code to have the application work with the new Electron, Node and V8 versions.
=> deps: Bump Electron to v6.1.12

gui/js/autolaunch.js
We introduced a fix a while back to make sure the autolaunch
`.desktop` file created on Linux would use the app's name and not its
path since the path would contain the version by default and
autolaunch would thus break after each upgrade.
We tried to re-enable autolaunch with the app's name for users who had
it enabled with the app's path. We would check the return value of
`autoLauncher.isEnabled()` to decided whether we needed to do it but
this value is not a boolean as expected, it is a promise of a boolean.
This means that we would always try to re-enable autolaunch, at each
run, for users who wanted to disable it.
We're now waiting for the promise resolution and use the resolved
value to decide if we need to re-enable autolaunch.
=> gui: Don't automatically re-enable autolaunch

gui/elm/Window/Help.elm, gui/elm/Window/Onboarding/Address.elm, gui/elm/Window/Onboarding/Folder.elm, gui/elm/Window/Onboarding/Welcome.elm, gui/elm/Window/Tray.elm, gui/elm/Window/Tray/Settings.elm, gui/elm/Window/Tray/UserActionRequiredPage.elm, gui/styles/_icon.styl, gui/styles/_markdown_viewer.styl, gui/styles/_spin.styl, gui/styles/_toggle.styl, gui/styles/_two_panes.styl, gui/styles/_updater.styl, gui/styles/_wizard.styl, gui/styles/app.styl, package.json, yarn.lock
Upgrades `cozy-ui` to v35.38.0 and makes the required changes to the
views and styles to have the same interface as the one prior to the
update (variables have changed, the import style as well and some
components like spinners have a slightly different implementation).
=> deps: Bump cozy-ui to v35.38.0

core/pouch/index.js, core/pouch/migrations.js, test/support/helpers/pouch.js, test/unit/pouch.js, test/unit/pouch/migrations.js
When migrating an existing database, we copy all existing documents,
migrate those that need to be, replace their old version in the
database copy and then replace the old database with the copy.
In this process, we lose an essential information: the list of changes
from the old database's changesfeed that were not already processed by
the Sync module.
These changes can be found by requesting the changesfeed starting with
the saved local sequence. However, since the sequence increases with
each change made on a document and the new database has not seen the
same number of changes, the old database's local sequence has no
meaning in the new database context.
This is why we were just setting the new database's local sequence to
the last update sequence of the new database.
From there, only …
=> pouch/migrations: Migrate changesfeed

core/local/atom/initial_diff.js, core/local/chokidar/initial_scan.js, core/pouch/index.js, test/unit/local/atom/initial_diff.js, test/unit/local/chokidar/initial_scan.js, test/unit/pouch/index.js
When starting the Desktop client, we need to guess what changes were
made to local files while it was stopped. To do so, we run a full scan
of the local synced folder, fetch all records from our PouchDB
database and compare them to find modifications, movements and
deletions.
In this context, deletions are inferred from the absence on the local
filesystem of a document for which we have a record in PouchDB.
In this case, we emit a `deleted` event for that document and leave
the rest to the other local watcher steps.
However, if the record was merged by the remote watcher and not
synchronized before the client was stopped, it is expected that the
document would not exist on the local filesystem yet (i.e. it has not
been downloaded at all).
To avoid emitting `deleted` events for such …
=> core/local: Initial scan keeps unsynced remote docs

.flowconfig, dev/remote/automated_registration.js, dev/remote/generate-test-env.js, gui/js/onboarding.window.js, gui/js/proxy.js, gui/main.js, package.json, test/integration/add.js, test/support/helpers/context_dir.js, test/support/helpers/cozy.js, test/unit/gui/proxy.js, yarn.lock
Upgrades Electron to v7.3.2 and applies the required changes to other dependencies and code to have the application work with the new Electron, Node and V8 versions.
=> deps: Bump Electron to v7.3.2

test/integration/trash.js
The Desktop client is supposed to cancel remote deletions of files
that were moved on the local filesystem at the same time.
However, the implementation of this behavior resulted in incoherent
metadata on the Cozy and the stack is now denying client requests to
move files that are in the Cozy trash.
See https://github.com/cozy/cozy-stack/commit/afa80ba65de265d5133974562014b89aae7b2836
We'll need to fix our implementation (probably by restoring the file
before moving it) but this is not the priority so we're only disabling
this test for the moment.
=> test: Disable known failing trash integration test

core/local/index.js, core/reader.js, core/remote/cozy.js, core/remote/index.js, test/integration/notes.js, test/integration/platform_incompatibilities.js, test/support/helpers/remote.js, test/unit/remote/index.js
We're witnessing a lot of timeout errors (i.e. 504 response status)
when users send file modification requests while we don't really see
them for file creation requests.
We're not completely sure about the actual cause of those timeouts but
the `Content-Length` header is not sent in modification requests and
we believe this can have a role in this situation.
We're now sending the header and we'll monitor errors to see if we see
something different, either a drop in error rate or different errors
(we are expecting to receive 412 response statuses meaning the content
we're sending does not reflect the headers value and thus that the
content has changed on the local filesystem between the time the
record was merged and the time we stated propagating the change to the
remote Cozy).
Please …
=> core/remote: Send body size with file modification

package.json, yarn.lock
`cozy-client` requires `@babel/runtime` modules from its distribution
file for NodeJS but does not declare it in its `package.json` file so
its not imported in our final build.
Once packaged by `electron-builder` the client can't find the modules
and fails to start.
Importing `@babel/runtime` as a direct dependency seems to fix the
problem.
=> deps: Add @babel/runtime

gui/styles/_two_panes.styl
The file type icons CSS rules are generated from a simple loop over
all the types we're supporting.
One of those types is `text`.
However, if those are not quoted, stylus will use the value of any
existing variable with that given name in interpolations instead of
the string itself.
Since we import the `button` component module from `cozy-ui` and a
`text` variable is defined in this module, the generated rule for this
file type was a mess and the associated icon would not be displayed in
the Recent list in the main window.
By quoting the types in the loop argument, we make sure those will be
interpreted as strings and not variables.
=> gui/styles: Quote file types in stylus loop

gui/styles/_updater.styl
With the upgrade of `cozy-ui` spinners elements need to be styled
differently.
The Updater window spinner was not updated and was still using a
background image instead of a mask.
This is fixed by extending the new `$spin` mixin and using a
background color instead of a fill color.
=> gui/updater: Fix infinite spinner style

core/local/chokidar/normalize_paths.js, core/remote/change.js, core/remote/watcher/index.js, core/remote/watcher/normalizePaths.js, test/unit/remote/change.js, test/unit/remote/watcher.js
On macOS, we normalize the paths of remote changes to make sure we
keep the normalization of existing PouchDB records and avoid issues
like conflicts.
However, this process requires that ancestor paths be normalized
before their descendants' paths and remote changes are not necessarily
in this order (e.g. in case a folder is added with content and then
renamed, the folder addition change will come after its content
addition).
To prevent normalization issues, we now sort changes by destination
path before normalizing those paths.
It should not affect the final order of changes but this is a risk as
we know the remote changes sort method is not fully accurate.
Tests are passing so we hope we won't see new changes order issues in
the future.
=> core/remote/watcher: Normalize path sorted changes

CHANGELOG.md, package.json
- The order in which changes fetched from the remote Cozy were
processed could hinder the paths normalization and lead to issues
like conflicts.
We're now sorting changes before the normalization to make sure the
process will complete as expected.
=> Release v3.23.0-beta.5

CHANGELOG.md, package.json
- Failing file uploads could block the client in an ever ending
synchronization state because of the way Electron/Chromium treats
those errors.
We've added some workarounds to catch and process those errors to
make sure the file upload attempt finishes (it will still be failed)
and releases control back to the synchronization process.
=> Release v3.23.0-beta.6

CHANGELOG.md, package.json
- We upgraded the framework upon which our application is built,
Electron, to v9.2.1 which is the 2nd latest major version. This
should bring more stability to the application overall and prevent
some crashes. We can also expect smaller bundles. This upgrade
brings us official support back for a while.
- Data migrations run after some client upgrades should not prevent
not fully synchronized changes from being detected and synchronized
after the migration.
- Documents added on your remote Cozy, detected by the client but not
fully synchronized before it is stopped should be synchronized
correctly after the next client launch. The client should not try to
delete them on your Cozy because it does not find them locally (the
deletions never went through …
=> Release v3.23.0

core/local/index.js, core/metadata.js, core/remote/index.js, core/sync.js, core/writer.js, test/support/doubles/side.js, test/unit/metadata.js, test/unit/remote/index.js, test/unit/remote/watcher.js
The `remote` attribute of `Metadata` objects, stored locally in
PouchDB, only includes the `_id` and `_rev` of the associated remote
document.
We've started storing most of the other remote attributes in the main
section of the `Metadata` object but we're missing an opportunity to
make comparisons between the most recent remote state of a document
and the latest known remote state from any part of the synchronization
process.
We're forced to make those comparisons in the remote watcher while we
could benefit from them in the Merge or Sync modules.
Besides, storing the entire remote document means we have access to
all remote attributes and won't need to make further changes in the
future to access new attributes.
This commit only adds the entire remote document to `Metadata` objects …
=> core/metadata: Store remote doc in `Metadata`

core/merge.js, core/metadata.js, core/pouch/migrations.js, test/integration/mtime-update.js, test/integration/notes.js, test/support/builders/metadata/base.js, test/unit/merge.js
We build the `local` attribute of `Metadata` for folders like we
already do for files.
This will allow us to make comparisons between a known local state and
a new one and between a local state and a known synchronized or remote
state.
PouchDB records are migrated with known attributes which are present
in the main section of the `Metadata` object.
=> core/local: Build local metadata for folders

core/metadata.js, core/remote/constants.js, core/remote/cozy.js, core/remote/document.js, core/remote/index.js, core/remote/watcher/index.js, dev/capture/remote.js, test/integration/platform_incompatibilities.js, test/support/builders/index.js, test/support/builders/metadata/base.js, test/support/builders/metadata/file.js, test/support/builders/remote/base.js, test/support/builders/remote/dir.js, test/support/builders/remote/file.js, test/support/builders/remote/note.js, test/support/builders/stats.js, test/support/helpers/remote.js, test/unit/merge.js, test/unit/metadata.js, test/unit/remote/index.js, test/unit/remote/watcher.js
For Flow to help us avoid mistakes it is crucial that the types we
use are well defined to represent the reality and not lie to us.
The `RemoteDoc` type was defined with a `path` attribute for both
file and directory remote documents while the remote Cozy actually
does not populate the path for file documents.
This refactoring updates the `MetadataRemoteInfo` type and creates the
2 subtypes `MetadataRemoteFile` and `MetadataRemoteDir` to accurately
represent the remote documents as we store them in PouchDB while
`RemoteDoc` and its 2 subtypes `RemoteFile` and `RemoteDir` represent
the remote documents as we receive them.
With those new types we caught incoherences in the data being used in
some tests (especially the `metadata` module unit tests which were not
covered by Flow).
=> core: Refactor remote types

core/utils/timestamp.js, test/integration/notes.js
When updating a remote document in tests, we should always set the
`updated_at` attribute to the update time or the local `Metadata`
object will keep the latest update time and we'll see synchronization
issues arise once the local watcher kicks in (i.e. the update time,
which is used to set the local file metadata on the filesystem, hasn't
changed so we won't recompute the checksum of the local file although
its content has changed).
For now the `RemoteBaseBuilder.update()` method is only used once in
the Notes integration tests.
We also fix the `timestamp.spread()` method which was returning a
0-based month number when builders and `timestamp` methods are
expecting a 1-based month when building dates.
=> test/integration/notes: Update time with note

core/metadata.js, core/move.js, test/support/builders/metadata/base.js, test/support/builders/remote/base.js, test/unit/local/atom/dispatch.js, test/unit/merge.js, test/unit/metadata.js
Now that we're maintaining `local` and `remote` metadata separately we
should check that we have the expected value when calling different
Merge methods.
This meant improving the way we build and maintain those attributes in
the data builders as well.
=> test/merge: Check local & remote attributes' value

core/merge.js, core/metadata.js, core/pouch/migrations.js, test/unit/merge.js
We want to track the local and remote path of documents separately
since they will differ between the time a move on one side is merged
and the time it is propagated to the other side.
We already stored the remote path in the `remote` attribute of
`Metadata` records but we now store the local path in the `local`
attribute.
They both need to be updated for children of moved directories since
we won't necessarily receive the move events/changes for those
documents at the same moment, leaving us with incoherent paths.
For other changes, we should have up-to-date side attributes computed
from the event/change.
=> core/merge: Maintain path in local and remote attributes

core/remote/index.js, test/unit/remote/index.js
When we try to propagate the creation of a local folder to the remote
Cozy and a folder with the same name in the same parent already
exists, we link the local and remote version together instead.
However, the local version can be slightly different (have another
last update date for example) so we'll now send an update request with
the local version after the remote document has been linked to the
local one.
=> core/remote: Update folder after linking it

core/merge.js, core/metadata.js, core/pouch/migrations.js, test/integration/executable.js, test/support/builders/metadata/file.js, test/unit/metadata.js
The `executable` attribute of `Metadata` objects is marked as optional
in the type definition. This leads to uncertainty as to whether the
attribute is defined in `Metadata` objects or not and forces us to
check for its presence every time we want to read or set it. Besides,
it allows us to build file `Metadata` objects without it.
Marking the attribute as required and setting it for every file
`Metadata` object will help us ensure our documents are valid and
simplify the use of this attribute.
/!\ Although it is marked as required, it will still be missing in
folder `Metadata` objects. This is made possible by cracks in our
types coverage but should be fixed once we'll have different type
definitions for file and folder metadata.
=> core/metadata: Require `executable` file attribute

core/sync.js, test/unit/sync.js
Instead of computing the current document "revision" when computing
the out-of-date side and passing it down to `applyDoc()` as an
argument as well as the side name, we can compute it within
`applyDoc()` where it's used.
This will simplify `applyDoc()` unit tests as we won't have to
determine what's the appropriate `rev` (i.e. the previous term) to
pass to `applyDoc()` to have the expected behavior.
=> core/sync: Compute current revision in applyDoc

core/merge.js, core/metadata.js, test/unit/merge.js
We can receive requests to Merge a file creation while the file
`Metadata` already exists in PouchDB (during an initial local scan for
example).
In this situation we transform the creation into an update.
To avoid code duplication and complexity in the `Merge.addFile()`
method, we now delegate the file update to the `Merge.updateFile()`
method.
**Please** make sure the following boxes are checked:
=> core/merge: addFile delegates existing file update

core/merge.js, core/metadata.js, core/move.js, core/pouch/migrations.js, test/support/builders/metadata/base.js, test/unit/metadata.js, test/unit/move.js
The `Metadata` `tags` attribute could either be missing or a list of
string values. It is now marked as required.
The `metadata.buildFile()` and `metadata.buildFolder()` methods will
now always default it to an empty Array since tags come from remote
documents and those are used to build `Metadata` objects from local
data.
The `merge` and `move` methods won't need to default the attribute to
an empty Array anymore and moved documents will inherit the list of
tags from the source document.
=> core/metadata: Mark `tags` attribute as required

core/local/index.js, core/reader.js, core/remote/index.js, core/writer.js
The `Reader` and `Writer` interfaces (which are implemented by the
`Local` and `Remote` sides) are meant to apply changes saved in
PouchDB to the appropriate side.
This means that they should always be manipulating saved PouchDB
records and thus accept `SavedMetadata` arguments rather than simple
`Metadata`.
=> core: Use `SavedMetadata` in reader and writer

test/support/builders/metadata/base.js, test/support/builders/metadata/file.js, test/unit/remote/index.js
The `$Shape<>` special type allows us to check the type of each
attribute of the typed object without providing all the attributes.
By typing the `BaseMetadataBuilder`'s `doc` with `$Shape<Metadata>` we
can partially build it in the constructor and finish in the `build()`
or `create()` method while still making sure that each attribute set
on the object is correctly typed.
Typing it with `Object` was not offering us this security and allowed
us to modify `doc` in ways that were not correct.
=> test/builders/metadata: Type doc with $Shape<>

core/merge.js, core/metadata.js, core/sync.js, test/integration/conflict_resolution.js, test/unit/merge.js
To avoid losing merged but unsynced remote file updates while avoiding
unnecessary conflicts, we introduced an exception in the
`Merge.updateFileAsync()` behavior when merging an "update" from an
initial scan event.
In this case, we would always consider that the file had not been
updated on the local file system to preserve the remote update.
It means that if the file had actually been updated, we would lose the
local update.
To mitigate this problem, we would not mark the update as an
overwriting one, thus telling Sync to trash a copy of the file before
applying the remote update on the local filesystem.
Now that we track the local metadata separately from the remote and
"merged" metadata, we can tell if the file was updated locally or not.
If it wasn't we won't modify the existing …
=> core/merge: Fix conflicting file updates

core/merge.js, core/metadata.js, test/unit/merge.js
When we merge a file update in PouchDB, we fetch the existing record
from PouchDB and copy some of its attributes to the new record for the
updated file.
However, we were not copying all relevant attributes and thus losing
some of them (e.g. the `tags` attribute would be overwritten).
To avoid losing data and make this copy more scalable, we're now
building the new record based on the existing one and overwriting
only the relevant attributes.
This process should probably be done in every `Merge` method updating
an existing PouchDB record.
=> core/merge: Merge attributes in updateFile

CHANGELOG.md, package.json
- This release lays the ground work for a future synchronization
algorithm. We now store the complete remote metadata of each
document and the local metadata of both files and directories. This
will allow us to make deeper comparisons and take better action in
complex situations (e.g. a file modification and renaming on the
local filesystem with a parent directory renaming on the Cozy).
Another part of this base work is the move to generated PouchDB
records ids. Those were previously based on the document's path and
this scheme had several limitations (e.g. when a document was moved
or renamed, its record id had to change).
- The move to generated PouchDB ids allows you to synchronize
documents whose name start with an underscore (`_`), in the root …
=> Release v3.24.0-beta.1

core/local/chokidar/analysis.js, core/local/chokidar/local_change.js, test/unit/local/chokidar/analysis.js
Since we buffer events on macOS, if a file or a directory is moved
more than once during the buffering time and `fsevents` fires
`unlink` and `add` events for all moves, then we'll end up with
`wip` moves (i.e. because the document is not at the final location
already)that should be completed by future `unlink` and `add`
events.
However, we were only expecting the situation where `fsevents` will
group those events together and fire only the final `unlink` and
`add` events. Besides not handling `wip` moves, we were throwing an
error when encountering them.
Since we have a better grasp on the situation, we simply stop
throwing errors if we find ourselves in a situation where we should
group a `wip` move event with an `unlink` event. We will still throw
an error if the move was complete …
=> core/local/chokidar/analysis: Handle wip moves

.github/actions/build-and-publish/action.yaml, .github/actions/setup-couchdb/action.yaml, .github/actions/setup-cozy-stack/action.yaml, .github/workflows/linux.yaml, .github/workflows/macos.yaml, build/afterSignHook.js, test/integration/case_or_encoding_change.js, test/integration/id_conflict.js, test/support/helpers/config.js, test/support/helpers/pouch.js, test/unit/app.js, test/unit/local/chokidar/watcher.js
Allow testing and building the application on Github Actions instead of Travis CI.
=> ci: Use Github Actions instead of Travis

CHANGELOG.md, package.json
- We're now handling moving the same document multiple times in a
short delay and moving a document just downloaded from the Cozy to a
path including UTF-8 characters on HFS+ filesystems.
=> Release v3.24.0-beta.3

CHANGELOG.md, package.json
- This release lays the ground work for a future synchronization
algorithm. We now store the complete remote metadata of each
document and the local metadata of both files and directories. This
will allow us to make deeper comparisons and take better action in
complex situations (e.g. a file modification and renaming on the
local filesystem with a parent directory renaming on the Cozy).
Another part of this base work is the move to generated PouchDB
records ids. Those were previously based on the document's path and
this scheme had several limitations (e.g. when a document was moved
or renamed, its record id had to change).
- The move to generated PouchDB ids allows you to synchronize
documents whose name start with an underscore (`_`), in the root …
=> Release v3.24.0

core/app.js, core/pouch/index.js, test/support/helpers/pouch.js, test/unit/app.js, test/unit/pouch/index.js
When we migrated the `Pouch` class to native Promises, we missed an
asynchronous call in the `tree()` method that needed to be awaited,
preventing the help messages from being sent to support.
Besides, now that the PouchDB records' ids are not based on the
documents' paths anymore, returning them does not give us an idea of
the documents tree.
We've moved to a more precise `localTree()` method that returns the
local path of documents as saved in the `local.path` attribute of the
records since this tree is mostly used to be compared with the remote
tree.
=> core/pouch: Fix local tree getter

CHANGELOG.md, package.json
- Some synchronization errors will now be notified to you within the
main window with information about the error itself and how to fix
it and two options: giving up on the change if it can't be
synchronized or requesting an early retry (automatic retries will be
performed in the background).
Know that the synchronization will be blocked by the failing change
until an outcome is decided. This should avoid a lot of
automatically dropped changes as we would otherwise stop retrying
after the third attempt.
=> Release v3.25.0-beta.1

core/syncstate.js, gui/elm/Data/Status.elm, gui/js/tray.js, gui/main.js
The syncing status comes from the Sync state and is propagated to the
main GUI window and the systray icon. It can come with data (i.e.
metadata about the file being transferred) from which we want to
derive a label for the systray.
We had 2 issues with this process:
1. the filename was not passed correctly to the `tray` module in
charge of setting the systray label
2. the method in charge of setting the systray label would not
correctly concatenate the main part of the label with the given
filename
We also take the opportunity to harmonize the status name across the
board by using `syncing` instead of `sync` in the Sync state.
=> gui: Fix syncing status display

.github/workflows/linux.yaml, .github/workflows/macos.yaml, test/scenarios/move_overwriting_dir/trashed_first/scenario.js, test/scenarios/run.js, test/support/helpers/scenarios.js
The value `false` assigned to the `STOPPED_CLIENT` env variable in our
github workflows is read as a string and thus interpreted as a thuthy
value instead of the boolean `false` in the scenarios configuration.
This means our scenarios were always run with a stopped client in our
github workflows!
In an attempt to prevent such issues in the future, we're now using
helpers to read the value of env variables and interpret them. This
way, all boolean variables will be interpreted the same way which
makes it easier to reason about.
=> test/scenarios: Replace env variables with helpers

core/local/chokidar/watcher.js, dev/capture/local.js, package.json, yarn.lock
Upgrading these 2 dependencies improves the reliability of the local
watcher on macOS and prevents segmentation faults during integration
tests specifically.
=> deps: Upgrade Chokidar and PouchDB

core/merge.js, test/integration/trash.js, test/unit/merge.js
When we try to merge a doc trashing and that doc was already trashed
or deleted on the other side, we don't do anything as it looks like we
are already in sync.
However, this is ain't quite true. The sides metadata have changed and
since we use a deletion marker now, Sync will try to apply the first
deletion.
If the first deletion was done on the local PC, we'll try to trash a
doc that has since changed on the Cozy and we'll get a 412 error.
Now that we're blocking the Sync on this error, this is quite visible
and annoying (we can still get out of this situation by giving up on
the change).
By simply accepting the merge the second trashing request, we make the
remote revision will be updated when the remote watcher runs and the
synchronization will resume after a retry (either automatic …
=> core/merge: Accept trashing of already trashed doc

.github/actions/setup-cozy-stack/action.yaml
It seems more recent versions of `brew` don't allow installing casks
via the `brew cask install` command anymore but would have us call
`brew install --cask` instead.
It also seems that such version is now used on the `macos-latest`
Github Workflow OS, making our `setup-cozy-stack` action fail.
=> ci: Fix brew cask install usage

core/local/constants.js, core/local/index.js, core/sync/index.js, test/unit/local/index.js
It appears that the Node `fs.access()` method does not check
access-control policies on files and folders.
This means that `fs.access()` won't detect when a file is opened in
an editor like Office and is thus locked (and its parent folders as
well).
As a workaround, we can use the `fs.open()` method with a read/write
access flag. If the file is locked, the call will fail with a `EBUSY`
error.
However, this won't detect locked folders and our only option seems to
try applying changes on the folder and manage errors.
=> core/local: Detect ACL lock on open files

gui/elm/Data/UserAction.elm, gui/elm/Window/Tray/Dashboard.elm
To give users control when the synchronization is blocked by an error,
we were displaying a button within the GUI to "Give up" on the
blocking change.
This isn't without consequences though as the change could never be
synchronized and the user could lose data.
Since most changes should never block forever, we won't give this
option anymore in these situations and only offer it when we face a
remote conflict because it can in some very uncommon cases stay
unresolved.
=> gui: Allow giving up only on remote conflicts

core/remote/cozy.js, core/remote/registration.js, gui/elm/Data/UserAction.elm, gui/elm/Window/Tray/Dashboard.elm, gui/js/autolaunch.js, gui/js/help.window.js, gui/js/onboarding.window.js, gui/main.js
There 2 ways to provide an error handling function to promises:
1. as the second parameter of the `then()` call
2. as the sole parameter of a call to `catch()`
The second method has the advantage to also catch errors raised within
the call to `then()` so we should prefer it.
In some situations it was easier to use `async` functions and a
`try/catch/finally` construction.
=> Handle promises' errors outside then() calls

core/local/index.js
On Windows, files and folders can be locked by software. These locks
result in `EPERM`, `EBUSY` or `EACCES` errors when trying to modify or
move the documents (and sometimes their parent folders).
For example, Anti-Virus software can block a folder for up to a minute
and for this reason `graceful-fs`, the drop-in replacement for Node's
`fs` module used by our own dependency `fs-extra` adds a retry
mechanism to the `rename` method in case the returned error is `EPERM`
or `EACCES`.
See isaacs/node-graceful-fs@1139b6f/polyfills.js#L83
Now that we're blocking the synchronization on local filesystem
permission errors, this comes at odds with our own retry mechanism and
delays the result of our retries for a full minute during which we
display a "synchronizing" state to the user.
We probably …
=> core/local: Don't retry moving locked docs

core/app.js, core/remote/cozy.js, test/unit/app.js
When the user tries to unregister their Desktop client from its remote
Cozy, we attempt to:
1. delete the OAuth client on the remote Cozy
2. and then delete the local client config
If the remote Cozy does not exist anymore because it's either been
deleted on moved to another location (and 30 days have passed since),
we won't be able to delete the OAuth client.
In this situation we still want to delete the local config so the user
can connect its Desktop client to another Cozy (e.g. the new
location).
=> core/app: Unregister client even with deleted Cozy

core/app.js, core/local/index.js, core/remote/index.js, core/sync/errors.js, core/sync/index.js, core/syncstate.js, gui/elm/Data/UserAction.elm, gui/elm/Ports.elm, gui/elm/Window/Tray/Dashboard.elm, gui/js/tray.window.js, gui/ports.js, package.json, test/support/helpers/index.js, test/unit/local/index.js, test/unit/remote/index.js, test/unit/sync.js, yarn.lock
When we failed to synchronize a change, we would block the Sync
process and subsequently check periodically if the change could be
synchronized via dedicated methods (one for each Sync error code).
This has a major flaw though: the dedicated method must always check
for all possible causes of the synchronization failures and ways to
fix them.
For example, a file upload to the remote Cozy could fail if the Cozy
is out of disk space and the situation can be solved in 3 different
ways:
- by removing files on the Cozy
- by increasing the Cozy disk space (by purchasing some)
- by removing files on the local disk, especially the file we're
trying to Sync
We were not checking for the third solution and thus the user could be
stuck without understanding why if they ever chose it.
To simplify our …
=> core/sync: Retry failed changes that block Sync

core/remote/cozy.js, core/remote/index.js, test/unit/remote/index.js
Chromium and thus Electron, does not allow manually setting the value
of the `Content-Length` header on streamed or chunked requests for
security reasons (see
electronjs.org/docs/api/client-request#requestsetheadername-value).
This limitation means that the stack cannot know the size of a file
being uploaded until the end of the upload. If the Cozy does not have
enough disk space to fit the file then a 413 status response is sent
back to the client.
If the file is quite large, the client will have to wait for a while
to get this error response and know the request has failed.
Now that we're retrying failed requests when the Cozy is full, the
client will spend yet more time trying to upload a file that won't
fit.
We introduce here a check of the available disk space on the remote
Cozy …
=> core/remote: Check available space before upload

core/remote/index.js, core/utils/timestamp.js, test/unit/remote/index.js, test/unit/utils/timestamp.js
When sending a new file to a remote Cozy, it can happen that the stack
saves in CouchDB a creation date more recent than the one provided in
the upload request.
For example. if the uploaded file is:
- a photo with EXIF metadata
- and the creation date in the metadata does not contain a timezone
- and the photo was taken in a timezone ahead of UTC
In this case, the stack will use the EXIF date as creation date and
consider it as a UTC datetime. Therefore, the creation date as saved
on the remote Cozy will be ahead of the creation date on the local
filesystem.
If this photo is then moved on the local filesystem for example, the
stack would refuse the move as the provided modification date (i.e.
the one taken from the filesystem) will be older than the remote one.
This leads to …
=> core/remote: Use most recent modification date

core/utils/logger.js
The standard serializer of Bunyan, our logging library, strips out
most attributes of logged errors which means we can miss some
important information when those include non standard attributes.
For example, the `status` attribute of `FetchError`s are stipped out
so we can't know the returned status of failed requests.
As we've done for other attributes, we add it back to the logged
object.
=> core/utils/logger: Log FetchError's status

gui/js/lastfiles.js, test/unit/gui/lastfiles.js
The list of recently synchronized files is persisted to disk in a JSON
file. We only keep the last 250 files to keep it short.
However, it happens that we would not remove existing occurrences of
the same path when adding a file to the list although we only display
the latest occurrence in the GUI. This means that if we were to
synchronize 250 modifications on the same file. we would only display
this one file in the GUI while the list on disk would be full.
We now make sure only one occurrence is saved on disk.
=> gui/js/lastfiles: Persist same path only once

core/sync/errors.js, core/sync/index.js, test/unit/sync.js
When the remote watcher fails to fetch remote changes because the Cozy
is unreachable (i.e. we received a FetchError with a status for which
we don't have a special treatment or that treatment is notifying that
the Cozy is unreachable) we block the synchronization and stop the
remote watcher to prevent further errors.
While we were regularly pinging the remote Cozy to see if it was
reachable again and notifying the GUI with an `online` event in this
case, we were not restarting the remote watcher.
Therefore, we were not fetching remote changes anymore after the Cozy
was made unreachable once.
We now make sure the remote watcher is restarted whenever we unblock
the synchronization.
=> core/sync: Restart remote watcher when back online

CHANGELOG.md, package.json
- We're now correctly restarting the remote watcher when we detect the
Cozy is reachable again after a failed attempt at fetching changes
from the remote Cozy.
- We're now making sure the list of recently synchronized files
persisted to disk includes only one occurrence of each file since we
display only one of them. With this change, the displayed list will
always contain 250 elements once this number is reached.
=> Release 3.25.0-beta.5

CHANGELOG.md, package.json
- Some synchronization errors will now be notified to you within the
main window with information about the error itself and how to fix
it. Although automatic retries will be performed in the background,
you'll have the opportunity to request an early retry via the
interface.
Know that the synchronization will be blocked by the failing change
until it can finally be applied. This should avoid a lot of
automatically dropped changes as we would otherwise stop retrying
after the third failed attempt.
- We upgraded the framework upon which our application is built,
Electron, to v11.1.1 which is the latest stable version. This should
bring more stability to the application overall and fix an issue on
macOS Big Sur which was preventing the application from restarting …
=> Release v3.25.0

.jq, core/merge.js, core/metadata.js, core/remote/cozy.js, core/remote/document.js, core/remote/watcher/index.js, gui/notes/index.js, test/support/builders/metadata/base.js, test/support/builders/metadata/file.js, test/support/helpers/remote.js, test/unit/merge.js, test/unit/metadata.js
To make sure a file modified on the local filesystem would not be
trashed by the remote Cozy before the modification could be uploaded,
we were preventing remote trashing if the existing PouchDB record and
the trashed document did not have the same `md5sum` value.
However, if the file was also edited on the remote Cozy before being
trashed and the Desktop client did not fetch the modification before
the trash order, we get different `md5sum` values but still want to
apply the trash order on the local filesystem.
Now that we store both the `local` and `remote` metadata for each
document, we can achieve the desired result by checking whether the
existing document has the same local and remote `md5sum` instead.
We're also making the protection more generic by protecting remote
modifications …
=> core/merge: Trash files modified on the same side

core/sync/errors.js
The retry delay for blocking Sync errors which are not specifically
processed (a.k.a the default retry delay) was 0 milliseconds.
This very low value meant that the client would make requests to the
remote Cozy every few seconds (there's a little overhead to process a
change) when retrying to synchronize the changes.
This creates an unnecessary burden on the remote Cozy and the
underlying errors would probably not be solved in such a short delay
anyway.
=> core/sync/errors: Set default retry delay to 1 min

core/remote/cozy.js, core/remote/document.js, test/unit/metadata.js, test/unit/remote/cozy.js
The `_type` attribute is used by `cozy-stack` to store the doctype of
CouchDB records. In our case, this doctype is always `io.cozy.files`
and since it is not stored in the CouchDB records themselves, the data
we receive from our calls to the remote changes feed for example does
not contain this attribute.
We don't need this attribute and should not expect its presence in
returned remote records via our Flow types nor add it ourselves since
it makes it harder to compare remote data in tests with docs fetched
from our helpers.
=> core/remote: Remove _type attribute from doc types

core/remote/index.js, core/utils/timestamp.js, test/unit/remote/index.js, test/unit/utils/timestamp.js
When the Cozy stack assigns the creation and last modification dates
on remote records (it can happen when the creation request does not
include any `createdAt` and `updatedAt` attributes for example), the
dates' precision is up to the nanosecond.
When formatted as a string, the nanoseconds digits will be
concatenated to the ISO format milliseconds digits.
When the Desktop client wants to compare two date strings, it feeds
them to the `Date` JavaScript object constructor which does not
understand nanoseconds and truncates the date string after the last
millisecond digit.
This means, the resulting date will be older than the actual date
represented by the original string.
Now, when we send requests to the stack to modify existing remote
documents with local data, we want to make sure we …
=> core/remote: Handle Cozy dates with nanoseconds

core/metadata.js, core/utils/path.js, test/support/builders/metadata/base.js, test/support/builders/remote/base.js, test/unit/metadata.js, test/unit/utils/path.js
We do convert remote paths to their local counterpart and vice versa
when creating Metadata objects from remote documents for example or
when building test data from our builders.
Those paths don't have the same format:
- remote paths use a POSIX format and have a leading `/`
- local paths don't have the leading `/`
- Windows paths use a `\` as separator instead of the POSIX `/`
The Node's `path.normalize()` helper is not sufficient to convert one
format to the other when dealing with Windows paths so we introduce
our own helpers which can deal with paths on every platform we
support.
=> core/utils: Ensure correct paths on all platforms

test/integration/move.js, test/support/builders/metadata/base.js, test/support/builders/remote/dir.js, test/support/builders/remote/file.js, test/unit/local/atom/dispatch.js
Our Metadata builders allow us to generate accurate Metadata objects
from scratch or built either from a remote document or another
Metadata object or even both.
However, to accommodate for a lot of different test contexts, the logic
for ensuring we have valid `local` and `remote` attributes is quite
complex and we missed a spot for built Metadata objects marked as
up-to-date (i.e. their `sides` attribute's `local` and `remote` values
are both equal to the `target` value which means the represented
document is synced).
To cover this case, we introduce 2 functions that will help us
determine if the `local` and `remote` attributes need to be updated or
should remain untouched.
These methods are meant to be modified in case new attributes should
be considered to make the decision.
Please …
=> test/builders/metadata: Keep up-to-date sides

core/metadata.js, test/unit/metadata.js, test/unit/remote/index.js
When a creation or modification date is generated by the remote Cozy,
it has a nanosecond precision, formatted as extra millisecond digits.
When those dates are converted by the Desktop client (for comparison
pruposes) via the `Date` contructor, those extra digits are simply
dropped. The resulting date is thus older than the original one.
This can prevent future requests to the Cozy to complete so we
introduced a method to round those dates up to the next millisecond
instead.
However, we used it only during the creation of documents on the
remote Cozy and forgot to use it when dealing with updated remote
documents.
=> core/metadata: Round updated remote date times

core/remote/index.js, test/unit/remote/index.js
We have been storing more and more attributes from remote documents in
PouchDB over time but some users still have old PouchDB records
without the new attributes (they only have the path, _id and _rev for
example).
In commit ce0da21939aa6e0571fb337e33c9a55dac35ce1b we introduced a new
way to compute the most recent `updated_at` value when sending
requests to the remote Cozy to avoid sending outdated values which
would be refused by the stack (error 422 Invalid Time).
This method simply compares the stored local and remote `updated_at`
values and uses the most recent.
However, when the remote `updated_at` is not present (i.e. in old
PouchDB records), we would send `NaN` as the most recent date and
still get a 422 error.
When the local `updated_at` value is the most recent one, this …
=> core/remote: Use only existing remote updated_at

core/local/atom/add_infos.js, core/local/atom/await_write_finish.js, core/local/atom/event.js, core/local/atom/initial_diff.js, core/local/atom/win_detect_move.js, test/support/builders/atom_event.js, test/support/builders/stats.js, test/unit/local/atom/add_infos.js, test/unit/local/atom/await_write_finish.js, test/unit/local/atom/dispatch.js, test/unit/local/atom/initial_diff.js, test/unit/local/atom/win_detect_move.js
When `@atom/watcher` sends us a `deleted` event, it does not contain
the inode (or fileid) of the deleted document. Besides, we cannot get
it from the filesystem as it does not exist anymore.
Until now we were fetching the supposedly deleted inode from PouchDB
(via the document's path) only when needed. However, in some
situations like the application of a remote move on the local
filesystem on Windows (on Windows we detect moves by grouping
`deleted` and `created` events), it might be too late to get the
inode of the moved document from PouchDB (i.e. it has been erased
already by Sync after the change application has completed).
To mitigate this situation we now fetch the inode of locally deleted
documents as soon as we get the event in case it would be modified or
moved in PouchDB …
=> core/local/atom: Fetch deleted local inode ASAP

core/local/atom/add_infos.js, core/local/atom/dispatch.js, core/local/atom/incomplete_fixer.js, core/local/atom/initial_diff.js, core/local/atom/win_detect_move.js, core/local/atom/win_identical_renaming.js, core/merge.js, core/pouch/index.js, core/prep.js, core/sync/index.js, gui/notes/index.js, test/integration/sync_state.js, test/integration/update.js, test/scenarios/move_overwriting_dir/not_trashed/scenario.js, test/scenarios/move_replace_then_edit_moved_file/remote/changes.json, test/scenarios/move_replace_then_edit_moved_file/scenario.js, test/unit/local/atom/add_infos.js, test/unit/local/atom/initial_diff.js, test/unit/local/atom/overwrite.js, test/unit/local/atom/win_identical_renaming.js, test/unit/merge.js, test/unit/prep.js
In a number of the local Atom watcher, we try to fetch the PouchDB
record associated with the events we're processing. We use for that
the events' paths as the record key.
However, the record itself has 3 different path values:
- a local path
- a remote path
- a "main" path, modified by Merge each time it's changed either
locally or remotely (i.e. the document was renamed or moved)
This means that fetching the record from the local watcher via its
main path can return unexpected results (the wrong record, more than
one records or no records at all) if the document was moved or renamed
remotely and this information was merged but not fully applied.
We're usually in this situation when we're actually applying the
remote path change to the local filesystem and processing the events
fired by …
=> core/local/atom: Fetch from PouchDB via local path

core/metadata.js, core/remote/cozy.js, core/remote/errors.js, core/remote/index.js, core/sync/errors.js, core/sync/index.js, core/utils/conflicts.js, test/integration/add.js, test/integration/move.js, test/scenarios/move_replace_then_edit_moved_file/atom/linux.json, test/scenarios/move_replace_then_edit_moved_file/atom/win32.json, test/scenarios/move_replace_then_edit_moved_file/local/darwin.json, test/scenarios/move_replace_then_edit_moved_file/scenario.js, test/scenarios/replace_file_with_file/scenario.js, test/scenarios/run.js, test/support/helpers/index.js, test/support/helpers/remote.js, test/unit/helpers_merge.js, test/unit/metadata.js, test/unit/remote/index.js, test/unit/utils/conflicts.js
When the stacks responds to a Sync request with a 409 status error, it
means the change we're trying to push is conflicting with an existing
document.
This can happen when we try to push a new document or move an existing
one to a location where another document with the same name exists.
Those conflicts should be managed at the Merge level but there are
situations where the conflict is only detected when trying to apply
the local change on the remote Cozy:
1. we have another change to apply that will free the give name by
moving the document or renaming it
2. we have not yet merged the remote change that took the name and
would have generated a conflict copy
3. we have not merged the remote change that took the name and never
will because we abandoned that change in the past
We can solve …
=> core/sync: Create conflict copy on 409 errors

core/remote/cozy.js, package.json, test/support/builders/remote/dir.js, test/support/builders/remote/file.js, test/support/builders/remote/note.js, test/unit/remote/cozy.js, yarn.lock
By default `cozy-client-js` will sanitize the names of documents (i.e.
trim them) when sending requests to the remote Cozy.
This is a problem for the Desktop client as we won't update local
names if their remote counterparts were sanitized and we can end up
with missing parent documents or other similar errors.
Since v0.18.0, `cozy-client-js` has a `noSanitize` option for all
requests that would sanitize names by default. If this option is
passed and set to `true`, `cozy-client-js` will refrain from
sanitizing.
=> core/remote: Don't sanitize doc names in requests

core/remote/index.js, package.json, test/unit/remote/index.js, yarn.lock
Since Electron prevents us from setting the `Content-Length` header
when uploading a file as a chunked request, the stack cannot respond
with an error right away when the file is either larger than the max
file size or the available space on the Cozy.
This means we have to wait until the end of the request to get that
response back thus wasting time and resources.
As a workaround, we were checking if the Cozy had enough space before
making the request but this has 2 major flaws:
- we make an extra request to the server each time we try to upload a
file (or retry)
- the available space can change between the time we make this request
and the upload one
However, the stack can now read the file size from the `Size`
query-string parameter as well as the `Content-Length` header and …
=> core/remote: Send file size via query-string

core/remote/watcher/index.js, test/unit/remote/watcher.js
In a effort to consolidate the `trashed` and `deleted` attribute usage
we replaced a condition in the remote watcher based on the `trashed`
attribute to use the `deleted` attribute.
This condition was meant to treat "new" remote records for documents
previously trashed as additions.
While we still want this behavior, the usage of the `deleted`
attribute goes against another desired behavior which is to cancel the
local deletion of documents which were moved on the remote Cozy.
To accommodate both we go back to using the `trashed` attribute via a
call to the `inRemoteTrash()` helper which carries more meaning than
the `trashed` attribute alone.
=> core/remote/watcher: Deleted file move is move

core/remote/errors.js, core/sync/errors.js, core/sync/index.js, gui/elm/Data/UserAction.elm, test/integration/sync_state.js, test/integration/update.js, test/unit/sync.js
We specifically handle 4xx remote errors (i.e. Fetch errors with a 
status code between 400 and 499) so that they won't show up as an 
unreachable Cozy to the user.
When we can, we provide new errors messages to help the user figure out
how to fix the issue and resume the synchronization.
Some errors will be sent to Sentry so we can try to solve them before
too many users encounter them.
=> core/sync: Handle 4xx remote errors

CHANGELOG.md, package.json
- Files that were modified then trashed on your Cozy before the
Desktop client could fetch the modification will be trashed on your
computer and your Cozy and not re-uploaded.
- The workaround we introduced in the previous release to help
synchronize modifications to your remote Cozy when modification
dates are not the same in the local database and the remote Cozy
created a regression for users who locally modified documents that
had not been modified in a very long time and did not have the
remote modification date stored in the local database.
For those documents, we'll skip the workaround and hope that the
local modification date is more recent than the remote one (which is
very likely).
- If some of your documents (files like directories) have local names …
=> Release v3.26.0-beta.1

core/merge.js, core/metadata.js, core/move.js, core/pouch/index.js, core/pouch/migrations.js, test/property/runner.js, test/unit/merge.js, test/unit/pouch/index.js
The historical `sides.local` and `sides.remote` attributes are hints
used in conjunction with `sides.target` to tell the synchronization
process on which side changes should be applied.
But we now also have `local` and `remote` attributes which store the
document's metadata on the given side (i.e. the local filesystem or
the remote Cozy).
Each side attribute (i.e. `local` or `remote`) should only exist on a
record if there is a matching `sides.remote` attribute and vice versa.
We take measures to make sure this is true in the future and that
existing records are cleaned up.
=> core: Sync `sides` attribute with side attributes

CHANGELOG.md, package.json
- Some expectations made in the previous beta release on the local
metadata stored in PouchDB were not met and resulted in exceptions
being thrown thus stopping the synchronization.
We've taken measures to make sure those expectations are met in the
future and existing metadata is cleaned up to meet these
expectations as well.
=> Release v3.26.0-beta.2

CHANGELOG.md, package.json
- Files that were modified then trashed on your Cozy before the
Desktop client could fetch the modification will be trashed on your
computer and your Cozy and not re-uploaded.
- The workaround we introduced in the previous release to help
synchronize modifications to your remote Cozy when modification
dates are not the same in the local database and the remote Cozy
created a regression for users who locally modified documents that
had not been modified in a very long time and did not have the
remote modification date stored in the local database.
For those documents, we'll skip the workaround and hope that the
local modification date is more recent than the remote one (which is
very likely).
- If some of your documents (files like directories) have local names …
=> Release v3.26.0

CHANGELOG.md, package.json
- The mechanism we introduced in the last version to resolve
conflicts from the synchronization process when we've run out of
options was assuming that the current date of the computer would
always be greater than the last modification date of the document
being renamed on the remote Cozy.
Since this is not always the case and the remote Cozy will refuse
the renaming in those situations, we'll use the same workaround than
for the other requests and send the most recent date between the
current local date and the last modification date of the remote
document.
=> Release v3.26.1-beta.1

CHANGELOG.md, package.json
- Whenever a file move or name change is synchronized, we'll properly
remove its source path entry from the Recent list in the main
window. Its destination path entry will remain as expected.
=> Release v3.26.1-beta.2

CHANGELOG.md, package.json
- The mechanism we introduced in the last version to resolve conflicts
from the synchronization process when we've run out of options was
assuming that the current date of the computer would always be
greater than the last modification date of the document being
renamed on the remote Cozy.
Since this is not always the case and the remote Cozy will refuse
the renaming in those situations, we'll use the same workaround than
for the other requests and send the most recent date between the
current local date and the last modification date of the remote
document.
- Whenever a file move or name change is synchronized, we'll properly
remove its source path entry from the Recent list in the main
window. Its destination path entry will remain as expected.
=> Release v3.26.1

core/merge.js, core/remote/watcher/index.js, test/unit/helpers_merge.js, test/unit/remote/watcher.js
When merging a local change, we were checking if its parent folder
record existed in PouchDB. To make sure the whole hierarchy was
present in the database, we would create any missing parent folder
record with only a few attributes: their path and update date.
However, this generates records missing most attributes that we rely
on more and more (i.e. inode, local and remote attributes…) and should
not be necessary as a document cannot exist on the local filesystem
without its parent folder and so we should receive an event leading us
to merge that parent folder record at some point.
This is why we'll be more optimistic and rely on an eventual
consistency regarding the parent hierarchy of any given record in
PouchDB.
Besides, we were not creating those parent records for remote
documents …
=> core/merge: Stop creating local parent records

core/remote/index.js, core/sync/index.js, test/integration/move.js, test/support/builders/remote/dir.js, test/support/builders/remote/file.js, test/unit/remote/index.js
After reaching the maximum number of failed synchronization attempts
due to a missing remote document, we take steps to finally get the
current change synchronized and move on.
If the change in question is a move of the document missing on the
remote Cozy, potentially overwriting another document, then we'll try
to synchronize the local document as a new document.
However, this involves removing from the PouchDB record the attributes
used by Sync to detect that the document has been moved. Otherwise, on
the next round of synchronization, Sync will try again to move the
document that no longer exists on the Cozy.
We also remove the overwriting hint as the move action first attempts
to trash the overwritten document and this part should not fail
because the document we're trying to move …
=> core/sync: Handle missing doc remote move retries

core/merge.js, test/integration/move.js, test/scenarios/run.js, test/support/helpers/config.js, test/support/helpers/index.js, test/support/helpers/remote.js, test/unit/merge.js
Trying to propagate a folder move when it does not exist on the other
side yet would fail. This is why we transform the move of an unsynced
folder into a creation at its destination path.
However, we did not take into account the possibility that the folder
could have children which path needed to be modified as well.
We also did not take into account the possibility of a conflict at the
destination path.
We're now making sure overwriting, conflict resolution and children
updates are done when transforming the folder move into a folder
creation.
=> core/merge: Unsynced folder move updates children

core/incompatibilities/platform.js, core/metadata.js, core/sync/errors.js, core/sync/index.js, core/utils/logger.js, test/integration/conflict_resolution.js, test/support/builders/metadata/base.js, test/support/helpers/remote.js, test/unit/gui/notes/index.js, test/unit/helpers_merge.js, test/unit/local/atom/dispatch.js, test/unit/local/atom/win_detect_move.js, test/unit/local/chokidar/normalize_paths.js, test/unit/local/chokidar/prepare_events.js, test/unit/local/index.js, test/unit/merge.js, test/unit/move.js, test/unit/pouch/index.js, test/unit/remote/index.js, test/unit/remote/watcher.js
In the same way we enforce the presence of a `remote` attribute when
the `sides.remote` attribute is present on a PouchDB record we're
about to save, we should encore the presence of a `local` attribute
when the `sides.local` attribute is present.
Not doing so means we could potentially save incoherent records which
will create issues down the road.
If some records fail to be saved we should be able to find the root
cause and fix it.
=> core/metadata: Enforce `local` invariant

core/merge.js, test/support/builders/metadata/base.js, test/unit/merge.js
We previously added a rule to cancel any file trashing if the file was
modified on the other side to avoid stressing the user over lost data
(although we always send documents to the local or remote trash).
Unfortunately, the condition we used to detect this situation was not
precise enough and we started cancelling trashing of files that were
previously modified on the same side.
We don't want to cancel the trashing in this case because we assume
that the user is aware that she's deleting the modified version.
=> core/merge: Trash file when modified on same side

core/merge.js, test/scenarios/trash_file_and_move_parent/atom/linux.json, test/scenarios/trash_file_and_move_parent/atom/win32.json, test/scenarios/trash_file_and_move_parent/local/darwin.json, test/scenarios/trash_file_and_move_parent/remote/changes.json, test/scenarios/trash_file_and_move_parent/scenario.js, test/unit/merge.js
When a moved record is also marked for deletion, Sync will propagate
the move instead of the trashing because the presence of the
`moveFrom` attribute will have precedence over the presence of the
`deleted` attribute.
We could change the move detection in Sync but it seems better not to
move deleted children at all at the Merge level and simply propagate
their deletion at their original path.
=> core/merge: Don't move deleted child with parent

core/local/chokidar/analysis.js, core/merge.js, core/metadata.js, test/scenarios/move_and_trash_dir/atom/linux.json, test/scenarios/move_and_trash_dir/atom/win32.json, test/scenarios/move_and_trash_dir/local/darwin.json, test/scenarios/move_and_trash_dir/remote/changes.json, test/scenarios/move_and_trash_dir/scenario.js, test/scenarios/move_and_trash_file/atom/linux.json, test/scenarios/move_and_trash_file/atom/win32.json, test/scenarios/move_and_trash_file/local/darwin.json, test/scenarios/move_and_trash_file/remote/changes.json, test/scenarios/move_and_trash_file/scenario.js, test/scenarios/move_and_trash_file_from_inside_move/local/darwin.json, test/scenarios/move_and_trash_file_from_inside_move/scenario.js, test/scenarios/trash_file_and_move_parent/atom/linux.json, test/scenarios/trash_file_and_move_parent/atom/win32.json, test/scenarios/trash_file_and_move_parent/local/darwin.json, test/scenarios/trash_file_and_move_parent/remote/changes.json, test/scenarios/trash_file_and_move_parent/scenario.js, test/unit/local/chokidar/analysis.js, test/unit/merge.js
When a moved folders is also marked for deletion, Sync will propagate
the move instead of the trashing because the presence of the
`moveFrom` attribute will have precedence over the presence of the
`deleted` attribute.
We could change the move detection in Sync but it seems better to
trash the source of the moved folder and discard the destination
record at the Merge level and simply propagate its deletion at its
original path.
In case the trashed folder was overwriting another document, we make
sure this overwritten record will also be marked for deletion as it
does not exist on the trashing side anymore.
=> core/merge: Trash source of moved folders

core/merge.js, test/support/builders/metadata/base.js, test/unit/merge.js
When we took care of trashing the overwritten document of a trashed
overwriting move, we made the wrong assumption that the overwritten
and overwriting records would not have the same PouchDB `_id` and thus
could be modified together via a `Pouch.bulkDocs()` call.
It turns out that we reuse the _id (and _rev) of overwritten records
when merging an overwriting move so that only one record with the
destination path exists in PouchDB at the same time (i.e. to avoid
queries mismatches).
Thus, when trashing an overwriting move we'll only update the
destination record as if it was the deleted overwritten record.
We did not catch this problem because our test Metadata builders did
not correctly emulate an overwriting move as they were not reusing the
overwritten record's _id and _rev attributes. …
=> core/merge: Fix trashing of overwriting moves

core/merge.js, core/sync/index.js, dev/capture/remote.js, test/scenarios/move_and_replace_file_with_update/atom/linux.json, test/scenarios/move_and_replace_file_with_update/remote/changes.json, test/scenarios/move_and_replace_file_with_update/scenario.js, test/scenarios/update_delete_then_replace_file/atom/linux.json, test/scenarios/update_delete_then_replace_file/remote/changes.json, test/scenarios/update_delete_then_replace_file/scenario.js, test/unit/merge.js
When a specific path is overwritten more than once before
synchronization, we need to keep track of the first overwritten record
as it contains the information we need to propagate its deletion to
the remote Cozy and transfer its references to the new document in its
stead.
=> core/merge: Don't replace existing `overwrite`

core/sync/index.js, gui/main.js, test/unit/sync.js
The recent changes made to the error management in Sync and the remote
watcher introduced a regression preventing us from correctly detecting
and handling revoked OAuth client errors.
=> Fix revoked client error detection on start

CHANGELOG.md, package.json
- The Electron framework was upgraded to v12.0.0. This major version
fixes a lot of security errors as well as other smaller errors like
crashes.
- The Desktop client will now use the Electron API to send local
folders and files to the OS trash. This should ensure that these
documents can be restored from the trash via the default trash
operations and that their names are preserved.
- Missing parent folders when merging or propagating a child change
will not be created by default as this could lead to conflicts down
the road. We will instead rely on retry mechanisms to make sure
ancestor folders exist before saving a document record in PouchDB or
propagating it to the remote Cozy.
Local parent directories will still be created if missing when
propagating a …
=> Release v3.27.0-beta.1

CHANGELOG.md, package.json
- The Electron framework was upgraded to v12.0.0. This major version
fixes a lot of security errors as well as other smaller errors like
crashes.
- The Desktop client will now use the Electron API to send local
folders and files to the OS trash. This should ensure that these
documents can be restored from the trash via the default trash
operations and that their names are preserved.
- Missing parent folders when merging or propagating a child change
will not be created by default as this could lead to conflicts down
the road. We will instead rely on retry mechanisms to make sure
ancestor folders exist before saving a document record in PouchDB or
propagating it to the remote Cozy.
Local parent directories will still be created if missing when
propagating a …
=> Release v3.27.0

core/sync/errors.js, core/sync/index.js, test/unit/sync.js
When the remote Cozy becomes unreachable, two processes can throw
errors which will block the synchronization process and initiate a
retry interval:
- the synchronization process itself if the error was thrown while
trying to propagate a change
- the remote watcher when trying to fetch the latest remote changes
In the synchronization process errors out right before the remote
watcher tries to fetch the latest changes (i.e. the Cozy is thus still
unreachable), the reference to the retry interval initiated by the
synchronization process will be overwritten by the reference to the
retry interval initiated by the remote watcher.
This reference is held by the `Sync.retryInterval` variable.
Loosing the reference to the 1st retry interval means it will run in
parallel to the 2nd one and we won't …
=> core/sync: Prevent parallel retry intervals

gui/main.js
When the client is launched with more than 2 argument (the first 2
being the path to the application and an empty string), we assume the
last one is a path to a Cozy Note on the file system as this is the
way Linux and Windows notify us of an opening request from the file
explorer.
However, when the client is started automatically with the computer,
the `--hidden` argument is added by `auto-launch` to make sure the
client window is not opened right away.
In this case, the client will assume `--hidden` is a path to a note
and will try to open it. Since it's not a path at all, it will fail
with a generic error, triggering the display of an error popup.
This error does not prevent the client from starting however.
We'll now check if the "path" ends with `.cozy-note` to filter out all …
=> gui: Avoid unwanted note openings

core/config/.cozyignore
MacOS allows users to use custom folder icons and saves them as a
hidden file of the given folder with the name `Icon\r`.
However, cozy-stack forbids the presence of `\r` in document names so
these icons block the synchronization.
We think it's better to ignore those files rather than blocking the
user.
=> macOS: Ignore custom folder icons

core/prep.js, test/unit/prep.js
We should never have to process document moves from one path to the
exact same one. However, we've witnessed it happening in some
situations and we used to throw errors in these cases.
It seems like we should still merge the side metadata in these cases
and transforming the moves into updates seem like a good way to do
that.
It is still unclear how we get into these situations but since the
change does not trigger any test failure it seems pretty safe to test
it if not in production at least in a beta release.
=> core/prep: Transform same path moves into updates

gui/js/window_manager.js, gui/main.js
Recent changes in Electron might have altered the behavior of
`Window.setVisibleOnAllWorkspaces()` effectively making the app icon in
the macOS dock show whenever we create a new window and call this
function (e.g. the Tray window which is hidden by default).
Besides, it seems that displaying an Electron app icon in the dock
prevents the OS from shutting down, displaying an error message to the
user inviting them to force-kill the application.
Since we don't need to show our windows on all workspaces (we only want
it displayed on the workspace it was opened from) we can stop using
this function and thus kill two birds with one stone by preventing
unexpected icons in the dock and leaving the OS shutdown correctly.
=> gui: Hide dock icon on macOS by default

CHANGELOG.md, package.json
- The client will only trigger one synchronization retry loop when
encountering an unreachable Cozy error in both the synchronization
process and the remote watcher very closely.
- New remote documents whose path would be incompatible with the local
filesystem will not be ignored anymore.
- Local documents who've been moved or renamed remotely to a path that
would be incompatible with the local filesystem won't be trashed
anymore.
- Changes that can't be synchronized because the document has an
incompatible name or path with the local filesystem will now suspend
the synchronization and an error message will be displayed so you
can take action.
- Moves for which the destination path is exactly the same as the
source path will now be treated as modifications …
=> Release v3.28.0-beta.1

core/incompatibilities/platform.js, core/pouch/migrations.js
Add a `type` attribute to existing path length incompatibilities in
PouchDB records so we can use it to filter incompatibilities more
easily (and simplify our type checking) and remove any Windows path
length incompatibility if the path length is less than the new 32766
characters limit.
=> core/pouch: Migrate path length incompatibilities

gui/js/proxy.js, test/unit/gui/proxy.js, test/unit/remote/cozy.js
When the client encounters a network issue on Windows or macOS, it
sometimes "caches" this response and will return it to every subsequent
request.
We make the assumption that this "cache" is handled by Chromium and as
such can be disabled by adding the `Cache-Control: no-cache` header to
all responses.
Since we don't want the remote Cozy to do this (and thus disable
useful caches for all clients) we define an Electron response hook to
add it on the client side.
We've seen improvements during a test phase but don't have any hard
evidence that this really solves the issue.
=> gui/proxy: Prevent browser caching on all requests

CHANGELOG.md, package.json
Improvements for Windows and macOS users:
- After the remote Cozy has been found unreachable because of a
network error such as a interface change, the subsequent requests
won't fail anymore with the same error once a stable connection is
back.
- Documents that had been previously found incompatible with the local
filesystem because of the previous path length limit will be updated
to take the new limit into account. Most of them should thus become
compatible.
- Synchronization error messages displayed in the main window will now
only contain the name of the document involved instead of its
complete path.
=> Release v3.28.0-beta.2

CHANGELOG.md, package.json
- The client will only trigger one synchronization retry loop when
encountering an unreachable Cozy error in both the synchronization
process and the remote watcher very closely.
- New remote documents whose path would be incompatible with the local
filesystem will not be ignored anymore.
- Local documents who've been moved or renamed remotely to a path that
would be incompatible with the local filesystem won't be trashed
anymore.
- Changes that can't be synchronized because the document has an
incompatible name or path with the local filesystem will now suspend
the synchronization and an error message will be displayed so you
can take action.
- Moves for which the destination path is exactly the same as the
source path will now be treated as modifications …
=> Release v3.28.0

core/sync/index.js, core/syncstate.js, gui/elm/Data/UserAction.elm
We try to avoid showing a « Synchronization suspended » status without
any error message or after the error was fixed.
=> Improve user communication around synchronization errors

core/local/chokidar/analysis.js, core/local/chokidar/local_change.js, test/unit/local/chokidar/analysis.js
On macOS, since local changes are buffered, when a document is moved
within a folder that is also moved, we end up with a move change for
which the old path (i.e. the path used to query PouchDB for the old
record) won't be valid anymore when it comes to merging this event.
e.g.:
when doing those 2 moves:
- `dir` → `my dir`
- `dir/file` → `my dir/my file`
the old path of the file move change will be `dir/file` while the
saved path in the PouchDB record will be `my dir/file` once we've
merged the directory move.
To handle those cases, we detect when a move is done inside another
move and update its old path to take into account its parent move.
However, the logic used to detect them, would also consider the move
of a document from outside the moved directory into it as a "move
inside a …
=> core/local/chokidar: Don't squash moves into moves

core/metadata.js, core/sync/index.js, test/unit/metadata.js, test/unit/sync.js
It appears we can end up in situations where the only remaining side
is smaller than the target.
This can lead to conflicts when merging a file modification on the
same side when we don't expect it.
Although we don't know how we get into this situation (it could be
related to multiple sync errors on the other side which is later
dissociated), we want to mitigate its consequences by making sure the
`Metadata.isUpToDate()` and `Metadata.isAtLeastUpToDate()` methods
consider a single side as up-to-date.
=> core/metadata: Consider single side as up-to-date

CHANGELOG.md, package.json
- The client will now detect when the connected Cozy has been deleted
and will show an error message accordingly. The synchronization will
be stopped until you connect your client to another Cozy.
- We've worked on the process which decides if a synchronization error
needs to be displayed or not to make sure you get alerted with the
suspended synchronization status only if accompanied with an
explicit error message.
- In some rare situations where a document that was previously
synchronized is now only present on one side (i.e. we're in the
middle of re-synchronizing it) a conflict could be generated if the
document was modified on that remaining side.
We've introduced some mitigations to avoid generating those
conflicts.
- Moving …
=> Release v3.28.1-beta.1

core/config.js, core/merge.js, core/metadata.js, core/remote/change.js, core/remote/constants.js, core/remote/cozy.js, core/remote/document.js, core/remote/index.js, core/remote/watcher/index.js, core/remote/watcher/normalizePaths.js, test/support/builders/index.js, test/support/builders/remote/base.js, test/support/builders/remote/dir.js, test/support/builders/remote/erased.js, test/support/builders/remote/file.js, test/support/builders/remote/note.js, test/support/doubles/cozy_stack.js, test/unit/config.js, test/unit/metadata.js, test/unit/remote/cozy.js, test/unit/remote/index.js, test/unit/remote/offline.js, test/unit/remote/watcher.js
When a folder has been unsynced via the differential sync API, it is
seen as deleted by the Desktop client and so are its children.
However, when the same folder is resynced, the Desktop client will
only see a change for the folder.
To make sure we'll resync all its content, we will fetch it and
process all found remote documents as additions.
The way we detect a folder for which we need to fetch the content is
if we detect the addition of a folder whose remote revision is greater
than 1 (i.e. it was not just created on the Cozy).
If a new folder is modified on the Cozy before the client has detected
its addition via the changes feed, we'll treat it as a resynced folder
and fetch its content while we already have it in the feed.
We expect this not to be an issue though. the remote watcher …
=> core/remote/watcher: Fetch resynced folders content

yarn.lock
Upgrading Chokidar leads to an upgrade of `fsevents` (i.e. one of
Chokidar's own dependencies) which received a fix in v2.3.2 preventing
crashes we see in our tests on macOS, especially when run in Github
Actions.
See https://github.com/fsevents/fsevents/issues/355 for more info.
=> Bump Chokidar to v3.5.2

core/remote/cozy.js, test/support/builders/remote/erased.js, test/unit/remote/cozy.js, test/unit/remote/offline.js
The remote changes feed contains every change that was ever made on a
Cozy and also changes made on indexes (they're documents as well).
This means that a Cozy that has seen a lot of changes, even for
completely deleted documents, will have a very large changes feed and
thus will require many requests during the initial synchronization of
a new Desktop client.
To avoid losing time in fetching unnecessary documents and in hope of
decreasing the I/O consumption during this phase, we implement a
specific initial fetch that will only fetch the latest version of
remote documents and avoid downloading deleted ones.
=> core/remote/cozy: Skip deleted docs on inital sync

core/remote/constants.js, core/remote/cozy.js, core/remote/errors.js, core/remote/index.js, core/sync/errors.js, core/sync/index.js, gui/elm/Data/UserAction.elm, gui/elm/Window/Tray/Dashboard.elm, gui/locales/de.json, gui/locales/en.json, gui/locales/eo.json, gui/locales/es.json, gui/locales/fr.json, gui/locales/it_IT.json, gui/locales/ja.json, gui/locales/nl.json, gui/locales/nl_NL.json, gui/locales/pl.json, gui/locales/sq.json, gui/locales/zh_CN.json, test/unit/remote/cozy.js
Based on a restriction in Swift, remote Cozies using this storage
backend limit the size of files to 5 GiB.
See https://docs.openstack.org/kilo/config-reference/content/object-storage-constraints.html
When a client tries to send a file larger than that, the Cozy will
respond with a 413 status error before all the bytes have been sent
(i.e the size is a parameter of the request so the Cozy doesn't need
all the bytes to compute the file length).
However, such short ended requests are not properly handled by
Chromium and thus Electron. In this situation, they won't pass to the
requester the remote response but an in-house error whose message
contains `mojo result is not ok`.
To make sure the Desktop handles those errors properly, we catch those
in-house errors and try to reconstruct the …
=> core/remote: Catch 413 errors for large files

core/sync/index.js, test/integration/add.js, test/support/helpers/index.js
This test makes sure the PouchDB record of a remote only file which is
deleted on the Cozy before it's downloaded by Sync gets erased.
We erase it to ensure conflicts won't arise from the creation of a
local document with the same path.
=> test: Missing remote file record gets erased

core/remote/cozy.js, package.json, test/support/builders/atom_event.js, test/support/builders/checksum.js, test/support/builders/index.js, test/support/builders/metadata/file.js, test/support/builders/remote/file.js, test/support/builders/remote/note.js, test/unit/local/index.js, test/unit/remote/cozy.js, test/unit/remote/index.js, yarn.lock
If a local file is modified while we're uploading it to the remote
Cozy and grows larger, we'll end up sending more data than hinted to
the stack via the `Content-Length` request parameter.
In this case, the stack will respond with a 412 error (i.e. invalid
metadata) when we hit the expected file size, thus closing the request
prematurely.
When this happens, Electron throws its cryptic `mojo result is not ok`
error and we don't get the 412 response.
Like we do for 409 and 413 responses, we'll try to recreate the 412
`FetchError` by summing up the lengths of all chunks that were sent to
the stack and comparing the total with the sent `Content-Length`
header.
=> core/remote: Recreate 412 errors during uploads

core/local/chokidar/analysis.js, core/local/chokidar/initial_scan.js, core/local/chokidar/prepare_events.js, core/local/chokidar/watcher.js, test/unit/local/chokidar/analysis.js, test/unit/local/chokidar/prepare_events.js, test/unit/local/chokidar/watcher.js
The initial scan step in the Chokidar watcher can be potentially long
when a lot of documents are present in the local synchronization
directory (i.e. there are many events to process).
The step is run as part of the asynchronous events flushing callback
and could thus potentially be run each time events are flushed.
To prevent this, we mark the `initialScan` object (if it exists) as
flushed at the very beginning of the flushing callback.
However, the step itself does not check this attribute before
processing events and so a second flush while an initial scan is being
run could trigger a second initial scan run.
We now check the `flushed` attribute's value before running an initial
scan step and move its assignment to the step itself to co-locate it
with its usage.
Please make sure the …
=> core/local/chokidar: Run initial scan step once

CHANGELOG.md, package.json
- The last modification and last access dates on Windows were not
precise enough for Cozy Desktop to detect sub-second local
modifications. This would sometimes lead to `Invalid metadata`
errors when sending modifications to the remote Cozy.
We've increased this precision to include milliseconds so we should
not lose any local modification anymore.
- Due to a "bug" in Chromium (i.e. which we use through Electron to
provide our network stack), some error responses sent by the remote
Cozy to our file upload requests are transformed into a cryptic
error which we cannot deal with directly. In such cases, we end up
interpreting them as unreachable Cozy errors which is misleading to
you.
We caught and fixed two of those cases:
* when …
=> Release v3.28.1-beta.2

core/utils/logger.js
Whenever we run the app in debug mode, a `debug.log` file is created
and logs are written to it.
However, if it already exists, it is deleted, preventing any running
code in debug mode from writing to it until it is launched again.
To avoid this annoying situation, we now empty the file.
=> dev: Empty debug log file instead of deleting it

core/local/index.js, core/remote/index.js, core/sync/index.js, core/writer.js, test/support/doubles/side.js, test/unit/local/index.js, test/unit/remote/index.js, test/unit/sync.js
Our writers are meant to write either to the `remote` Cozy or the
`local` filesystem.
Based on that, we were associating with each one a side name, passed
separately as a string.
To simplify some calls and to make sure we can never have a mismatch
between the writer and the associated side name, we added the name to
the writers themselves.
=> core: Add side name to writers

core/remote/errors.js, core/sync/index.js, core/utils/fs.js, test/unit/local/index.js, test/unit/utils/fs.js
Since we've started using Electron's `shell.trashItem()` method to
send local files to the local Trash, errors raised when the file does
not exist anymore have not been properly handled.
This resulted in lots of retries during Sync and PouchDB records left
in the database for no reason.
This situation finds its root in the fact that `trashItem()` does not
raise a `SystemError` with status code `ENOENT` when the document does
not exist but its own error type without any code.
We'll now handle this error (i.e. with message `Failed to move item to
trash`) as if the file was already trashed if it can't be found at the
expected path.
We'll throw the original error otherwise.
=> sync: Handle doc already in trash errors

CHANGELOG.md, package.json
- We'll now consider the propagation of a move to the trash either on
the local filesystem or the remote Cozy as successful when the given
document does not exist anymore.
This will prevent delays during the synchronization process since we
won't have to deal with retries.
=> Release v3.28.1-beta.3

CHANGELOG.md, package.json
- We've realized that the errors thrown when trying to trash a missing
local document would not always be caught because of an unexpected
message localization.
We've completely changed the way we catch these errors to not depend
on their message altogether.
=> Release v3.28.1-beta.4

CHANGELOG.md, package.json
- The client will now detect when the connected Cozy has been deleted
and will show an error message accordingly.
The synchronization will be stopped until you connect your client to
another Cozy.
- We've worked on the process which decides if a synchronization error
needs to be displayed or not to make sure you get alerted with the
suspended synchronization status only if accompanied with an
explicit error message.
- In some rare situations where a document that was previously
synchronized is now only present on one side (i.e. we're in the
middle of re-synchronizing it) a conflict could be generated if the
document was modified on that remaining side.
We've introduced some mitigations to avoid generating those
conflicts.
- Due to a "bug" in Chromium (i.e. …
=> Release v3.28.1

core/utils/notes.js, package.json, yarn.lock
The future Cozy Notes with photos will be saved as `tar` archives
containing the markdown export as the first file, named `index.md` and
all the photos included in the note.
As a first step to support those notes in Desktop's degraded mode
(i.e. when we're offline and can't open the note or we can't find the
associated note anymore on the remote Cozy) we will unpack the `tar`
archive and read the content of `index.md`.
Photos included in the note with an HTTP URL will be displayed but
photos included as files won't for now as it would require modifying
the markdown code to replace their ids with their local `file://` URI.
Notes without photos will still be markdown files but we'll try to
unpack them as `tar` archives as well since we can't really tell them
apart easily.
If the unpacking …
=> core/utils/notes: Unpack notes archives

CHANGELOG.md, package.json
- Cozy Notes with photos will be exported as a tar archive instead of
a simple markdown file. Therefore, the client will now unpack the
markdown file from the archive when displaying a note in a degraded
mode (i.e. when you're offline or the actual note can't be found on
the remote Cozy).
=> Release v3.29.0-beta.1

.jq, dev/setup.sh, package.json
Redacting notes in errors prevents us from reading the content of
notes in log files and has the benefit of reducing the amount of text
displayed when searching through log files.
The `shortPath` helper keeps only the name of files and directories in
the `path` field of log lines to increase the readability of logs when
we don't care about the whole hierarchy.
Avoid depending on `bash` to run the dev script and run it directly
within the `cozy-app-dev` Docker container.
It also makes it easier to port the script to run it outside Docker.
=> dev: Small changes

CHANGELOG.md, package.json
- Cozy Notes with photos will be exported as a tar archive instead of
a simple markdown file. Therefore, the client will now unpack the
markdown file from the archive when displaying a note in a degraded
mode (i.e. when you're offline or the actual note can't be found on
the remote Cozy).
- Error messages will now be properly localized and the document names
included in some of them should be properly displayed instead of
their type.
=> Release v3.29.0

core/local/chokidar/analysis.js, core/local/chokidar/local_change.js, test/unit/local/chokidar/analysis.js
The `defaultSorter()` sort method used after the initial scan by the
Chokidar watcher to sort changes before merging them is supposed to
sort deletion changes before addition changes on the same path.
However, the way we compared those changes was flawed and in the
case the deletion change would come before the addition change
before sorting, our algorithm would switch places between them (i.e.
the "deleted path" of the addition change would be null and equal to
the "added path" of the deletion change).
We now make sure only non-null and normalized paths can be deemed
equal.
=> core/local/chokidar: Fix analysis defaultSorter

test/scenarios/move_and_replace_file_with_update/scenario.js, test/scenarios/move_and_update_file/scenario.js, test/scenarios/move_replace_then_edit_moved_file/scenario.js, test/scenarios/move_then_replace_file/scenario.js, test/scenarios/ods_update_through_osl_tmp_file/scenario.js, test/scenarios/replace_file_with_file/scenario.js, test/scenarios/run.js, test/scenarios/update_delete_then_replace_file/scenario.js, test/scenarios/update_file/scenario.js, test/scenarios/update_through_unignored_tmp_file/scenario.js, test/support/helpers/scenarios.js
Test captures are a way to get reproducible scenarios runs by saving
the local or remote events once and pushing them to the watchers on
later runs after the actual actions of the scenarios have been applied.
However, some scenarios can only succeed by getting events when each
action is actually applied as they would otherwise contain outdated
values (e.g. file inodes for a move event if we have run a file
update afterwards).
This is why we introduced a way to run scenarios without using the
captures. We started with local Atom scenarios since this watcher's
behavior is more dependent on timing but we now face issues with
Chokidar scenarios as well.
We will introduce the same mechanism for remote scenarios when
needed.
=> tests: Enable Chokidar scenarios without captures

core/local/chokidar/local_change.js, test/scenarios/move_and_update_file/scenario.js, test/scenarios/replace_file_with_file/scenario.js, test/unit/local/chokidar/analysis.js
In case a file is modified right after being moved (i.e. within the
buffering period), we want to make sure the `FileMove` event will be
marked as an update only if its `md5sum` AND `mtime` have changed or
the following `FileUpdate` event is included into it.
Since we don't have access to filesystem events when documents are
changed while the client was stopped, we have logic to detect when a
`FileMove` is also a `FileUpdate`. In this case, the `FileMove` will
be marked as an update and, once all changes have been detected,
we'll generate a custom `FileUpdate` change to make sure it is
merged.
However, when the client is running, if we have:
- a file move followed by a file modification where the inode has
changed (e.g. when we're applying a remote file move + update on
the local …
=> core/chokidar: Fix file move and update detection

core/merge.js, core/metadata.js, core/move.js, core/sync/index.js, test/integration/conflict_resolution.js, test/integration/move.js, test/integration/notes.js, test/integration/trash.js, test/scenarios/move_dir_and_replace_subfile/scenario.js, test/support/builders/metadata/base.js, test/support/helpers/index.js, test/unit/local/atom/dispatch.js, test/unit/local/atom/initial_diff.js, test/unit/local/atom/win_detect_move.js, test/unit/local/chokidar/initial_scan.js, test/unit/merge.js, test/unit/metadata.js, test/unit/move.js, test/unit/remote/index.js, test/unit/sync.js
Historically, document moves were merged in PouchDB by erasing the
record with the source path and creating a new record with the
destination path as record _ids were mapped to the path.
This way of doing things creates a number of difficulties (e.g.
inconsistencies if one record can be modified/created and not the
other as PouchDB does not offer transactions) and is not necessary
anymore since we've moved to generated _ids.
This change should give us opportunities in the future like linking
documents to their parent directory via its PouchDB record _id instead
of using a path attribute that can change or point to a different
document.
The main difficulty was managing overwrites as we were previously
using the overwritten record's _id as the destination record _id and
can't anymore as the …
=> core/merge: Handle moves on the same Pouch record

core/metadata.js, core/remote/index.js, core/sync/index.js, core/utils/notes.js, core/utils/timestamp.js, core/writer.js, test/integration/notes.js, test/support/builders/metadata/base.js, test/support/builders/remote/file.js, test/unit/remote/index.js
When synchronizing changes (other than a move or a deletion) on a
previously synchronized document, we need to compare the modified
metadata against a "previous" version to detect what needs to be
updated (i.e. either metadata or content, or nothing when it's just a
timestamp change).
We used to rely on the `sides` counters to decide how far to go back
in the PouchDB record's history to fetch this previous version.
However, this method is fragile and, in fact, unnecessary now that we
store the complete local and remote metadata in the record.
Thus, to propagate a local change to the remote Cozy, we can compare
the actual document's metadata against its remote metadata.
The same goes for propagating remote changes to the local filesystem.
This method has the added advantage of simplifying …
=> core/sync: Compare metadata against other side

core/local/chokidar/watcher.js, test/scenarios/create_dir_into_moved_one/local/darwin.json, test/scenarios/move_dir_a_to_b_to_c_to_b/local/darwin.json, test/scenarios/move_dir_into_created_one/local/darwin.json, test/scenarios/move_dir_reversed_events/local/darwin.json, test/scenarios/move_dir_successive_same_level/local/darwin.json, test/scenarios/move_dir_successive_same_level/scenario.js, test/scenarios/move_dir_successive_with_delay/local/darwin.json, test/scenarios/move_dir_with_content/local/darwin.json, test/scenarios/move_two_dirs/local/darwin.json, test/scenarios/move_two_dirs_same_prefix/local/darwin.json, test/unit/local/chokidar/watcher.js
If the local synchronization directory is empty when we start the
Desktop client, then the only event we'll receive and flush will be
for the synchronization directory itself (i.e. there aren't any
documents to emit `add` or `addDir` events). This event has no path
(i.e. events paths are relative to the synchronization directory
itself) and thus will be filtered out at the beginning of the
`onFlush` call.
This means that we won't have any events to call the initial scan
step on. However, we do need to run the step since the detection of
offline deletions is part of it.
Without this call we won't detect that the directory has been
emptied for example.
Some macOS scenarios started failing once this fix was introduced
but only for meaningless breakpoints (i.e. flushing points that don't
make …
=> core/local/chokidar: Run initial scan on empty dir

core/pouch/index.js, core/remote/index.js, core/sync/index.js, test/integration/add.js, test/support/helpers/remote.js, test/unit/remote/index.js
When we're looking for a directory by path (usually the parent
directory of another document), we make a request to the remote Cozy,
even if the directory probably hasn't changed since the last time we
requested it, just to get its `_id` and use it as the `dir_id` of its
direct children.
This is inefficient both for the Desktop client and the remote Cozy
and slows down the entire synchronization.
This is inefficient because we probably already have the information
we're looking for in the local PouchDB.
Besides, when we look for the parent directory of a document during
its synchronization, we should reason about the information on which
previous steps like Merge were based on and changed.
For example, when adding a file to a directory on the local
filesystem, we should be looking for the …
=> core/remote: Find remote parents in local Pouch

core/local/atom/win_detect_move.js
On Windows, moves trigger couples of `deleted` and `created` events
that we need to match to rebuild a `renamed` event.
If a directory with content is moved then we'll get a lot of `deleted`
events for its children between the directory's `deleted` and
`created` events.
Refreshing the timeout of the pending directory's `deleted` event
should make it more likely that we'll match it with its `created`
event.
=> core/local/atom: Keep Windows parent move events

core/merge.js, test/integration/add.js, test/integration/mtime-update.js, test/unit/merge.js
Ignore local events when the local metadata hasn't changed or only the
modification date has changed.
it would be preferable to store the new local date but we need
to avoid merging folder changes triggered while adding content (i.e.
adding a file in a directory triggers an `mtime` update on the file
system) and merged after we've synchronized a local renaming (i.e.
the change which was waiting to be dispatched is now obsolete and
merging it would cause issues especially after actions like a conflict
resolution).
Until we find a way to mark specific events as obsolete, our only
recourse is to discard these modification date changes.
=> core/merge: Ignore local folder mtime updates

CHANGELOG.md, package.json
- All child moves (i.e. document moved because their parent directory
was moved) will now be notified to the GUI so the child documents
paths can be updated in the list of recently synchronized documents.
- We've introduced a mechanism to detect dependencies between multiple
changes on the same side (i.e. the local filesystem or the remote
Cozy) and synchronize them in the right order. We've added a few
dependencies that let us solve situations that were known to fail
(e.g. trashing directories as a whole instead of trashing every
element separately) and we will add more as needed in the future.
- As stated above, directories will now be trashed as a whole but we'll
now also keep empty directories in the trash instead of erasing them.
It should be easier for …
=> Release v3.30.0-beta.1

core/app.js, gui/elm/Window/Onboarding/Address.elm, test/unit/app.js
- Allow port in HTTPS Cozy URL
Thanks @scjtqs for reporting this issue and offering a fix.
- Fix app name removal from entered address
- Auto-correct My Toutatice URLs
=> Fix Onboarding addresses auto-correction and validation

core/remote/cozy.js
We don't need all the Redux heavy lifting coming from Cozy-Client. It
can consume a lot of RAM (on large Cozy) for no good reason here. We
only need to query the remote Cozy and return the result, so we'll use
Cozy-Stack-Client directly.
The request limit was also increased to reduce the number of network
calls.
Thanks @Crash-- for this optimization.
=> core/remote: Speed up initial changes fetch

CHANGELOG.md, core/remote/cozy.js, core/remote/document.js, package.json, test/integration/move.js, test/unit/remote/cozy.js
The remote cozy-stack is now filtering more attributes if their values
aren't defined in CouchDB. This means that we won't receive their
default JSON equivalent anymore and we should provide default values
by ourselves.
=> core/remote/document: Provide default values

package.json, yarn.lock
This version brings:
- better `queryAll` performance
- automatic OAuth token refreshing
- correct file references modifications response (i.e. now includes
`meta` object, and `data` is always an Array)
=> deps: Bump cozy-client to v27.0.1

core/remote/cozy.js, core/remote/watcher/index.js, package.json, test/unit/remote/cozy.js, yarn.lock
Queries for remote files either during the initial changes fetch or for re-included folders (i.e. that were previously excluded via the partial sync configuration) were either slow because the wrong index (or no index) was used or didn't meet the partial sync requirements.
These commits fix these issues to make sure fetching remote changes goes smoothly especially after a fresh install.
=> core/remote: Fix remote files queries

core/remote/watcher/index.js, test/unit/remote/watcher.js
We make sure the same change will only get analyzed and merged once,
even if it was fetched again as part of a folder content listing.
When fetching remote changes, what can look to be a remote folder
re-included in the client's synchronization (i.e. it's a addition but
it's revision is greater than 1) may as well be a new folder that was
updated remotely before we got a chance to fetch it.
In this case, its content will already be present in the feed and we
should not waste time analyzing and merging it.
Simply comparing content changes' _ids and _revs with changes fetched
from the feed can tell us if they're duplicates or not.
=> core/remote: No folder content changes duplication

core/remote/cozy.js, core/utils/flags.js, package.json, yarn.lock
Local flags can be useful in some situations but they have limitations
as well:
- they can't be used until we have saved a local config since they're
part of it
- they can't be enabled or disabled globally
We're mostly trying to address the second issue here. Being able to
enable a feature globally via a context will be helpful when releasing
the partial synchronization as we need to enable it in the Desktop and
Settings application as the same time.
=> core: Fetch and merge flags from remote Cozy

core/remote/index.js, core/remote/watcher/index.js, test/unit/config.js
We'll want to use the same flag as the Settings app to enable partial
synchronization to release them together.
Thus we start using the new `flags` module which merges remote and
local flags.
The new partial synchronization flag name is:
`settings.partial-desktop-sync.show-synced-folders-selection`
=> core/remote: Use remote partial sync flag

core/app.js, core/config.js, core/remote/index.js, core/utils/capabilities.js, test/unit/config.js
We add a new module similar to the `flags` module, allowing us to
fetch the capabilities of the remote Cozy with just a valid `Config`.
This will allow us to use this data in places where we don't easily
have access to an instance of `Remote` or `RemoteCozy`.
The remote capabilities are stored locally for the duration of the
Desktop session. This will limit the number of requests made to the
Cozy for data that rarely changes.
=> core/utils: Add remote capabilities module

gui/elm/Data/AddressConfig.elm, gui/elm/Data/SyncFolderConfig.elm, gui/elm/Ports.elm, gui/elm/Window/Onboarding.elm, gui/elm/Window/Onboarding/Address.elm, gui/elm/Window/Onboarding/Context.elm, gui/elm/Window/Onboarding/Folder.elm, gui/elm/Window/Onboarding/Welcome.elm, gui/js/onboarding.window.js, gui/js/window_manager.js, gui/locales/de.json, gui/locales/en.json, gui/locales/eo.json, gui/locales/es.json, gui/locales/fr.json, gui/locales/it_IT.json, gui/locales/ja.json, gui/locales/nl.json, gui/locales/nl_NL.json, gui/locales/pl.json, gui/locales/sq.json, gui/locales/zh_CN.json, gui/main.js, gui/ports.js, gui/styles/_wizard.styl
Once the OAuth client used to communicate with the remote Cozy has
been created, we can offer users to configure the partial
synchronization of their remote folders.
To this end, we modify the Folder page of the Onboarding to display a
link to the OAuth client's configuration within the remote Settings
app.
For now, this link will only be displayed if the partial
synchronization flag is enabled on the Cozy.
=> gui/elm: Configure partial sync during Onboarding

core/remote/watcher/index.js
We want to be able to enable/disable a feature via a flag on the
remote Cozy or the local Config.
Checking the value of the local Config flags does not allow for that
while the new `flags` module does.
When we changed the partial synchronization flag in the
`RemoteWatcher`, we forgot to start using the module instead of the
Config.
=> core/remote/watcher: Use flags module

core/merge.js, core/remote/index.js, test/integration/notes.js, test/unit/merge.js, test/unit/remote/index.js
Until recent changes were made to `cozy-stack`, changes made to the
Markdown export of Cozy Notes could not be re-imported as actual Cozy
Note changes and would break the note, rendering it unusable as such.
Therefore, we would prevent such local changes by considering them as
conflicts.
Now that local content changes made to the export can be re-imported,
we can remove these protections.
We updated the tests to make sure the changes are actually taken into
account and don't create conflicts. They should probably be removed
after a while since this is the expected behavior of local file
changes.
=> core: Allow local Cozy Note updates

core/sync/index.js
The `Sync.skipChange()` method is asynchronous as it saves data in
PouchDB and its calls should be awaited.
We forgot to await 2 calls when dealing with missing parent errors. If
the change was the only one to synchronize or computing the dependency
tree was simply faster than the write into PouchDB then we could see
the change we wanted to skip being retried once more.
=> core/sync: Await skipChange calls

core/remote/cozy.js, gui/locales/en.json, gui/locales/fr.json, gui/main.js, gui/ports.js
When a Cozy is unreachable (e.g. because it's been revoked), requests
for flags and capabilities will fail and should be handled.
Besides, if the Cozy has been revoked, we should display the specific
error pop-up inviting the user to reconnect their Desktop client instead
of displaying the generic "Synchronization impossible" status.
=> Fix error management for unreachable Cozy

gui/js/tray.js, gui/main.js
We have witnessed de-synchronizations between the status within the
app's main Window and the systray which we believe arise from close
asynchronous status updates (partially) overwriting each other.
To prevent these, we will now enqueue those updates so only one is
processed at a time.
We also take the opportunity to reduce the number of systray image
changes which can be costly CPU wise.
=> gui: Fix Tray status updates

CHANGELOG.md, package.json
- The selective synchronization flag is fetched from the remote Cozy for
every use case.
- We fixed an issue in our synchronization process which could lead to
unnecessary metadata updates.
- When the app's OAuth client is revoked on the remote Cozy, fetching
the Cozy's flags and capabilities won't result into an error anymore
and the revocation pop-up will displayed again instead of the generic
"Synchronization impossible" status.
- GUI state updates will now be queued up to avoid having two close
updates overwrite each other and ending in a de-synchronized state
between the app's main Window and the systray.
=> Release v3.32.0-beta.2

core/remote/index.js, core/remote/watcher/index.js
We remove the flag protection for partial synchronization to fully
enable it.
Its configuration access via the on-boarding or the "Preferences" tab
in the main window are still hidden behind a flag though.
=> core/remote: Enable partial synchronization

CHANGELOG.md, package.json
- Selective synchronization is available behind the
`settings.partial-desktop-sync.show-synced-folders-selection` flag.
- The core of the synchronization process can handle selective
synchronization without flags (only the configuration of the selective
synchronization remains hidden behind a flag).
- The selective synchronization flag is fetched from the remote Cozy for
every use case.
- We fixed an issue in our synchronization process which could lead to
unnecessary metadata updates.
- When the app's OAuth client is revoked on the remote Cozy, fetching
the Cozy's flags and capabilities won't result into an error anymore
and the revocation pop-up will displayed again instead of the generic
"Synchronization impossible" status.
- GUI state updates will now be …
=> Releave v3.32.0

gui/js/onboarding.window.js, gui/js/tray.window.js, gui/js/window_manager.js
With Electron v12.x the DevTools window will only show up if it's
opened after the related BrowserWindow's content has already been
loaded (i.e. `loadUrl` or `loadFile` has been called).
Also, opening the tools when creating a new BrowserWindow means we
would always open them for the main window (i.e. the tray window)
while we don't necessarily want to work on it.
Therefore, we'll now open the DevTools only when calling the `show()`
method (we load the content while the window is still hidden to avoid
showing loading content).
=> dev: Fix devtools opening

core/pouch/index.js, core/remote/constants.js, core/remote/cozy.js, core/remote/watcher/index.js, test/integration/sync_state.js, test/support/helpers/remote.js, test/unit/remote/cozy.js, test/unit/remote/watcher.js
Directories content retrieval as part of the selective synchronization
can be quite costly and is particularly useless during the initial
content retrieval.
As such, we optimize both use cases to limit the number of requests and
thus memory consumption and retrieval time.
=> core/remote: Optimize directory content fetching

gui/styles/_statusbar.styl, gui/styles/_wizard.styl, gui/styles/app.styl
The method used to vertically center the spinner displayed in the
Updater window when no download progress information is available is
a Firefox experimental feature which has no effects in Chromium, the
browser used to render Desktop's views.
Besides, this hack was only necessary because the `spin` animation was
redefined in our own CSS because, in turn, we were adding an
unnecessary top margin on the main window's status bar spinner icon.
One fix leading to the other, we now have centered spinners in both
the status bar and the updater window.
We took the opportunity to use the same size for the status bar
spinner as the other status bar icons and to align these with the file
icons displayed below in the Recent tab.
=> gui: Fix Updater spinner's vertical alignment

CHANGELOG.md, package.json
- You can now open your Cozy within a Desktop window with a Ctrl-click
(Cmd-click on macOS) on the "Open Cozy" button in the main window. You
will have to enter your credentials the first time.
- You can now open folders in your Cozy with a Ctrl-click (Cmd-click on
macOS) on folder paths in the Recent tab of the main window or the
"Open folder" button.
- Paths displayed in synchronization error messages for changes coming
from the remote Cozy will now open in Cozy Drive Web since they might
not exist on the local filesystem and the solution probably resides in
remote actions.
=> Release v3.33.0-beta.2

gui/elm/Data/Confirmation.elm, gui/elm/Ports.elm, gui/elm/Window/Tray.elm, gui/elm/Window/Tray/Settings.elm, gui/js/tray.window.js, gui/js/window_manager.js, gui/locales/en.json, gui/locales/fr.json, gui/ports.js
Refactor the existing synchronization reinitialization confirmation 
request to create a general purpose confirmation process that can be 
used in different situations.
We take the opportunity to make sure the confirmation request is never 
hidden when the main window loses focus and does not prevent using the 
app's GUI afterwards.
=> gui: Create a general purpose confirmation process

core/remote/cozy.js, core/remote/index.js, test/support/builders/remote/dir.js, test/support/doubles/side.js, test/unit/merge.js, test/unit/remote/cozy.js
When a directory is re-included in the synchronization of a Desktop
client, we recursively fetch its content because it won't be present
in the changes feed (only the parent directory is modified when
re-including it).
When doing so, we should not fetch excluded sub-directories and their
content as they're still excluded.
We're filtering them out on the client side because doing it on the
server side would mean filtering without an index (it would require
the usage of `$exists: false` since the `not_synchronized_on`
attribute is not always present on directories and is never present on
files).
=> core/remote: Don't fetch content of excluded dirs

core/local/chokidar/normalize_paths.js, core/remote/watcher/normalizePaths.js, test/integration/id_conflict.js, test/support/helpers/platform.js, test/unit/local/chokidar/normalize_paths.js, test/unit/remote/watcher.js
HFS+ filesystems automatically re-encode utf-8 characters of document
names using the NFD norm when they were encoded with the NFC norm in
the first place. On the other hand, most filesystems and,
specifically, the remote Cozy filesystem, encode utf-8 characters with
the NFC norm.
This means that documents created on these systems will be
automatically renamed when Desktop creates them on the local HFS+
filesystem, generating unnecessary name changes.
We implemented a re-normalization process to try and keep the previous
normalization of document names in our local PouchDB database but we
did not account for cases where both norms coexist in the same
document name. In these cases, the re-normalization wouldn't work
(because we could not detect the one norm used) and, worse, conflicts
were …
=> core/lochokidar/normalize_paths: Normalize only when needed

CHANGELOG.md, package.json
- You should not see conflicts created anymore when a remote document
whose name contains multiple utf-8 characters encoded with NFC and NFD
norms is downloaded and saved on your local filesystem.
=> Release v3.33.0-beta.4

.github/workflows/linux.yaml, .github/workflows/macos.yaml
To generate the key that will determine if a new cache entry should be
generated or if an existing cache entry can be loaded, we would use
the Github Actions `hashFiles` helper on the directory containing
`yarn.lock`, thus on our entire code base plus the generated test
directories.
While this seemed to work, `hashFiles` was actually silently failing
to parse a directory generated during tests.
Github decided to throw an error instead and thus our builds started
to fail (i.e. only the cache generation failed).
Since this cache is meant for our Node and Electron dependencies, we
can generate the key by hashing only `yarn.lock` and thus fix this
issue.
=> ci: Fix Github Actions cache generation

core/metadata.js, core/pouch/index.js, core/remote/cozy.js, core/remote/watcher/index.js, test/integration/sync_state.js, test/support/builders/metadata/base.js, test/support/helpers/remote.js, test/unit/metadata.js, test/unit/remote/cozy.js, test/unit/remote/watcher.js
When a directory is re-included in a Desktop client's synchronization,
we need to manually fetch its content.
We used to do so sub-directory by sub-directory but this would require
a lot of fetch requests from the client on a large Cozy and could lead
to client crashes.
We then tried to fetch them layer by layer using a more complex Mango
query. Unfortunately, these requests could not make use of CouchDB
indexes and would be so slow on a large Cozy that we would never get a
response before the request would time out.
We're now trying a different approach. We'll fetch these
sub-directories one by one but we won't fetch all of them before
processing them. Instead, we'll merge a directory's direct content
before fetching the next sibling.
Sub-directories fetched in this process will be …
=> core/remote/watcher: Fetch directories one by one

CHANGELOG.md, package.json
- Old files with a creation date seemingly more recent than their last
modification date can now be moved or renamed. Their last modification
date will be updated in the process to match the most recent date
available.
- Re-included directories that need their content to be fetched manually
will be marked as such until their content is actually retrieved so we
can resume the operation in case Cozy Desktop is stopped in the
middle.
=> Release v3.33.0-beta.5

.github/actions/build-and-publish/action.yaml
We need to install extra linux packages to build our app on this
platform and unfortunately we were not updating the package list
before installing them.
This list has changed and the packages could not be installed anymore.
Simply updating the list before installing the packages fixes the
issue.
=> ci: Fix linux packages build

core/remote/change.js, core/remote/watcher/index.js, core/remote/watcher/squashMoves.js, test/unit/remote/watcher.js
Sub-directories of sub-directories of moved directories wouldn't get
their new remote revision saved in PouchDB thus triggering 412 errors
on following local updates.
Now descendant moves go up to the top-most directory move and the
revisions of all descendants are updated.
=> core/remote/watcher: Update revs of moved children

core/metadata.js, core/remote/change.js, core/remote/cozy.js, core/remote/document.js, core/remote/watcher/index.js, core/sync/index.js, test/support/builders/remote/base.js, test/support/builders/remote/dir.js, test/support/builders/remote/erased.js, test/support/builders/remote/file.js, test/unit/metadata.js, test/unit/remote/cozy.js, test/unit/remote/watcher.js
Files don't have a `path` attribute in the remote CouchDB (only
directories do) but we still rely on this attribute in Desktop so we
rebuild it using their parent's path.
However, the dedicated files' changes feed now has an option to
populate this attribute before it is sent to the client.
This greatly simplifies our changes feed interaction code and types.
Also, this forces us to use the `cozy-client` changes feed method
since the one in `cozy-client-js` does not use the dedicated files
feed and thus cannot return file changes with a `path`.
=> core/remote: Fetch file changes with path

core/merge.js, core/metadata.js, core/remote/constants.js, core/remote/cozy.js, core/remote/document.js, core/remote/index.js, core/remote/watcher/index.js, core/utils/array.js, core/utils/notes.js, dev/capture/remote.js, test/integration/platform_incompatibilities.js, test/support/builders/index.js, test/support/builders/metadata/base.js, test/support/builders/remote/base.js, test/support/builders/remote/dir.js, test/support/builders/remote/erased.js, test/support/builders/remote/file.js, test/support/builders/remote/note.js, test/support/helpers/remote.js, test/unit/metadata.js, test/unit/remote/cozy.js, test/unit/remote/index.js, test/unit/remote/watcher.js, test/unit/utils/array.js
We want to use old file versions stored in the remote Cozy to avoid as
many conflicts as possible and even "fix" existing ones. To do so,
whenever a situation would trigger the creation of a conflict we'll
fetch the conflict remote file's previous versions from the remote
Cozy and, if the local content can be found in one of them, we'll
write the remote content on the local filesystem instead of creating a
conflict.
This PR creates the few methods that we'll need to run these checks.
=> Add file versions manipulation methods

core/app.js, core/migrations/constants.js, core/migrations/index.js, core/migrations/migrations.js, core/pouch/index.js, gui/main.js, test/unit/migrations/index.js, test/unit/pouch/index.js
Sub-directories of sub-directories of directories moved on the remote
Cozy would not see their new remote revision stored in PouchDB,
resulting in 412 errors when the user would modify them on their local
filesystem (i.e. since we don't have the latest revision, our
modifications are rejected by the remote Cozy).
This bug was fixed in #2216  but directories moved until now are still
affected by the issue.
We solve this problem here by fetching and updating in PouchDB the
latest remote revision of all directories if the remote metadata is
equivalent (we only compare a few attributes that we really care about
like the path, the tags…).
This is done via a migration and therefore these can now make use of
the `Remote` module to make calls to the remote Cozy.
Please make sure the following …
=> Update remote revision of directories affected by move bug

gui/js/onboarding.window.js
If the user decides to read our TOS during the on-boarding process,
opening them in the on-boarding window will prevent them to finish the
process as there is no way to go back to the OAuth dance.
Besides, these TOS are written in a PDF file rather than an HTML page
and does not seem to be readable within the OAuth webview.
To make sure the user can read the TOS and continue the on-boarding
process, we'll intercept navigation to PDF files and open the given
URLs in the external browser.
=> gui: Open Cozy TOS in external browser

core/local/index.js, core/remote/errors.js, core/remote/index.js, core/remote/watcher/index.js, core/sync/errors.js, core/utils/lifecycle.js, test/support/helpers/remote.js, test/unit/remote/errors.js, test/unit/remote/watcher.js, test/unit/sync/errors.js, test/unit/sync/index.js
Network errors thrown while a file is being transferred to or from the
Cozy should be handled as `FetchError` errors so our error handling
mechanisms will work.
This includes showing proper error messages, retrying transfers and
avoiding blocking the client.
This PR solves multiple problems at once:
- `net::*` errors are handled as `FetchError` errors
- file transfers are retried as quickly as possible for a limited amount
of network errors
- the remote watcher does not try to make calls to the remote Cozy when
stopped
- the synchronization process does not get blocked for more than one
reason at any given time (since it can only get unblocked for one
reason)
=> Handle network errors during file transfers

CHANGELOG.md, package.json
- During the client's on-boarding process, clicking on the ToS link (or
any link pointing to a URL ending with `.pdf`) will open the pointed
URL within the external browser rather than the on-boarding window.
- Network errors during the synchronization of a change should not
result in a blocked synchronization anymore.
- Network errors during a file transfer either from or to the remote
Cozy will now be handled properly, restarting the transfer until too
many errors are encountered and the global error handling mechanism
takes over.
=> Release v3.34.0-beta.2

core/migrations/migrations.js, core/utils/sentry.js, gui/main.js
We've seen a surge of migration failures with the last release which
includes a migration making network requests.
This PR aims at preventing these failures and making sure Sentry
exceptions include more details to help us debug migration errors in the
future.
=> Fix latest migration failures

core/migrations/migrations.js, core/remote/cozy.js, test/unit/remote/cozy.js
In the latest migration, we make requests to the remote Cozy to fetch
the latest version of known directories from their _id.
However, these known directories can have been deleted on the Cozy.
This was expected and the migration can deal with missing directories
but the method we were using the fetch the directories would throw on
missing documents instead of returning the expected `null` value.
This leads to failing migrations.
To avoid this, we created another method returning `null` instead of
throwing when the expected remote directory is missing and we'll use
it in the migration.
=> core/migrations: Use non-throwing remote methods

core/incompatibilities/platform.js, core/merge.js, core/metadata.js, core/move.js, test/scenarios/move_overwriting_dir/with_unsynced_dir/atom/linux.json, test/scenarios/move_overwriting_dir/with_unsynced_dir/scenario.js, test/scenarios/move_overwriting_file/with_unsynced_file/atom/linux.json, test/scenarios/move_overwriting_file/with_unsynced_file/scenario.js, test/support/builders/metadata/base.js, test/unit/incompatibilities/platform.js, test/unit/merge.js, test/unit/metadata.js, test/unit/move.js, test/unit/remote/watcher.js
When a document existing only on side (i.e. not synchronized yet) is
moved, we convert the move into a creation at the move's destination
(because the move could not be synchronized since the document does not
exist on the remote Cozy).
Also, when we're dealing with an overwriting move, we transform it into
an update of the overwritten document instead (and make sure we don't
leave traces of the source of the move in PouchDB).
Failing to do so would result in:
- having 2 records with the same path in PouchDB which can lead to
requests issues (they're based on the path and we're not sure which
record would be returned)
- conflicts when trying to synchronize the creation of the local
document on the remote Cozy since there is another document at the
same path
Please make sure the following …
=> core/merge: Handle unsynced document moves

core/app.js, core/migrations/index.js, gui/js/actions.js, gui/js/tray.js, gui/js/tray.window.js, gui/main.js
When migrations making requests to the remote Cozy encounter a revoked
OAuth client error, we should display this error to the user and allow
them to go through the on-boarding again instead of displaying the
failed migration error which will prevent them from running the client
until the configuration folder is deleted.
=> core/migrations: Handle revoked client errors

core/sync/index.js, test/unit/sync/index.js
When content is moved to a directory that was just created (and not
synced yet), we would try to synchronize the move first.
This would raise synchronization errors as the directory would not
exist on the other side. It would eventually work after retrying
(since we would finally get to synchronize the directory creation) but
this slows down synchronization (especially if a lot of documents were
moved to the directory) and could be the source of more problems
(de-synchronized states is never good).
Simply adding a comparison rule between these changes forces the
synchronization of the directory's creation first and prevents retries
for the content move.
=> core/sync: Dir creation before moves from outside

electron-builder.yml
*.node only matches files at the root.
**/*.node matches any file in the tree.
This should properly implement https://github.com/cozy-labs/cozy-desktop/pull/1846 (in addition to reasons mentioned
there, it should be noted that extracted files are not cleaned upon
exit, so this is yet another reason to have them unpacked from the
start).
=> build: Really unpack native modules

core/remote/cozy.js, core/remote/document.js, core/utils/logger.js, test/unit/remote/cozy.js
We added our own `RemoteCozy.queryAll()` method to fetch the content
of a directory from the remote Cozy but its implementation was flawed
and would result in errors when there were multiple pages of documents
to fetch (i.e. we use 3000 docs pages).
Instead of fixing this implementation, we will now use `cozy-client`'s
`queryAll()` method which is battle tested.
I don't understand why we didn't use it before.
=> core/remote/cozy: Use cozy-client queryAll method

test/support/helpers/context_dir.js, test/support/helpers/scenarios.js
Recursive `fs.rmdir` calls have been deprecated in favor of recursive
calls to `fs.rm` and the deprecation warning is seen as an error by
AppVeyor thus failing the scenarios job.
Replacing these calls should get us a green CI again.
=> test/helpers: Replace deprecated recursive rmdir

core/merge.js, test/support/builders/metadata/base.js, test/unit/merge.js
Since trashing a document on the remote Cozy changes its CouchDB
revision, we need to store this updated metadata in our local PouchDB.
This makes future changes on the remote doc and detecting that the
trashed remote document is up-to-date possible.
We were updating the remote revision only when the doc had previously
been moved and that move wasn't synchronized yet.
We're now saving the complete updated remote metadata whenever merging
a document trashing (this includes the `trashed` attribute).
=> core/merge: Update remote metadata of trashed docs

.github/workflows/macos.yaml, electron-builder.yml
Although our users install Cozy Desktop via the `dmg` target on macOS,
the `zip` target is still required for the updater to work.
Indeed, if the generated zip file isn't published, the updater will
fail as it is looking for its presence.
The issue has been reported a long time ago in
https://github.com/electron-userland/electron-builder/issues/2199 but
there is no recent work on any potential solution.
=> dev: Build and publish zip target on macOS

CHANGELOG.md, package.json
- We made sure to properly save the metadata of documents trashed on the
remote Cozy so Cozy Desktop won't try to fetch that change again and
potential local modifications made on the document can be synchronized
with the remote Cozy.
- Documents moved out of a remote directory subsequently trashed or
completed erased should now be moved out their local parent before it
is trashed on the local filesystem. This ensures Cozy Desktop will be
able to synchronize both changes.
- The previous beta release broke the auto-update feature on macOS as we
stopped packaging Cozy Desktop in a format that we thought unused. We
brought back this packaging so users running a previous beta version
should be able to update once again.
=> Release v3.36.1-beta.2

core/local/chokidar/send_to_prep.js, core/merge.js
When a document being synchronized with the remote Cozy is moved on
the local filesystem, we fail to merge the move in PouchDB because we
fetch the source record before it is updated by Sync (i.e. to add the
remote info) and get a conflict error since we don't have the new
revision.
Fetching the source record (again) right before merging the move, when
Merge has the PouchDB lock, solves this problem.
This should not create new issues as Merge should be able to handle
potential situations where changes to the source record are more
substantial than adding remote metadata.
=> fix: Avoid PouchDB conflicts when merging moves

.github/actions/setup-cozy-stack/action.yaml, .github/workflows/macos.yaml, electron-builder.yml, package.json, yarn.lock
The `macos-10.15` runner is deprecated since 5/31/22 and will be
unsupported by 12/1/22 (see
https://github.com/actions/runner-images/issues/5583).
We did not upgrade before because the `macos-11` runner does not
provide VirtualBox which we need to create an Ext filesystem for
`cozy-stack` (see
https://github.com/actions/runner-images/pull/4010 for more details on
previous attempts to add it to `macos-11`)
and it was not yet available in the `macos-12` runner.
It's now available in `macos-12` (see
https://github.com/actions/runner-images/pull/5594) so we can upgrade
to `macos-12`.
=> ci: Upgrade github actions macOS runner

.github/workflows/linux.yaml
Fixes #2283 
The symbol used to compile our native addons depend on the version of
the OS on which they're compiled.
We've lost compatibility with some LTS OS versions like Debian stable
and Ubuntu 20.04 because of an upgrade of the runner image so we're
switching to a specific version, ubuntu-20.04.
=> ci: Use older linux GA runner image

CHANGELOG.md, package.json
Improvements for linux users:
- We reverted our build machine Ubuntu version back to v20.04 as newer
versions make our native addons such as the Linux local watcher
incompatible with some current LTS versions of popular distributions
like Ubuntu and Debian.
This change does not have short term drawbacks.
=> Release v3.38.0-beta.1

gui/ports.js
Until now, partial synchronization was hidden behind a feature flag.
Although this flag was enabled on all `mycozy.cloud` instances, this
requires self-hosted administrators to think about activating it.
The feature is mature and can be enabled everywhere (unless the flag
is present and disabled).
=> feat: Enable partial synchronization by default

test/support/helpers/index.js, test/unit/sync/index.js
We use the Sync lifecycle module to follow state changes and take
actions upon them. This is done via async methods which return
Promises resolving when a specific state is transitioned to.
However, in tests, we were modifying the state by hand so the
associated events would not be fired and the Promises waiting for them
would never resolve. This resulted in tests failing from time to time,
especially in the Windows and macOS CI builds.
We replaced all the manual state changes with the appropriate
transitions.
=> fix: Use Sync lifecycle state transitions in tests

core/merge.js, core/sync/index.js, test/integration/update.js, test/unit/merge.js
Some synchronization errors are not expected to resolve themselves in
time and each failed attempt will increase an errors counter on the
Pouch document until we've reached a maximum number of retries and
decide to stop trying.
However, if new changes for the document are merged, we should clear
the errors counter and try to synchronize the document as the errors
might be fixed at this point.
=> fix: Clear errors counter after each merge

core/local/index.js, core/utils/fs.js, test/support/doubles/fs.js, test/unit/local/index.js
Sending a document to the trash can fail for various reasons, one of
them being the absence of a trash (e.g. on Windows network shares).
In this case the document would remain in the user's local
synchronization directory while it's been deleted on their Cozy.
To prevent this state, we'll catch trash errors and try to permanently
delete the document.
In a second time, we might want to mark the trashed document on the
remote Cozy to alert the user that document might not be recoverable
from a local trash (if all connected Desktops's OSes don't have a
working trash for example).
=> fix: Handle send to trash errors

gui/js/tray.window.js
When closing the application from a user request (via the "Quit"
button for example), we first stop the synchronization to avoid
corrupting data.
However, we were not waiting for the synchronization to be fully
stopped (i.e. it is an asynchronous process) before closing the
application.
We believe this might be the source of crashes on Windows.
=> fix: Await full sync stop before closing the app

CHANGELOG.md, package.json
- Google Chrome's temporary download files will now be ignored by the
local changes watcher.
This will prevent synchronization attempts while the file is being
downloaded as they will most probably fail and are useless since the
temporary file will be removed in the end.
- We'll now try to synchronize documents that were modified even after
multiple previous failed attempts as the new changes might fix the
previous issues.
- Documents trashed or erased on the remote Cozy will now be erased on
the local filesystem when they cannot be trashed (because the Trash is
configured to be skipped or because the synchronized directory is
located on a network disk without any Trash).
This will prevent de-synchronization between the local …
=> Release v3.38.0-beta.3

gui/js/tray.window.js
This reverts commit 0901d11ead767a16e3ae3dfe6048f248e4f5a1fb.
By awaiting the full sync stop, we prevent quitting the app during a
synchronisation or a watcher run while these can take a very long time
(especially the first scan of local and remote changes).
We'll bring back this behavior once we have a way to cancel the
on-going sync and watch runs.
=> Revert "fix: Await full sync stop before closing the app (#2300)"

CHANGELOG.md, package.json
- We've activated the partial synchronization feature by default. It can
still be disabled by setting the
`settings.partial-desktop-sync.show-synced-folders-selection` flag to
`false` either in the client's config or on the Cozy itself.
- Google Chrome's temporary download files will now be ignored by the
local changes watcher.
This will prevent synchronization attempts while the file is being
downloaded as they will most probably fail and are useless since the
temporary file will be removed in the end.
- We'll now try to synchronize documents that were modified even after
multiple previous failed attempts as the new changes might fix the
previous issues.
- Documents trashed or erased on the remote Cozy will now be erased on
the …
=> Release v3.38.0

core/remote/watcher/realtime_manager.js, gui/js/network/index.js
When replacing `electron-proxy-agent` with our custom implementation
of a proxy agent, we replaced the `globalAgent` of both `http` and
`https` modules but left `http.Agent.globalAgent` untouched.
Unfortunately, this prevented our `WebSocket`s to connect when the
Sentry SDK was setup as its wrapper over `http.request` would make
changes to the protocol being used to make the connection.
It seems that the protocol used was the one of
`http.Agent.globalAgent` so replacing this agent again fixes the
issue.
This also allows us to stop passing a custom agent to the `WebSocket`
constructor and thus simplify the use of `cozy-realtime`.
=> fix: Replace default http Agent with ProxyAgent

core/utils/sentry.js, core/utils/time.js
Desktop was not filtering events sent to our Sentry server which could
result in a lot of events being sent at once when facing an issue
which is not resolved quickly during an operation which is retried or
done repeatedly (e.g. errors raised while trying to access PouchDB
while the db is corrupted).
We will now keep track of all events sent in the past 24 hours (or
since the app was last started, whichever is the most recent) and will
only send events that were not sent already in this timespan.
=> feat: Send same Sentry event at most once per 24h

gui/js/onboarding.window.js
It seems our OAuth `BrowserView` can be undefined when it's time to
close it.
Although we're uncertain why, it could be Electron closes it already
when loading the redirect URL.
Anyway, we can check for its presence before trying to close it and
avoid errors.
=> fix: Close OAuth BrowserView only if present

gui/js/onboarding.window.js
By default when links have a `_blank` target, Desktop will open the
targeted page in a new window.
However, we'd like these to be opened in the user's default browser
instead as a mechanism to control where links rendered by `cozy-stack`
should be opened.
=> feat: Open _blank target links in defaut browser

CHANGELOG.md, package.json
- OpenOffice lock files won't be synchronized anymore.
- The onboarding window will now honor `_blank` link targets during the
onboarding process by opening the targeted URL in a default browser
tab rather than a new Cozy Desktop window.
=> Release v3.39.0-beta.4

.tx/config
Transifex stops February 12 their API v2. Therefore, we are migrating the configuration to v3. If you were using a [transifex-client](https://github.com/transifex/transifex-client), you also must move to [Transifex CLI](https://developers.transifex.com/docs/cli) to be compatible with the v3 API.
=> chore: Migrate transifex config from v2 to v3

core/remote/watcher/index.js, core/sync/index.js, gui/main.js, test/unit/remote/watcher.js, test/unit/sync/index.js
Using Electron's power monitoring, we can make sure the watchers and
the synchronization are stopped when the power is suspended and
started again when the power is resumed.
This has 2 benefits:
1. avoid delays to the power suspension (OSs try not to stop active
processes)
2. make sure event loops are reactivated when power is resumed as this
seems to be an issue with Electron (see
https://github.com/electron/electron/issues/4465)
The second point seems to be particularly true on macOS where we see
the remote watcher stop working completely sometimes after a long
suspension time.
=> feat: React to power being suspended/resumed

.appveyor.yml, build/windows/customSign.js, build/windows/setup-keylocker.ps1, build/windows/sign.ps1, build/windows/verify.ps1, dev/remote/generate-test-env.js, electron-builder.yml
Following changes to the internation recommandations regarding code
signing certificates issuance and storage, DigiCert does not allow
simply downloading a certificate and use it to sign binaries.
Instead, we need to store it in a HSM or, as we chose, in a
cloud-based HSM such as DigiCert Keylocker.
This means we need to install tools to fetch the certificate from the
HSM prior to signing our software and also use a custom signing script
as `electron-builder` does not support Keylocker out of the box.
The process is split into 3 phases:
1. download the DigiCert client and the certificate
2. sign our binaries
3. verify the signature
=> ci: Sign Windows binaries using Digicert Keylocker

CHANGELOG.md, package.json
- We will now fetch the latest changes from your Cozy as soon as they've
been made (with some delay in case many changes were made). This
feature is hidden behind a flag so we can do more tests in live
conditions before releasing it to everybody.
- We fixed our network configuration as it was preventing the realtime
manager, responsible for fetching changes from your Cozy as soon as
they've bee made, to create a connection with the Cozy.
- OpenOffice lock files won't be synchronized anymore.
- The onboarding window will now honor `_blank` link targets during the
onboarding process by opening the targeted URL in a default browser
tab rather than a new Cozy Desktop window.
- Cozy Desktop will now stop its processes when power is suspended and
restart them when …
=> Release v3.39.0

package.json, yarn.lock
Necessary to catch Invalid Token errors returned by `cozy-stack` with
a 401 HTTP status (instead of the 400 status used historically).
=> deps: Upgrade `cozy-client-js` to 0.21.0

CHANGELOG.md, package.json
- We anticipate changes in the way the remote Cozy will inform
Cozy Desktop that its OAuth token has expired and should be refreshed.
=> Release v3.40.0-beta.1

test/support/builders/metadata/base.js, test/unit/remote/index.js
=> test: Fix tests failing intermittently on CI

core/local/chokidar/analysis.js, core/local/chokidar/local_change.js, test/unit/local/chokidar/analysis.js
=> fix: Handle deletion/move after move on macOS

.appveyor.yml, build/windows/customSign.js
Since we switched to using DigiCert's cloud HSM for code signing
certificate storage (the other option being using a hardware token),
we have been limited to 1000 code signatures per year.
We could increase the number of allowed signatures at a cost.
We choose to stop signing binaries generated by Pull Requests as
they're not published.
=> ci: Sign Windows binary on master only

dev/remote/automated_registration.js
When `cozy-stack` returns an error response to an OAuth authorization
request, we throw a Javascript error with the response body.
However, when the body is a JSON object, we only get its type in the
error message rather than the content itself.
By stringifying the body, we make sure its content will be included in
the error message and thus displayed in the logs or console.
=> ci: Stringify automated registration errors

.appveyor.yml, .github/workflows/linux.yaml, .github/workflows/macos.yaml, build/windows/customSign.js
=> ci: Fix code signing on Windows

electron-builder.yml, package.json, yarn.lock
This is the latest version of v24.x and brings tag builds detection on
Github Actions (which we need to build and publish releases on tag
push).
=> deps: Upgrade electron-builder to v24.13.3

core/app.js, core/utils/logger.js
Bring back the debugging logs we're used to so we can help our users.
=> fix: Increase logging

gui/ports.js, package.json
Modules can only be required in renderer scripts via
`@electron/remote`.
Doing otherwise will throw an error and prevent the script from
executing properly.
This would manifest itself in an empty GUI.
=> fix: Require `flags` in GUI via Electron remote

core/utils/sentry.js
To help Sentry group similar errors together, we set the message
fingerprint ourselves with the error's name and message and the
originating logger name.
However, if we trying to send a message to Sentry without an error
(i.e. we logged a message with the `sentry: true` option), trying to
get its name or message will throw an error for trying to get
attributes of `undefined`.
Therefore, we'll set the fingerprint manually only when sending a
message related to an error.
=> fix: Setup Sentry fingerprint for errors only

core/app.js, core/utils/logger.js, core/utils/sentry.js, test/property/local_watcher/index.js, test/support/hooks/logging.js
In order to improve performance, we reduced the amount of logs written
to disk by setting the maximum level logged to `info` by default.
However, we left the level of the logger itself to `trace` so we could
increase the amount of logs written to disk via a flag and it turns
out we would not see the expected performance improvements because of
this.
By managing the logging level on the logger itself we make sure
`winston` won't process `debug` and `trace` logging calls unless we've
enabled the debug flag or set the `DEBUG` env variable.
=> fix: Manage logging level on logger itself

core/remote/watcher/index.js
Keep reducing logs to decrease IO pressure and RAM usage when
receiving numerous changes from the remote Cozy.
=> tech: Remove remote change log

core/sync/errors.js, core/sync/index.js
Winston loggers expect the message to be the first argument and extra
options as the other ones.
Failing to do that results in messages to be interpreted as options
and transformed into objects and finally not being properly displayed
(or filterable) when debugging.
=> fix: Pass message to log calls as first argument

.jq, core/pouch/index.js, test/unit/pouch/index.js
Large `bulkDocs` calls (i.e. with thousands of documents to save at
once) can be the source of crashes.
We're not sure if this comes from PouchDB or the logger calls with
each document but we've figured that creating smaller batches of
documents, logging them all at once and then saving the batch in
PouchDB prevents crashes.
It should also result in less I/O since we're making a lot less logger
calls.
To accommodate for these logging changes, we update our `jq` `path`
filter so it looks into batches for documents with the expected path.
=> fix: Break down large PouchDB.bulkDocs calls

core/local/channel_watcher/dispatch.js, test/integration/add.js, test/integration/case_or_encoding_change.js, test/integration/conflict_resolution.js, test/integration/differential_sync.js, test/integration/executable.js, test/integration/full_loop.js, test/integration/id_conflict.js, test/integration/interrupted_sync.js, test/integration/move.js, test/integration/mtime-update.js, test/integration/notes.js, test/integration/permanent_deletion.js, test/integration/platform_incompatibilities.js, test/integration/sync_state.js, test/integration/trash.js, test/integration/update.js, test/unit/remote/offline.js, test/unit/remote/realtime_manager.js
Some tests are the cause of errors (while not turning red) as they
start background processings which are not stopped at the end of the
tests and end up trying to access a destroyed database.
Stopping these processings will prevent those errors and might improve
test performance.
=> test: Prevent excessive errors during tests

core/local/channel_watcher/index.js, core/local/channel_watcher/parcel_producer.js, core/local/chokidar/event_buffer.js, core/local/chokidar/watcher.js, core/local/index.js, core/local/watcher.js, core/remote/index.js, core/remote/watcher/index.js, core/sync/index.js, test/unit/local/chokidar/event_buffer.js
When we started reacting to OS's suspend and resume events, we took
the simple route of stopping and restarting both the remote and local
watchers each time.
However, this is time consuming, especially with the local watcher
since it does a full scan of the local synchronization directory on
start, and quite unnecessary since there little change we missed a
local event while the computer was suspended.
This is why we now introduce suspend and resume actions which, for the
local watcher at least, only take care of stopping and restarting
their event subscriptions.
This should improve performance when resuming a suspended computer.
For now the remote watcher still does a complete stop and restart as
it does not trigger expensive computing.
=> feat: Add suspend and resume actions to watchers

gui/styles/_updater.styl
The spinner was slightly off, being pushed down 50% of its height.
=> fix: Vertically center updater progress spinner

gui/main.js, gui/utils/notes.js
Desktop registers with the OS as being able to open Cozy Note
documents. Thus, when a user opens a local `.cozy-note` file Desktop
opens the associated note in the default browser.
On Linux and Windows we receive one of two events depending on the
state of the application when the file is opened:
- `second-instance` when Desktop was already running
- `ready` when Desktop was not running
In both cases the file path is found in the execution arguments.
On macOS however, the file path will be made available via a dedicated
`open-file` event in both situations.
When the application is not running though, we'll also receive a
`ready` event **after** the `open-file` event.
This is where we encountered a deadlock situation:
- when receiving the `ready` event, we setup the application and start …
=> fix: Setup Desktop before opening notes on macOS

core/metadata.js, test/integration/trash.js, test/unit/metadata.js
When merging the trashing of a document, we add a `trashed` marker in
its metadata for the side on which it was trashed (e.g. in the
`remote` attribute if the document was trashed on the Cozy) as well as
its global metadata.
However, when a directory is trashed, we also mark all its children
and these might not have been synchronized yet and the trashed side
metadata can be missing.
e.g. given we have the synchronized directory `dir/` and a local only
file `dir/file`, when merging the trashing of `dir/` on the Cozy we:
1. mark `dir/` as trashed and its `remote` attribute
2. try to do the same for `dir/file` but it has no `remote` attribute, only a `local` one
We were not checking for the presence of the `remote` attribute and in
this case we would end up with an error while trying to mark …
=> fix: Do not mark undefined remote as trashed

core/local/chokidar/watcher.js
We wanted to stop watching local changes with Chokidar when macOS goes
to sleep and restart when resuming but it appears the `unwatch`/`add`
duo of Chokidar methods does not work as expected (i.e. they at least
don't seem to be recursive).
This was preventing the local watcher from doing its job after macOS
resumed from sleep so we'll try not to stop watching the local changes
when going to sleep.
If this has advert effects on the suspension we'll try to find another
way.
=> fix: Keep watching local changes after suspension

.github/workflows/linux.yaml, .github/workflows/macos.yaml, package.json, yarn.lock
`upload-artifact` v3 has been deprecated for a while now and Github
Actions prevent its use now by automatically failing any job using it.
Besides upgrading to the latest major version of the action, we add a
compression level option that should better suit our needs (i.e. large
files not easily compressed).
See https://github.com/actions/upload-artifact/tree/v4.6.1?tab=readme-ov-file#usage
=> ci: Upgrade `upload-artifact` action to v4

elm.json
`elm-explorations/test` < v2.0.0 is not compatible with the new
`elm-test` version we recently upgraded to thus preventing us from
running elm tests.
=> deps: Upgrade `elm-explorations/test` to v2.2.0

core/merge.js, test/unit/merge.js
When a local file move to a destination where a file already exists is
converted into an update of the existing file, if the existing and
moved files have the exact same modification date then the
modification will be ignored and not saved in PouchDB.
This choice was made on purpose to avoid merging intermediary file
changes in some situations like the propagation of a remote change to
the local filesystem.
Although having the exact same modification date for 2 files should be
almost impossible in production, it can quite easily happen in tests
where documents and their metadata are generated very closely.
This was the case in the unit test for this specific situation which
was failing from time to time (more often on the CI).
=> test: Fix flaky merge unit test

test/unit/merge.js, test/unit/remote/cozy.js
Some actions on `io.cozy.files` documents require them to have an
`updated_at` date attribute more recent than their `created_at`
attribute.
Although having the exact same modification date for 2 files should be
almost impossible in production, it can quite easily happen in tests
where documents and their metadata are generated very closely.
This is why we sometimes need to make sure the modification date is
increased between two versions of a document in unit tests.
=> test: Fix flaky merge unit tests

.github/workflows/macos.yaml
We need to cache node modules not only by OS name and node version but
also by Github Actions runner arch as some dependencies are compiled
and thus not compatible with both arm64 and x86-64 versions of macOS.
Our macOS workflow has been running two different versions of macOS
for a little while now as we need an arm64 runner to create a arm64
binary (this runner still allows us to create an x86-64 binary).
Besides, the job responsible for creating binaries is one of the first
to run (because its name is `build` and jobs are run in alphabetical
order) and thus would update the shared node modules cache when it is
required (e.g. when upgrading a dependency).
We recently removed `cozy-client-js` from our dependencies so the
cache was updated by the arm64 job and all jobs running on a x86-64 …
=> ci: Separate node modules caches by arch on macOS

core/local/index.js, core/reader.js, core/remote/index.js, core/sync/index.js, test/unit/local/index.js, test/unit/remote/index.js, test/unit/sync/index.js
To make finding trashed documents and their restoration easy for
users, we want to keep a folder's hierarchy when trashing it rather
than trashing each element separately which would put them all at the
trash's root.
However, when deleting a folder with content on the local filesystem, we
receive events for the deletion of each document and the event for the
folder itself can be received last (e.g. on linux).
When there's no delay in the processing of these events (e.g. on macOS
we buffer events for 10 seconds before processing them), we can end up
propagating the deletion of the folder's content before we even got
the chance to merge the folder's deletion.
In this situation, we'll end up trashing each document separately.
Rather than adding delay on all platforms, we add a new check …
=> feat: Always detect complete local folder deletion

build/afterPackHook.js, build/launcher-script.sh, doc/usage/build.md, doc/usage/linux.md
AppImage binaries are in fact composed of multiple files including the
actual binary that will be executed to run the app.
We have references to this internal binary in our codebase because we
replace it with a custom launcher script to disable Electron's chrome
sandbox (we use another kind of sandbox).
However, when we renamed Cozy Desktop into Twake Desktop, we forgot to
change these references and the resulting AppImage did not run.
It's all good now.
=> fix: Change references to internal binary on linux

gui/js/onboarding.window.js
To check if the given instance URL is a valid one and get its root
form (i.e. the instance domain), we use a `cozy-client` helper
(`rootCozyUrl`) that makes calls to the `/.well-known/change-password`
route on the server.
This route redirects requests to the Settings app and in fine to the
OIDC start route and the SSO since we're not logged in.
It turns out that some SSO can store a cookie when reaching the login
page which prevents overwriting the successful login redirection if
another call to the login page with a different redirection URL is
made.
In this case, the requested OAuth registration redirection is not
acknowledged and the user gets redirected to the Settings app instead
of the OAuth permissions page thus preventing the completion of the
process.
By clearing out cookies …
=> fix: Remove cookies before starting registration

gui/js/updater.window.js, gui/locales/en.json, gui/locales/es.json, gui/locales/fr.json
The Twake Desktop rebranding cannot be properly achieved for current
users as some Cozy icons and texts would remain or old executables
even.
To prevent this unideal situation, we prefer to block upgrades for
current Cozy Desktop users and invite them to install Twake Desktop in
its stead.
/!\ This will need to be reverted for the Twake Desktop launch.
=> feat: Block upgrade for existing users

.appveyor.yml
We avoid signing code for builds other than tags on the master branch
as we have a limited number of signatures included with our
certificate purchase.
However, we might want to sign our executables in other situations so
allowing to force code signing would be helpful (e.g. creating
hot fix releases from version branches).
=> ci: Allow forcing code signing on AppVeyor

electron-builder-config.js
`electron-builder` does not quote the AppImage description so newlines
will create new lines in the output `.desktop` file making it invalid
and thus breaking the integration with the OS.
We added these newlines in the javascript version of our
`electron-builder` config file as the description was on multiple
lines in the yaml version but apparently the description was written
in one line in the output before.
Since we don't really care about the format of the description we
simply removed the newlines.
=> fix: Remove newlines from AppImage description
